### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by Orace** [dotnet/docs-desktop#1014]
In the second paragraph,
In the sentence

 > To get the resource dictionaries for the desktop themes, see [Default WPF Themes](https://github.com/Microsoft/WPF-Samples/tree/master/Graphics/2DTransforms).

The link points to a page that has nothing to do with xaml themes.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 60c5ae30-77fe-da6e-a320-17a4e734f0cd
* Version Independent ID: ba7cff33-a2c3-ae78-c1c6-ad0839c03ad4
* Content: [Styles et modèles Control - WPF .NET Framework](https://docs.microsoft.com/fr-fr/dotnet/desktop/wpf/controls/control-styles-and-templates?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/controls/control-styles-and-templates.md](https://github.com/dotnet/docs-desktop.fr-fr/blob/live/dotnet-desktop-guide/framework/wpf/controls/control-styles-and-templates.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by ArrowRaider** [comment]
Someone who works at Microsoft doesn't know where their own source code is?

**Comment by ArrowRaider** [comment]
On my computer, they are here:  C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\DesignTools\SystemThemes\Wpf

**Comment by adegeo** [comment]
@ArrowRaider THANKS! I'll change that paragraph to be clearer. I bet those were uploaded somewhere at some point and then lost.
