### ISSUE TITLE
WPF InkCanvas and DynamicRenderer

### ISSUE THREAD

**Issue by carrilloan** [dotnet/docs-desktop#1016]
I have a wpf application in which I use an inkcanvas, I generate a video of the strokes in the inkcanvas, using the RenderTargetBitmap of the InkCanvas as frames. My problem is that when using a touch screen, the stroke of the InkCanvas is not updated until the user lifts the Stylus, and in the RenderTargetBitmap the entire stroke appears from one frame to another. I understand this is due to the DynamicRenderer. Is there a way for the InkCanvas to see the stroke as it is being made?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55334ea6-5b7f-9a3d-48fe-4eed4e81e9f3
* Version Independent ID: 65ef9d14-6883-7b49-e312-80d6049ad120
* Content: [The Ink Threading Model - WPF .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/the-ink-threading-model?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/advanced/the-ink-threading-model.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/advanced/the-ink-threading-model.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello!

Sorry to say, but this article is not the right place to ask that question, just for the fact that not many people will be looking here to help with your question. I think you will have a better chance of getting your question answered if you post it on a forum such as StackOverflow. In short, I have no idea, sorry!

I'm going to close the issue. 

Thanks.
