### ISSUE TITLE
Accessing WPF resources via relative vs fully-qualified URIs 

### ISSUE THREAD

**Issue by IanKemp** [dotnet/docs-desktop#103]
As far as I'm aware, the following are equivalent in WPF:

```cs
Uri uri = new Uri("/PageResourceFile.xaml", UriKind.Relative);
```

and

```cs
Uri uri = new Uri("pack://application:,,,/PageResourceFile.xaml");
```

Is there any reason to prefer one over the other? If not, it would be helpful to update this page to indicate that they are indeed equivalent.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a45ab2e-2d6e-7953-91a3-015ad4a532e5
* Version Independent ID: 93ebea65-7df0-6535-732c-03079780305b
* Content: [Application Resource, Content, and Data Files - WPF .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/app-development/wpf-application-resource-content-and-data-files?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/app-development/wpf-application-resource-content-and-data-files.md](https://github.com/dotnet/docs-desktop/blob/master/dotnet-desktop-guide/framework/wpf/app-development/wpf-application-resource-content-and-data-files.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
@IanKemp Hello! Really one of the links in the article explains more about it; https://docs.microsoft.com/en-us/dotnet/desktop/wpf/app-development/pack-uris-in-wpf?view=netframeworkdesktop-4.8

As with any URI, if you don't use the scheme+authority `scheme://authority/path` then the URI just represents the path of the resource, not where it's hosted. For example, if you used `/PageResourceFile.xaml` with an HTTP web object, it probably infers the final path of `http://whatever-current-authority-you've-been-using.com/PageResourceFile.xaml` which wouldn't go anywhere and probably be an error. The WPF content loader uses:

- Scheme
  `pack://`
- Authority
  `application:,,,` (which is really `application:///` but the `/` needs to be encoded with `,` to be compliant with standards

So the WPF loader can infer it's own scheme+authority (much like an HTTP web object might) on the URI making `/PageResourceFile.xaml` and `pack://application:,,,/PageResourceFile.xaml` resolve to the the same place.
