### ISSUE TITLE
little typo

### ISSUE THREAD

**Issue by UnicornSheep** [dotnet/docs-desktop#1051]
I am highly appreciating your efforts. 
I don't know if this is important but there is extra bracket before the semi colon.    
throw new ArgumentException("IXamlTypeResolver"));

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edfdf993-3c4b-629f-47eb-6251c645c71b
* Version Independent ID: f2dd0495-fe96-a108-afef-8b60cfa90d34
* Content: [Service Contexts Available to Type Converters and Markup Extensions - XAML](https://docs.microsoft.com/en-us/dotnet/desktop/xaml-services/service-contexts-with-type-converters-and-markup-extensions)
* Content Source: [dotnet-desktop-guide/xaml-services/service-contexts-with-type-converters-and-markup-extensions.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/xaml-services/service-contexts-with-type-converters-and-markup-extensions.md)
* Product: **dotnet-desktop**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for opening this issue. I'll add it to the backlog. If you would like to contribute, you can submit a fix by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!
