### ISSUE TITLE
Error on running the app

### ISSUE THREAD

**Issue by Rolews** [dotnet/docs-desktop#1057]
Ik have followed all the steps in the tutorial, but when i run the app i get this  error at line 25 'InitializeComponent();' in .cs file

```
"Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'MainWindow' does not contain a definition for 'ButtonAddName_Click' and no accessible extension method 'ButtonAddName_Click' accepting a first argument of type 'MainWindow' could be found (are you missing a using directive or an assembly reference?)	Names	C:\Users\rolew\source\repos\Names\MainWindow.xaml	26	Active
"
```

Something is missing in the tutorial.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 097f0935-4e55-891d-5a27-fb898d63d8f3
* Version Independent ID: cce4458e-b162-09f3-48ea-b4481aa4c183
* Content: [Create a new app with Visual Studio tutorial - WPF .NET](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/get-started/create-app-visual-studio?view=netdesktop-5.0#feedback)
* Content Source: [dotnet-desktop-guide/net/wpf/get-started/create-app-visual-studio.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/net/wpf/get-started/create-app-visual-studio.md)
* Product: **dotnet-desktop**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello @Rolews I'm sorry that you're having trouble. Did you perhaps miss the step where you right-click on the method name and select **Go To Definition**?

![image](https://user-images.githubusercontent.com/67293991/117074465-35352e80-ace8-11eb-83aa-a49c06d60356.png)

**Comment by adegeo** [comment]
Looks like this must have answered your question. I'll close this issue.
