### ISSUE TITLE
"Visual Basic code above" -- no such thing

### ISSUE THREAD

**Issue by SawNaw** [dotnet/docs-desktop#106]
At the bottom of this page, there is a reference to "the Visual Basic code above" , but there is no VB code on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b01e2f08-f620-3402-46f5-65ffb4e1dba6
* Version Independent ID: 114243e3-25bd-dc0d-1364-e7d573205edc
* Content: [How to: Create Event Handlers at Run Time - Windows Forms .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/how-to-create-event-handlers-at-run-time-for-windows-forms?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/winforms/how-to-create-event-handlers-at-run-time-for-windows-forms.md](https://github.com/dotnet/docs-desktop/blob/master/dotnet-desktop-guide/framework/winforms/how-to-create-event-handlers-at-run-time-for-windows-forms.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hi @SawNaw 

There is a dropdown button at the top of the article to switch the code context to VB. Unfortunately we don't have a way to show/hide paragraphs and sections based on that code. I really think that the sentence could be deleted. Really the intro into that code example says the same thing just without any language specifics. I think that's good enough.

![image](https://user-images.githubusercontent.com/67293991/98407062-db4af900-2023-11eb-9873-52f14e1e03e7.png)
