### ISSUE TITLE
Spelling error on page

### ISSUE THREAD

**Issue by cdmeillon** [dotnet/docs-desktop#1064]
There appears to be a spelling error using **then**  instead of **than** in the second paragraph of the help page: 
"...A TextBox requires less system resources **then** a RichTextBox and it is ideal when only plain text needs..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5806507-7645-b3c5-fb2c-921bd5d9d06c
* Version Independent ID: d6356719-549f-4de5-8c3c-0738b9246f30
* Content: [RichTextBox Overview - WPF .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/controls/richtextbox-overview?view=netframeworkdesktop-4.8&viewFallbackFrom=netdesktop-5.0)
* Content Source: [dotnet-desktop-guide/framework/wpf/controls/richtextbox-overview.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/controls/richtextbox-overview.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for opening this issue. I'll add it to the backlog. If you would like to contribute, you can submit a fix by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!

**Comment by adegeo** [comment]
@cdmeillon Hi! I noticed you tagged this issue in a commit. You'll need to open a pull request from your branch to get that published. Use this link to create the pull request: https://github.com/dotnet/docs-desktop/compare/main...cdmeillon:patch-1 I could open it for you but then it would attribute you in the github history for the article. Thank you for your contribution!
