### ISSUE TITLE
Some words missing, and typos

### ISSUE THREAD

**Issue by ptoye** [dotnet/docs-desktop#1066]
Under 'Resources and Settings' the test says "Windows Forms projects also include Windows Form project specific files, such as Properties/Settings.settings and Properties/Resources.resx. These files may need to be migrated they are declared in your original project."

There are three problems here:

1) The forward slashes should be backward slashes. My search for these in the old projects file failed for obvious reasons.

2) There is a word missing after "migrated" - this is not good grammar and ambiguous. Should it be "if" or "as" or some other word?

3) "such as" is not much help. My fairly small VB project has quite a number of references to "My Project" - which of these need migrating, and which don't?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98778ad1-6c20-6310-e4bc-9d9851a2270a
* Version Independent ID: d1ef1f43-00e2-b46f-4f38-6274a34f07f6
* Content: [Migrate a Windows Forms app to .NET 5 - Windows Forms .NET](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/migration/?view=netdesktop-5.0)
* Content Source: [dotnet-desktop-guide/net/winforms/migration/index.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/net/winforms/migration/index.md)
* Product: **dotnet-desktop**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for opening this issue. I'll get this fixed up.
