### ISSUE TITLE
Scrollviewer Template lacking vital details

### ISSUE THREAD

**Issue by Krythic** [dotnet/docs-desktop#1084]
The suggested template is missing a vital property being set, which is CanContentScroll being true. I have created a Stackoverflow question and answer regarding this, located here: https://stackoverflow.com/questions/67794659/customizing-scrollviewer-style-breaks-richtextbox-mouse-wheel-scrolling

Without that property set, RichTextBoxes lose their vertical mouse scrolling functionality; this is also not noted anywhere as being a problem. The style example doesn't need to be corrected, but a note should certainly be added to the page that tells people about the requirement.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 348ed980-f1c8-9b92-4fca-c6c073b8fbd1
* Version Independent ID: 1f4c955f-034e-4433-6567-95de212c387e
* Content: [ScrollViewer Styles and Templates - WPF .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/controls/scrollviewer-styles-and-templates?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/controls/scrollviewer-styles-and-templates.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/controls/scrollviewer-styles-and-templates.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for opening this issue. I'll get this fixed up. I think it's worth putting in the style. When I generate a style via visual studio's create a copy, it has this property set.

![image](https://user-images.githubusercontent.com/67293991/120515616-5179c900-c383-11eb-9e7a-2c99c6b1e8c2.png)

```xaml
<Style x:Key="ScrollViewerStyle1" TargetType="{x:Type ScrollViewer}">
    <Setter Property="CanContentScroll" Value="True"/>
    <Setter Property="PanningMode" Value="Both"/>
    <Setter Property="Template">
        <Setter.Value>
            <ControlTemplate TargetType="{x:Type ScrollViewer}">
                <Grid>
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition/>
                        <ColumnDefinition Width="Auto"/>
                    </Grid.ColumnDefinitions>
                    <Grid.RowDefinitions>
                        <RowDefinition/>
                        <RowDefinition Height="Auto"/>
                    </Grid.RowDefinitions>
                    <ScrollContentPresenter Grid.Column="0" CanContentScroll="{TemplateBinding CanContentScroll}"/>
                    <ScrollBar x:Name="PART_VerticalScrollBar" Grid.Column="1" Maximum="{TemplateBinding ScrollableHeight}" Grid.Row="0" ViewportSize="{TemplateBinding ViewportHeight}" Value="{TemplateBinding VerticalOffset}" Visibility="{TemplateBinding ComputedVerticalScrollBarVisibility}"/>
                    <ScrollBar x:Name="PART_HorizontalScrollBar" Grid.Column="0" Maximum="{TemplateBinding ScrollableWidth}" Orientation="Horizontal" Grid.Row="1" ViewportSize="{TemplateBinding ViewportWidth}" Value="{TemplateBinding HorizontalOffset}" Visibility="{TemplateBinding ComputedHorizontalScrollBarVisibility}"/>
                    <Rectangle Grid.Column="1" Fill="Red" Grid.Row="1" Visibility="Hidden"/>
                </Grid>
            </ControlTemplate>
        </Setter.Value>
    </Setter>
</Style>
```

**Comment by Krythic** [comment]
Sounds great, thank you!
