### ISSUE TITLE
Unable to Reference Person Class

### ISSUE THREAD

**Issue by markdcarringer** [dotnet/docs-desktop#1088]
My instinct was to create the Person class, then make a reference to it in the XAML. This approach does not work. Visual Studio tells you, incorrectly, that "the name Person does not exist in the namespace clr-namespace:One_SimpleBinding". (I named my project One_SimpleBinding instead of SDKSample, which makes no difference here.) And Visual Studio will not build the project. I am running VS2017 Enterprise version 15.3.0. 

There are two workarounds for this issue: 
1. Reference the Person class in the XAML first, then add Person to the project. 
2. Drop and re-add the Person class. 

It might be helpful to add a note about adding the Person class after referencing it in XAML. Trying to fix this issue is a frustrating use of an hour. I imagine the issue will be fixed at some point, but it seems to have been around for awhile. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0dae4f2-252b-dad2-8355-cac20a09c315
* Version Independent ID: 695ac494-103c-8a6e-b2ea-e66efa7ebfce
* Content: [How to: Create a Simple Binding](https://docs.microsoft.com/en-us/dotnet/framework/wpf/data/how-to-create-a-simple-binding)
* Content Source: [docs/framework/wpf/data/how-to-create-a-simple-binding.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/data/how-to-create-a-simple-binding.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by adegeo** [comment]
@natejgardner I'll get something done for this!

**Comment by markdcarringer** [comment]
Hey guys
Thanks for resurrecting this issue. I'm no longer doing WPF in my job, and have forgotten some of it. 
However, I just tried the example in Visual Studio 2019, creating a WPF project in .NET Framework. It seems to work okay for me, but I did have to make two changes after simply copying and pasting the example into my Window.xaml file. 
1. Changed the value of the xmlns:src prefix to match the name of the namespace in which my Person class was located. 
2. Added the following attribute to the Window class, so it could call InitializeComponent: 
    x:Class="WpfApp2.MainWindow"

That second point is really the key, I think. The learner might reasonably be expected to figure out the namespaces have to match, though it wouldn't hurt to tell them so. 
And of course, you have to create a Person class with a PersonName property of type string, and make sure it has a no-arg constructor. 
Again, I think adding an x:Class prefix to the example will clear up most of the trouble. 
Let me know if you want me to proof the new version when it's ready. 
Thanks for your efforts!
Mark Carringer    On Wednesday, June 9, 2021, 01:21:37 PM CDT, Andy (Steve) De George ***@***.***> wrote:  
 
 


@natejgardner I'll get something done for this!

**Comment by adegeo** [comment]
Thanks for replying even though you're not involved in this :) I think part of the problem is just how atomic the sample is trying to be, but it's hard for that to work with traditional WPF
