### ISSUE TITLE
WindowsFormsHost doesn't work in WPF .Net 5 application

### ISSUE THREAD

**Issue by AhmadKelany** [dotnet/docs-desktop#1092]
[Enter feedback here]
![image](https://user-images.githubusercontent.com/12924528/121728627-34b56200-caf6-11eb-800e-3b7cebf3fce3.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f1bac29-3647-35e0-29a1-e0d2efda12cd
* Version Independent ID: 4ed95343-2c73-e55e-9591-968489810601
* Content: [Host a Windows Forms control in WPF using XAML](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/walkthrough-hosting-a-windows-forms-control-in-wpf-by-using-xaml?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/advanced/walkthrough-hosting-a-windows-forms-control-in-wpf-by-using-xaml.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/advanced/walkthrough-hosting-a-windows-forms-control-in-wpf-by-using-xaml.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
If you're using .NET 5, you'll need to import winforms by adding `<UseWindowsForms>true</UseWindowsForms>` to your project file.

**Comment by AhmadKelany** [comment]
> If you're using .NET 5, you'll need to import winforms by adding `<UseWindowsForms>true</UseWindowsForms>` to your project file. Let me know if that doesn't fix your problem :)

That fixed the problem, thanks 😊
