### ISSUE TITLE
3D Objects not listed

### ISSUE THREAD

**Issue by AzureAzim** [dotnet/docs-desktop#1095]
3D Objects is not listed in this list of known folders. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b24bd33-34dd-1d33-1846-e90f71d60bff
* Version Independent ID: 277656f7-f07d-aa6c-7365-d44f0a18270f
* Content: [Known Folder GUIDs for File Dialog Custom Places - Windows Forms .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/controls/known-folder-guids-for-file-dialog-custom-places?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/winforms/controls/known-folder-guids-for-file-dialog-custom-places.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/winforms/controls/known-folder-guids-for-file-dialog-custom-places.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
@AzureAzim Do you know the GUID? You can edit the doc and add it. There is an edit icon on the top-right of the page. The reason it's missing is that this was written long before Windows 10.
