### ISSUE TITLE
Please update this information for .Net core through .Net 5+

### ISSUE THREAD

**Issue by davi1td** [dotnet/docs-desktop#1102]
Hi, this really needs to be updated ASAP with the notes from this winforms issue:
https://github.com/dotnet/winforms/discussions/4894

attach to the "DesignToolsServer.exe" process from the instance of Visual Studio that is doing the debugging.
Regards,
-TD

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cf24e8a-af35-53f6-093d-5392128ad3fb
* Version Independent ID: f493ff27-e2e1-ad7e-38d4-46ded0c45022
* Content: [Debug Custom Controls at Design Time - Windows Forms .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/controls/walkthrough-debugging-custom-windows-forms-controls-at-design-time?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/winforms/controls/walkthrough-debugging-custom-windows-forms-controls-at-design-time.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/winforms/controls/walkthrough-debugging-custom-windows-forms-controls-at-design-time.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello @davi1td we're porting all that content to a different area, slowly though. I'll add a quick note in there though so that anyone else running into this can get a solution. Thank you for the suggestion!
