### ISSUE TITLE
Data binding overview - example is not present

### ISSUE THREAD

**Issue by whitehorsesoft** [dotnet/docs-desktop#1107]
**Issue description**

In data binding overview page (at https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/net/wpf/data/index.md), in Data validation section, under "Associating validation rules with a binding," it states

> A DataErrorValidationRule object checks for errors that are raised by objects that implement the IDataErrorInfo interface. For an example of using this validation rule, see DataErrorValidationRule.

However, an example is not present at DataErrorValidationRule documentation. It would be better to state "more information is found at..." instead of "For an example..."

**.NET or .NET Framework**

Check the .NET target framework(s) being used, and include the version number(s). Put an `x` between the `[ ]` to check it.

- [x] .NET (5 or Core)
- [x] .NET Framework

**Technology**

Check the .NET target framework(s) being used, and include the version number(s). Put an `x` between the `[ ]` to check it.

- [x] WPF
- [ ] Windows Forms

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adcf9793-10cf-bdeb-3810-9be075db969f
* Version Independent ID: 8cfffaa6-fa5c-a50b-0110-1750713bd153
* Content: [Data binding overview - WPF .NET](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/data/?view=netdesktop-5.0)
* Content Source: [dotnet-desktop-guide/net/wpf/data/index.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/net/wpf/data/index.md)
* Product: **dotnet-desktop**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for opening this issue. I'll add it to the backlog. If you would like to contribute, you can submit a fix by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!

**Comment by whitehorsesoft** [comment]
Created & linked pull request. Let me know if anything else is needed or if unclear. Thanks.
