### ISSUE TITLE
The code doesn't work in the Enter event of the textbox.

### ISSUE THREAD

**Issue by digitaldragonfire** [dotnet/docs-desktop#1118]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7943d1c-c61b-b782-13c6-521c4e72b9ab
* Version Independent ID: 5f09ab60-ae93-f783-a4bf-133b3b985f7f
* Content: [Select Text in TextBox Control - Windows Forms .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/controls/how-to-select-text-in-the-windows-forms-textbox-control?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/winforms/controls/how-to-select-text-in-the-windows-forms-textbox-control.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/winforms/controls/how-to-select-text-in-the-windows-forms-textbox-control.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello @digitaldragonfire I just tested this and it's working for me. Can you provide more information?

1. Did you attach the ENTER event for the textbox?
2. Did you add text to the textbox?
3. Did you focus the textbox using the TAB key?

**Comment by digitaldragonfire** [comment]
Yes, the event is attached, and there is text there.

 

I suppose I should qualify it a bit more.

It does work entering the textbox using the tab key. It doesn’t work entering the textbox using a click event.

This, however, works in both cases:

 

txtTextbox.BeginInvoke(New Action(AddressOf txtTextbox.SelectAll))

 

My understanding is that this is due to the events processed by the click event (positioning the caret) which take place after the enter event is fired. The above snippet works by putting itself in the processing queue after those events.

 

Ken Russell

 

 ***@***.***> ***@***.***

**Comment by digitaldragonfire** [comment]
Yes, the event is attached, and there is text there.

I suppose I should qualify it a bit more.
It does work entering the textbox using the tab key. It doesn’t work entering the textbox using a click event.
This, however, works in both cases:

txtTextbox.BeginInvoke(New Action(AddressOf txtTextbox.SelectAll))

My understanding is that this is due to the events processed by the click event (positioning the caret) which take place after the enter event is fired. The above snippet works by putting itself in the processing queue after those events.

I suppose I feel that the example code isn't the greatest example because it doesn't work in both cases.

**Comment by adegeo** [comment]
> This, however, works in both cases:
> 
> txtTextbox.BeginInvoke(New Action(AddressOf txtTextbox.SelectAll))

That's a great way of doing it!

> I suppose I feel that the example code isn't the greatest example because it doesn't work in both cases.

Indeed. However, this is probably an extremely low priority code changes. We would also need the change in C++/C# since those code examples are in the article.

Would you feel up to doing those changes? Otherwise we can close this issue since the existing code does work even though it isn't the best.
