### ISSUE TITLE
The `Settings.settings` include should be update

### ISSUE THREAD

**Issue by Romanx** [dotnet/docs-desktop#1124]
```xml
<ItemGroup>
  <None Include="Properties\Settings.settings">
    <Generator>SettingsSingleFileGenerator</Generator>
    <LastGenOutput>Settings.Designer.cs</LastGenOutput>
  </None>
  <Compile Update="Properties\Settings.Designer.cs">
    <AutoGen>True</AutoGen>
    <DependentUpon>Settings.settings</DependentUpon>
    <DesignTimeSharedInput>True</DesignTimeSharedInput>
  </Compile>
</ItemGroup>
```
This section seems to be incorrect since it seems that settings files are added automatically so the generator property is never set and so the quoted section below is incorrect.
> Notice that the Properties\Settings.settings entry remained Include. The project doesn't automatically include settings files.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98778ad1-6c20-6310-e4bc-9d9851a2270a
* Version Independent ID: d1ef1f43-00e2-b46f-4f38-6274a34f07f6
* Content: [Migrate a Windows Forms app to .NET 5 - Windows Forms .NET](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/migration/?view=netdesktop-5.0)
* Content Source: [dotnet-desktop-guide/net/winforms/migration/index.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/net/winforms/migration/index.md)
* Product: **dotnet-desktop**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for pointing this out. I did some tests and this is what the Visual Studio Designer puts in the project when you add a settings file to the project. I'll open a bug with Visual Studio to figure out why they're generating the entry in the project when it should be automatic. I'll get back to you.

**Comment by adegeo** [comment]
@Romanx It looks like these are needed so that the IDE associates the two files into a collapsible entry in the Project Explorer. When you add a new settings file to the project via **Add new item** in Visual Studio, it creates these entries. I think the note needs to be amended.
