### ISSUE TITLE
Ambigous behavior in the final snippet of a WPF getting started article

### ISSUE THREAD

**Issue by Zotyamester** [dotnet/docs-desktop#1126]
I believe the final code snippet of the **[Tutorial: Create a new WPF app (WPF .NET)](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/get-started/create-app-visual-studio?view=netdesktop-5.0)** article has a bit misleading behavior.
The user would expect the TextBox to be cleared after clicking on the button.

It's really a minor thing, but I thought why not add this little 'feature', especially if the reader can learn one more function of WPF by this change.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 097f0935-4e55-891d-5a27-fb898d63d8f3
* Version Independent ID: cce4458e-b162-09f3-48ea-b4481aa4c183
* Content: [Create a new app with Visual Studio tutorial - WPF .NET](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/get-started/create-app-visual-studio?view=netdesktop-5.0)
* Content Source: [dotnet-desktop-guide/net/wpf/get-started/create-app-visual-studio.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/net/wpf/get-started/create-app-visual-studio.md)
* Product: **dotnet-desktop**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for opening this issue. I'll add it to the backlog.

Thanks again!
