### ISSUE TITLE
ProgressBarIndicatorAnimatedFill Binding Issue

### ISSUE THREAD

**Issue by bfurlani** [dotnet/docs-desktop#1134]
the line   Fill="{StaticResource ProgressBarIndicatorAnimatedFill}" in the code should be   Fill="{DynamicResource ProgressBarIndicatorAnimatedFill}" otherwise when you run the application and the Load event happens for the control it throws a Markup exception. Small fix but for someone who might not understand XAML it may be a lot of bug hunting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c641dc28-4b41-5772-e656-69b569553270
* Version Independent ID: f6de3d92-816d-7033-1eb1-e697bfa5eeda
* Content: [ProgressBar Styles and Templates - WPF .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/controls/progressbar-styles-and-templates?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/controls/progressbar-styles-and-templates.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/controls/progressbar-styles-and-templates.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for reporting this. I'll take a look and get it fixed!
