### ISSUE TITLE
Opacity/OpacityMask typo?

### ISSUE THREAD

**Issue by magla42** [dotnet/docs-desktop#1137]
In the section "Creating an Opacity Mask" the last sentence is:

`..using a SolidColorBrush is equivalent to setting the element's or visual's OpacityMask property.`

I would think that should be `Opacity property`, not `OpacityMask property`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46990e22-d704-d41d-8603-58acc6622984
* Version Independent ID: 863cdb85-3907-705e-d24d-2f8d9f37828f
* Content: [Opacity Masks Overview - WPF .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/graphics-multimedia/opacity-masks-overview?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/graphics-multimedia/opacity-masks-overview.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/graphics-multimedia/opacity-masks-overview.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Great catch! I'll fix that!
