### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by auggie123** [dotnet/docs-desktop#1140]
this does not work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 232e99bb-0a3c-1cc7-f0c0-74ac2db24b31
* Version Independent ID: 725cb253-4c49-1b04-02a3-ce2e9f0a73fe
* Content: [How to: Put Quotation Marks in a String - Windows Forms .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/controls/how-to-put-quotation-marks-in-a-string-windows-forms?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/winforms/controls/how-to-put-quotation-marks-in-a-string-windows-forms.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/winforms/controls/how-to-put-quotation-marks-in-a-string-windows-forms.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello @auggie123 

You'll have to be more specific about what doesn't work. Everything looks good there. What language are you using? How are you using this code?
