### ISSUE TITLE
Some misstypings at this page

### ISSUE THREAD

**Issue by Filipizaum** [dotnet/docs-desktop#1143]
> The following image shows a Label "Themes" that targets a ComboBox.

But the attached image shows "Theme" instead of "Themes".

> When the user presses , the ComboBox receives focus.

I think there is some keybinding missing at this prhrase.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26302480-4713-8232-22b1-8adc5ace0d42
* Version Independent ID: 19661d47-20ab-2fc2-692b-d76ff2462f38
* Content: [Label - WPF .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/controls/label?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/controls/label.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/controls/label.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for opening this issue. I'll get it fixed. If you would like to contribute, you can submit a fix by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!
