### ISSUE TITLE
This tells me nothing.

### ISSUE THREAD

**Issue by aybiss** [dotnet/docs-desktop#116]
What does this code accomplish that would not be accomplished without ObservableCollection?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 414099c5-9251-e3b0-b693-74febd5f4c01
* Version Independent ID: d7e4a1ef-bfce-4593-069b-84c27ba96769
* Content: [How to: Create and Bind to an ObservableCollection - WPF .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/data/how-to-create-and-bind-to-an-observablecollection?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/data/how-to-create-and-bind-to-an-observablecollection.md](https://github.com/dotnet/docs-desktop/blob/master/dotnet-desktop-guide/framework/wpf/data/how-to-create-and-bind-to-an-observablecollection.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
@aybiss I can only guess but I think the original author was wrapping the ObservableCollection so that it was easy to create as a XAML resources for the purpose of demonstrating the binding.

**Comment by MV10** [comment]
@aybiss isn't wrong ... subclassing `ObservableCollection` doesn't do anything useful. You could just create and bind a property and accomplish the same thing. I've seen this page linked as an example of how to get property change notifications from the _contents_ of the collection (changing `PersonName` properties, using the example) and that isn't true and doesn't work.

The page and content are pointless.

**Comment by adegeo** [comment]
> The page and content are pointless.

I agree. I can only guess as to why they did it the way they did it. As I port content to .NET 6/7/8 these types of articles are to be rolled into bigger conceptual articles. This one, for example, I would see as a section in a generic `Bind to collections` type of article, and it would just use `ObservableCollection` directly...
