### ISSUE TITLE
"You can set the Width and Height manually."

### ISSUE THREAD

**Issue by riobertd903** [dotnet/docs-desktop#1162]
Really??  What version of Visual Studio permits this?  VS2019 will promptly change the settings back to their original values.  So, that's partially true.  True--you can manually change the values, however, VS2019 will change them back.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91b8db81-dce3-2dee-b3de-1c1c8f7dc01f
* Version Independent ID: dcfa1126-50e8-a5d6-6b9b-8ec72f3634f1
* Content: [Position and resize a form - Windows Forms .NET](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/forms/how-to-position-and-resize?view=netdesktop-5.0)
* Content Source: [dotnet-desktop-guide/net/winforms/forms/how-to-position-and-resize.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/net/winforms/forms/how-to-position-and-resize.md)
* Product: **dotnet-desktop**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello @riobertd903 It's always been manually settable. Testing this again it's working fine for me. I tried in VS2019 and VS2022. Perhaps you have some other code that is running that is overriding it, like an event handler or something? If you can't get this solved, use the menu **Help** > **Feedback** > **Report a problem...**

![temp](https://user-images.githubusercontent.com/67293991/134946230-b5650d88-d9d8-495c-9edd-58be20b60d23.gif)
