### ISSUE TITLE
Typo in the doc

### ISSUE THREAD

**Issue by MihailsKuzmins** [dotnet/docs-desktop#1165]
There is a typo in a comment
"Inititate" -> "Initiate"
https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/walkthrough-enabling-drag-and-drop-on-a-user-control?view=netframeworkdesktop-4.8
![image](https://user-images.githubusercontent.com/47413092/135399552-ea94ce33-1830-4ce5-8e70-2e27d457ce4f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23f605d0-6326-17d5-3087-4f6ef96ab9bb
* Version Independent ID: 10411c7d-3586-4904-6d4f-79e84f0c9b98
* Content: [Walkthrough: Enabling Drag and Drop on a User Control - WPF .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/walkthrough-enabling-drag-and-drop-on-a-user-control?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/advanced/walkthrough-enabling-drag-and-drop-on-a-user-control.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/advanced/walkthrough-enabling-drag-and-drop-on-a-user-control.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for reporting this. I'll get it fixed.
