### ISSUE TITLE
Error in Example Requirements

### ISSUE THREAD

**Issue by MarvusMedia** [dotnet/docs-desktop#1168]
"This example requires: ... An image file that is named TestPhoto.jpg and located at `c:\`."
I think location should be `c:\test\` in accordance with the code. Thanks.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b34c0362-b66b-d065-5d15-87c5dfa810be
* Version Independent ID: b0ca8d84-edb4-0adf-f289-54945dd6ef62
* Content: [How to: Set JPEG Compression Level - Windows Forms .NET Framework](https://docs.microsoft.com/en-gb/dotnet/desktop/winforms/advanced/how-to-set-jpeg-compression-level?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/winforms/advanced/how-to-set-jpeg-compression-level.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/winforms/advanced/how-to-set-jpeg-compression-level.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello. Are you saying that the description text isn't what is demonstrated in the code? Or are you just suggesting that nothing is broken in the article, but instead of `c:\` the article should be updated to use `c:\test`?

**Comment by MarvusMedia** [comment]
Hi. The example code contains the line:

`Using bmp1 As New Bitmap("C:\test\TestPhoto.jpg")`

but under 'This example requires:' it says:

`An image file that is named TestPhoto.jpg and located at c:\.`

(I used the code format for that last line, even though it's text, because otherwise the backslash doesn't show.)

**Comment by adegeo** [comment]
Ahhh in the VB.NET code! I'll fix that. Thank you for reporting it.

**Comment by MarvusMedia** [comment]
You're welcome.
