### ISSUE TITLE
Wrong content?

### ISSUE THREAD

**Issue by carlospenedorocha** [dotnet/docs-desktop#1174]
The page says: "When declaring a `ShouldSerialize` or `Reset` method, use the `private` access modifier."

But the `ShouldSerialize` method is only being called if the access modifier is `public`. It doesn't work with `private`, at least not with the example below:
```
    public class C
    {
        [XmlAttribute("myProp")]
        public int MyProp{ get; set; }

        private bool ShouldSerializeMyProp()
        {
             // never reaches here if access modifier is private, but works with public
        }
   }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e32682fb-671a-8f6e-045c-e92a96ca029e
* Version Independent ID: 42210b30-f3ee-9975-b3f2-8752f9aca815
* Content: [Defining Default Values with the ShouldSerialize and Reset Methods - Windows Forms .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/controls/defining-default-values-with-the-shouldserialize-and-reset-methods?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/winforms/controls/defining-default-values-with-the-shouldserialize-and-reset-methods.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/winforms/controls/defining-default-values-with-the-shouldserialize-and-reset-methods.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Sorry for the delay in response, this got lost in my inbox. Did you ever get this figured out? Please attach the project and source code for me to take a look at as I was unable to replicate your problem.
