### ISSUE TITLE
Attached property is not settable on any object 

### ISSUE THREAD

**Issue by KWodarczyk** [dotnet/docs-desktop#1195]
The first paragraph states "An attached property is a concept defined by XAML. An attached property is intended to be used as a type of global property that is settable on any object." That is not true, for example you cannot set it o **DataTemplate**  becasue it's not a DependencyObject right ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f6a20c9-f639-43ae-04f1-7bf25d45ab77
* Version Independent ID: d96932c9-0a8b-aefe-8a0a-ce6a6a8a32b6
* Content: [Attached Properties Overview - WPF .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/attached-properties-overview?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/advanced/attached-properties-overview.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/advanced/attached-properties-overview.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for reporting this. It seems this go lost in the shuffle. I'll correct it. Thanks again.
