### ISSUE TITLE
Inconsistent requirements for collection properties

### ISSUE THREAD

**Issue by magla42** [dotnet/docs-desktop#1200]
In the section **Writing Collection Properties** one possibility for a WPF collection type is listed as:

- Implements` IDictionary` or the generic equivalent (`IDictionary<TKey,TValue>`).

But that the generic interface can be used is directly contradicted by the Note a few lines further down. Is possibly `Dictionary<TKey, TValue>` meant? But then you should probably mention `List<TValue>` as an alternative to `IList` also. I would think it is most clear to just skip mentioning `IDictionary<TKey,TValue>` here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b30c2691-5877-ea11-d359-532fb96fdecb
* Version Independent ID: 87c6e97d-b3c0-a960-69b1-0a48f2f12134
* Content: [XAML and custom classes - WPF .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/xaml-and-custom-classes-for-wpf?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/advanced/xaml-and-custom-classes-for-wpf.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/advanced/xaml-and-custom-classes-for-wpf.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Sorry for the delay in getting back to you. Thank you for pointing this out. I'll fix it up. I think you're right, removing reference to the generic interface makes the most sense.
