### ISSUE TITLE
Redundant text

### ISSUE THREAD

**Issue by magla42** [dotnet/docs-desktop#1201]
The first two paragraphs are verbatim identical, with the only exception the link at the end.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9024fd6b-79b6-4b3e-17f7-b7257fe39139
* Version Independent ID: dbdfb5d0-7d61-b4e1-3e91-42f785445c64
* Content: [XAML Syntax In Detail - WPF .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/xaml-syntax-in-detail?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/advanced/xaml-syntax-in-detail.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/advanced/xaml-syntax-in-detail.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
HA! Thank you for pointing this out. I also need to do a bunch of link updates too.
