### ISSUE TITLE
Inconsistence between XMAL and code-behind in Window example

### ISSUE THREAD

**Issue by yqrickw20** [dotnet/docs-desktop#1209]
Hi! Thanks for write this page (https://docs.microsoft.com/en-us/dotnet/desktop/wpf/windows/?view=netdesktop-5.0). It's very helpful for beginners like me. However, I found that there may be a typo in the second example of **Implementing a Window** section in this page.

In the XAML, the **x:Class** attribute is **"WindowsOverview.Final"**. In the code-behind, the name of partial class is **Window1**.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c50c7729-f1ce-2f8e-cd77-186a94846c64
* Version Independent ID: 02653ec8-ce70-979e-c96c-5949fa5befd6
* Content: [Windows in WPF overview - WPF .NET](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/windows/?view=netdesktop-5.0)
* Content Source: [dotnet-desktop-guide/net/wpf/windows/index.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/net/wpf/windows/index.md)
* Product: **dotnet-desktop**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for opening this issue. I'll get this fixed up.
