### ISSUE TITLE
Typo in the page

### ISSUE THREAD

**Issue by yqrickw20** [dotnet/docs-desktop#1211]
At the start of this page

Dialog boxes are used to:

-Display specific information to users.
-Gather information from users.
-Both display and gather information.
-Display an operating system prompt, such a print window. **(I think it should be "such as a print window" if understand correctly)**
-Select a file or folder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3ef818a-aabf-2b9d-378a-f1cb792b6e1c
* Version Independent ID: f967e9a9-6db6-dfca-1a53-00d00592762b
* Content: [Dialog Boxes Overview - WPF .NET](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/windows/dialog-boxes-overview?view=netdesktop-5.0)
* Content Source: [dotnet-desktop-guide/net/wpf/windows/dialog-boxes-overview.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/net/wpf/windows/dialog-boxes-overview.md)
* Product: **dotnet-desktop**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for opening this issue. I'll add it to the backlog. If you would like to contribute, you can submit a fix by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!
