### ISSUE TITLE
Windows 10 or 11?

### ISSUE THREAD

**Issue by yowl** [dotnet/docs-desktop#1225]
[Enter feedback here]
This doesn't say much about Microsoft's commitment to WPF.  Why does the table not go to WIndows 10 or 11?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60c5ae30-77fe-da6e-a320-17a4e734f0cd
* Version Independent ID: ba7cff33-a2c3-ae78-c1c6-ad0839c03ad4
* Content: [Control Styles and Templates - WPF .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/controls/control-styles-and-templates?view=netframeworkdesktop-4.8&viewFallbackFrom=netdesktop-6.0)
* Content Source: [dotnet-desktop-guide/framework/wpf/controls/control-styles-and-templates.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/controls/control-styles-and-templates.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for the feedback.

The themes haven't been updated in quite some time. WPF uses its own theme system that doesn't automatically use the Windows theme. So a full WPF theme must be written for WPF to be styled like Windows 11/10. You can vote and voice your comment in the WPF repo: https://github.com/dotnet/wpf/issues/4749
