### ISSUE TITLE
Example SplitContainer code contains errors

### ISSUE THREAD

**Issue by sminhinnick** [dotnet/docs-desktop#1228]
Hi,

In the page's code example I think **splitContainer2** should be **splitContainer1**, in the following code:

    // Set properties of first SplitContainer control.  
    splitContainer1.Dock = System.Windows.Forms.DockStyle.Fill;  
    splitContainer2.TabIndex = 1;  
    splitContainer2.SplitterWidth = 4;  
    splitContainer2.SplitterDistance = 150;  
    splitContainer2.Orientation = Orientation.Horizontal;  
    splitContainer2.Panel1.Controls.Add(this.listView1);  
    splitContainer2.Panel1.Controls.Add(this.richTextBox1);  

Please make the correction, thanks.

Regards,
Stephen Minhinnick
Auckland, New Zealand

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea1c4b9e-194b-dfbb-84e6-be22048f0bdf
* Version Independent ID: 8686a411-89b8-e249-d93c-e4d79b05de51
* Content: [Create a Multipane User Interface - Windows Forms .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/controls/how-to-create-a-multipane-user-interface-with-windows-forms?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/winforms/controls/how-to-create-a-multipane-user-interface-with-windows-forms.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/winforms/controls/how-to-create-a-multipane-user-interface-with-windows-forms.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for opening this issue. I'll get this fixed up.

**Comment by adegeo** [comment]
Hello @sminhinnick when looking at this I also spotted some other errors. I've transformed the article away from the old style of "creating a form from scratch and building controls via code" and now I'm just describing what settings you need per control to generate the UI.

![image](https://user-images.githubusercontent.com/67293991/150588704-7984dc56-b2e6-4db2-9e16-c948103198b5.png)


I've also added a screenshot that shows what the UI looks like:

![image](https://user-images.githubusercontent.com/67293991/150588648-c1ee6bba-e952-4117-b063-534ed9488fb4.png)
