### ISSUE TITLE
Unused variable

### ISSUE THREAD

**Issue by gggustafson** [dotnet/docs-desktop#1239]
In the CaptureScreen method, a variable named memoryGraphics is declared and initialized. Why?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 897fff16-d70f-5e07-0d49-a718e35df446
* Version Independent ID: 08014790-627a-e56f-9eea-309f4d70c016
* Content: [How to: Print a Windows Form - Windows Forms .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/advanced/how-to-print-a-windows-form?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/winforms/advanced/how-to-print-a-windows-form.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/winforms/advanced/how-to-print-a-windows-form.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello @gggustafson.

This example prints a bitmap (the `memoryImage` variable). When drawing on a bitmap, you can't draw directly to it and must use a `Graphics` object to wrap the target bitmap. All drawing is done through the `Graphics` object. In this case the `memoryGraphics` variable is that wrapper for `memoryImage`. This wrapper is used to copy the forms graphics to the bitmap and then the bitmap is printed.
