### ISSUE TITLE
Missing style: MenuScrollButton Not Defined

### ISSUE THREAD

**Issue by YounesCheikh** [dotnet/docs-desktop#124]
[Enter feedback here]

The Style MenuScrollButton is mssing, the app crashes
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a19972d-68c2-fdcb-9ee2-34b9be6577be
* Version Independent ID: 39ab460f-20e6-9997-2f83-1fed12e4347d
* Content: [Menu Styles and Templates - WPF .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/controls/menu-styles-and-templates?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/controls/menu-styles-and-templates.md](https://github.com/dotnet/docs-desktop/blob/master/dotnet-desktop-guide/framework/wpf/controls/menu-styles-and-templates.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thanks, we'll look into it!

**Comment by YounesCheikh** [comment]
@adegeo .NET5

**Comment by SRichardsonDTech** [comment]
The static resources 'UpArrow' and 'DownArrow' are also missing from the sample code. I'm running .NET Framework.

**Comment by adegeo** [comment]
@SRichardsonDTech Do you get them when you use the **Document Outline** pane to right-click edit template > edit a copy ?
![image](https://user-images.githubusercontent.com/67293991/127710962-0fb0fa32-70fa-46f5-a959-87dff8fb62c9.png)

**Comment by adegeo** [comment]
I can't really find the reference material that was used to generate these. Unfortunately it's not in our current scope to regenerate these for .NET 4. Your best bet is to generate your own copies using the method I detailed above. Sorry about that.

**Comment by KyleC69** [comment]
This problem still exists in .Net 6 documentation. Sample code is missing style definition. 
This is a very detailed sample, would like to see it fixed. or possibly an alternate Menu control sample.
