### ISSUE TITLE
ListView

### ISSUE THREAD

**Issue by EsterShmuel** [dotnet/docs-desktop#1250]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fd9f4bd-6e11-4cde-00e1-69435af8b873
* Version Independent ID: 3a274a3d-00f7-a0bc-0e67-ce97823be755
* Content: [ListView Overview - WPF .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/controls/listview-overview?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/controls/listview-overview.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/controls/listview-overview.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello, it doesn't seem like you provided any details with your issue. Could you provide those details?
