### ISSUE TITLE
Would be nice if the example code had pictures of what the UI would look like with the example that was given.

### ISSUE THREAD

**Issue by PatrickMcDougle** [dotnet/docs-desktop#1252]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c641dc28-4b41-5772-e656-69b569553270
* Version Independent ID: f6de3d92-816d-7033-1eb1-e697bfa5eeda
* Content: [ProgressBar Styles and Templates - WPF .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/controls/progressbar-styles-and-templates?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/controls/progressbar-styles-and-templates.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/controls/progressbar-styles-and-templates.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for the suggestion. That would be a nice addition but it's not in our current scope for this content. I'll close this issue for now. Thanks again.
