### ISSUE TITLE
Is the text wrong in the nuget section?

### ISSUE THREAD

**Issue by kennethhovsnow** [dotnet/docs-desktop#126]
[Enter feedback here]
I'm trying to migrate a winform project to .net 5. In the section about nuget packages, it says: Right-click on packages.config > Migrate packages.config to ProjectReference. Should this be: Right-click on packages.config > Migrate packages.config to PackageReference? This is the only option I get when right clicking the package.config.

Br
Kenneth Hov

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98778ad1-6c20-6310-e4bc-9d9851a2270a
* Version Independent ID: d1ef1f43-00e2-b46f-4f38-6274a34f07f6
* Content: [Migrate a Windows Forms app to .NET 5 - Windows Forms .NET](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/migration/?view=netdesktop-5.0)
* Content Source: [dotnet-desktop-guide/net/winforms/migration/index.md](https://github.com/dotnet/docs-desktop/blob/master/dotnet-desktop-guide/net/winforms/migration/index.md)
* Product: **dotnet-desktop**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Ack yes, you're right. I'll get this fixed.
