### ISSUE TITLE
Content of the page "Host a Windows Forms control in WPF using XAML" is outdated

### ISSUE THREAD

**Issue by loicmorvan-ansys** [dotnet/docs-desktop#1272]
When switching to this page for .Net Desktop 5.0 or 6.0, we redirected to the .Net Framework 4 version which is outdated.
In particular this page says to add references to WindowsFormsIntegration and System.Windows.Forms, which seems not to be possible in dotnet 5.0 or 6.0.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f1bac29-3647-35e0-29a1-e0d2efda12cd
* Version Independent ID: 4ed95343-2c73-e55e-9591-968489810601
* Content: [Host a Windows Forms control in WPF using XAML](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/walkthrough-hosting-a-windows-forms-control-in-wpf-by-using-xaml?view=netframeworkdesktop-4.8&viewFallbackFrom=netdesktop-5.0)
* Content Source: [dotnet-desktop-guide/framework/wpf/advanced/walkthrough-hosting-a-windows-forms-control-in-wpf-by-using-xaml.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/advanced/walkthrough-hosting-a-windows-forms-control-in-wpf-by-using-xaml.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
@loicmorvan-ansys Hello! We haven't migrated this content yet. If I remember correctly, to get this enabled, simply add the `<UseWindowsForms>true</UseWindowsForms>` property to your project file along with the existing `<UseWPF>` property.

**Comment by loicmorvan-ansys** [comment]
Indeed this works. Thanks!
