### ISSUE TITLE
Undefined variables in code-behind example code

### ISSUE THREAD

**Issue by DaveGWork** [dotnet/docs-desktop#1278]
1. Variables tp1 to tp5 are undefined in C# code-behind example.
2. It would be useful if a parent root element were added to the XAML (e.g. a stackpanel).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ba782ab-3b9c-a51d-e692-48d3a8c8015f
* Version Independent ID: 2a5526da-ac87-c4f7-bbbb-2b2ee07db004
* Content: [How to: Manipulate Columns and Rows by Using ColumnDefinitionsCollections and RowDefinitionsCollections - WPF .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/controls/manipulate-columns-and-rows-by-using-columndefinitionscollections?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/controls/manipulate-columns-and-rows-by-using-columndefinitionscollections.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/controls/manipulate-columns-and-rows-by-using-columndefinitionscollections.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
@DaveGWork It's silly that the example is so big but omits those tiny pieces. I'll fix this up, but for reference here is the full XAML: https://github.com/dotnet/docs-desktop/blob/da363692ff6d30641003148c90cd8d0e7fa5ddf6/dotnet-desktop-guide/samples/snippets/csharp/VS_Snippets_Wpf/ColumnDefinitionsGrid/CSharp/Window1.xaml#1
