### ISSUE TITLE
IOException: Cannot locate resource 'watermark.png'.

### ISSUE THREAD

**Issue by myNameIsKeith** [dotnet/docs-desktop#1290]
[Enter feedback here]
The walk-through works up until the watermark.png is added. The watermark shows up in the source file "ExpenseItHome.xaml" but when launching the app, an exception is thrown.

This looks to be a path issue rather than an error in the code. I'm a complete beginner to WPF and don't yet know how to modify the paths for the app to pick up the file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3d7ba9b-4bc3-105a-bed6-fed320821bb5
* Version Independent ID: cc43c332-3eb2-9473-b88a-128c6390cfec
* Content: [Create your first WPF app in Visual Studio 2019 - .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/getting-started/walkthrough-my-first-wpf-desktop-application?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/getting-started/walkthrough-my-first-wpf-desktop-application.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/getting-started/walkthrough-my-first-wpf-desktop-application.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
@myNameIsKeith Hi there. Sorry for the delay in answering your question. Are you still having this problem? In [step 12 of Add files to the application](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/getting-started/walkthrough-my-first-wpf-desktop-application?view=netframeworkdesktop-4.8#add-files-to-the-application), it says to add this file to your project. 

I believe you also then need to set the **Build Action** of the file to **Resource**. This is done by selecting the file in the **Project explorer** pane, then changing the value in the **Properties** pane:
![image](https://user-images.githubusercontent.com/67293991/151839241-ddbb9dc3-4817-4e01-bb56-e093ad2d418b.png)

Let me know if this fixes your issue and I'll update the documentation.
