### ISSUE TITLE
Translucency is missing from icons

### ISSUE THREAD

**Issue by AesirHod** [dotnet/docs-desktop#1293]
The icons loaded using this method don’t appear to have any of their translucency included despite doing so in File Explorer, OpenFileDialog, and on the desktop.

I try to use them on a ListView or a ListBox and they all have a black background, making them unsuitable for the file browser I’m trying to make.

If there’s a solution for this, it would be really appreciated to include in this example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c42dcdf-eeef-520b-87a9-03c2e0f2764f
* Version Independent ID: ef36402a-d1cf-5995-0f1a-d571725bfd3e
* Content: [How to: Extract the Icon Associated with a File - Windows Forms .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/advanced/how-to-extract-the-icon-associated-with-a-file-in-windows-forms?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/winforms/advanced/how-to-extract-the-icon-associated-with-a-file-in-windows-forms.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/winforms/advanced/how-to-extract-the-icon-associated-with-a-file-in-windows-forms.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hi @AesirHod, while I appreciate the predicament you're in but I don't really have an answer for you. You're better off asking a public forum where you can share your code and get multiple people looking at it, especially those that may have also delt with the issue you're having. I would suggest StackOverflow or [Microsoft Q&A WPF](https://docs.microsoft.com/en-us/answers/topics/wpf.html).

If you end up finding a solution to your problem and can then get that feedback into the docs, I would love a PR or this issue updated. I'll close it for now as I don't think there is anything I can do to the docs at this point in time.

**Comment by AesirHod** [comment]
I couldn’t find any good explanation online, but a few similar problems involving converting the icon to a bitmap and manually editing the alpha channel.

It seems only the first part was needed, as the ImageList accepts both Icons and Bitmaps. It doesn’t seem efficient, and I’m not sure why it worked, but it achieved the result I needed.

Perhaps this information will be useful to someone else.
