### ISSUE TITLE
Not an event handler

### ISSUE THREAD

**Issue by paulwolt** [dotnet/docs-desktop#1297]
The one thing I need is the event name after the Handles operator. How might one handle the opening event of the ContextMenuStrip?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0280b4a-bdc8-2c83-cd4d-25bdafd62c95
* Version Independent ID: c26d1d5e-f8d1-9342-80ee-02527ab49d54
* Content: [How to: Handle the ContextMenuStrip Opening Event - Windows Forms .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/controls/how-to-handle-the-contextmenustrip-opening-event?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/winforms/controls/how-to-handle-the-contextmenustrip-opening-event.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/winforms/controls/how-to-handle-the-contextmenustrip-opening-event.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hi @paulwolt Can you give me more information? I'm assuming you're using VB.NET? The events in VB can be hooked up in multiple ways, one is through the designer in Visual Studio, which is what this article is describing. When you're trying to use teh `Handles` operator, yes you need the event name, which is `Opening`

**Comment by paulwolt** [comment]
Thank you so much. I eventually found my mistake. The code sample is missing the Handles operator, so I wasn’t sure what to do.

But, problem now solved. 

Thanks again.
