### ISSUE TITLE
DataBindingDemo project can't be run

### ISSUE THREAD

**Issue by tking222** [dotnet/docs-desktop#1299]
[Enter feedback here]

The DataBindingDemo project cannot be run, after compilation, select Group by category or other Checkbox will appear, the listingPeer is null, and the peer cannot be obtained automatically!! How to solve!! Thank you!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2fd805d-cc4c-d546-4fd5-fae24a4aea24
* Version Independent ID: c7bc226d-cd15-3740-a840-b12f7180fd04
* Content: [Data binding overview - WPF .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/data/data-binding-overview?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/data/data-binding-overview.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/data/data-binding-overview.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
@tking222 Hello. This is an issue with the sample itself, which had some updates to it which broke it. I've filed a new issue in that repo to get them to fix it. I'll close this issue as its external to us. Thank you very much for reporting it!

**Comment by tking222** [comment]
No one can solve this problem？？？？
