### ISSUE TITLE
what about to add some pictures and/or videos, how to do that, you explain?!! Its 21 century!

### ISSUE THREAD

**Issue by dobrys** [dotnet/docs-desktop#1325]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c48a1f29-7c7a-3a51-f542-2597b7bf0dd4
* Version Independent ID: e7f93079-a86e-8131-d8ed-a853e537e903
* Content: [Arrange Controls Using FlowLayoutPanel - Windows Forms .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/controls/walkthrough-arranging-controls-on-windows-forms-using-a-flowlayoutpanel?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/winforms/controls/walkthrough-arranging-controls-on-windows-forms-using-a-flowlayoutpanel.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/winforms/controls/walkthrough-arranging-controls-on-windows-forms-using-a-flowlayoutpanel.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hi, thank you for the feedback. We're getting there as we update this documentation for .NET 6. As you can see in the overview article, I added a lot of screenshots:

https://docs.microsoft.com/en-us/dotnet/desktop/winforms/controls/layout?view=netdesktop-6.0#container-flow-layout

The old documentation isn't going to be updated though. I'll close this issue
