### ISSUE TITLE
Provide xmlns references

### ISSUE THREAD

**Issue by markolbert** [dotnet/docs-desktop#1334]
I may have missed it, but providing the xmlns and xmlns:x references so that you can use XAML 2009 in your XAML files would be really helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdd1a056-e4fc-2c31-dc92-dd885504b489
* Version Independent ID: 22e8add7-710c-40b0-48c9-386965594140
* Content: [XAML 2009 Language Features - XAML](https://docs.microsoft.com/en-us/dotnet/desktop/xaml-services/xaml-2009-language-features)
* Content Source: [dotnet-desktop-guide/xaml-services/xaml-2009-language-features.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/xaml-services/xaml-2009-language-features.md)
* Product: **dotnet-desktop**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Do you just change the text in the namespace from 2006 to 2009?

**Comment by markolbert** [comment]
Tried that, didn’t work. Sorry should’ve mentioned that.

**Comment by adegeo** [comment]
Does WinUI 3 support XAML 2009? Everything I find online says 2006. Perhaps you could ask in their doc repos?

I looked through their source code and they're using 2006: https://github.com/microsoft/microsoft-ui-xaml/blob/main/dev/Breadcrumb/BreadcrumbBar.xaml

**Comment by markolbert** [comment]
Fair point. I'll ask over there.
