### ISSUE TITLE
Good review just missing one small thing.

### ISSUE THREAD

**Issue by Madelnick** [dotnet/docs-desktop#134]
[Enter feedback here]

Looking good, however, it's never explained (I'm brand new c# student) why devs omit the Toolbox, even in VS 2019. What's up with that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3d7ba9b-4bc3-105a-bed6-fed320821bb5
* Version Independent ID: cc43c332-3eb2-9473-b88a-128c6390cfec
* Content: [Create your first WPF app in Visual Studio 2019 - .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/getting-started/walkthrough-my-first-wpf-desktop-application?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/getting-started/walkthrough-my-first-wpf-desktop-application.md](https://github.com/dotnet/docs-desktop/blob/master/dotnet-desktop-guide/framework/wpf/getting-started/walkthrough-my-first-wpf-desktop-application.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
@Madelnick Hello! I'm not sure what you mean by omit the Toolbox 😄
