### ISSUE TITLE
Korean Translation Issue

### ISSUE THREAD

**Issue by CharlesNKim** [dotnet/docs-desktop#1342]
Hello

At below picture, TextBox control can't use [Formatting command like toggleBold(Ctr+B)
![image](https://user-images.githubusercontent.com/14905230/160958500-df10cd7b-59de-4f64-ab9d-9f7999b65de8.png)

But in this picture (korean version of document), it is possible to use [Formatting command like toggleBold(Ctr+B)
![image](https://user-images.githubusercontent.com/14905230/160958673-e876f12f-faf8-409a-9d12-2b66a7d2a449.png)

i can't find where fix it.

plz check it
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5806507-7645-b3c5-fb2c-921bd5d9d06c
* Version Independent ID: d6356719-549f-4de5-8c3c-0738b9246f30
* Content: [RichTextBox Overview - WPF .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/controls/richtextbox-overview?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/controls/richtextbox-overview.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/controls/richtextbox-overview.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
@CharlesNKim Hello. Thank you for reporting this. Are you saying that the line is saying Yes in Korean, but the English says No?

**Comment by CharlesNKim** [comment]
Hello.
You are right!
Korean "예" means "Yes".

"No" can translated by Korean "아니오"
