### ISSUE TITLE
Problem with Background Operation Example

### ISSUE THREAD

**Issue by MaxFun** [dotnet/docs-desktop#1344]
Followed Walkthrough, it compiles and runs. With a NumericUpDown set to 40, after a while a results is produced but the ProgressBar never indicates anything happening. Tried higher values of  NumericUpDown, still no ProgressBar indications.

Are the files that were generated by Visual Studio for the example available to download so I  can compare and see what I missed?

Thanks

**Comment by adegeo** [comment]
Hello, sorry for the delay. I was on vacation. Can you tell me which article you were following?

**Comment by adegeo** [comment]
Closing do to lack of response.
