### ISSUE TITLE
Add a note about accessibility when using the WinForms WebBrowser control

### ISSUE THREAD

**Issue by merriemcgaw** [dotnet/docs-desktop#1354]
Per Accessibility Team we should put a note that says the WebBrowser should only be in the Tab Order of the form if it has some type of content. Otherwise, it should not be part of the Tab Order.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62a507fd-04e5-4876-920e-f4fb8ddfd7df
* Version Independent ID: be89c649-d099-fc47-6711-fcfaf3948b27
* Content: [Add web browser capabilities to app - Windows Forms .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/controls/how-to-add-web-browser-capabilities-to-a-windows-forms-application?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/winforms/controls/how-to-add-web-browser-capabilities-to-a-windows-forms-application.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/winforms/controls/how-to-add-web-browser-capabilities-to-a-windows-forms-application.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
@merriemcgaw Just to verify, for .NET Framework?

**Comment by merriemcgaw** [comment]
Yes, but I think we can just close this issue. I did a PR directly on the doc page and @RussKie kindly approved it and it's merged.
