### ISSUE TITLE
Correction to BuildRegularPolygon

### ISSUE THREAD

**Issue by DrTomF** [dotnet/docs-desktop#1358]
### Type of issue

Other (describe below)

### Description

Thanks for giving the BuildRegularPolygon code but to work correctly you should change the using block as follows:

     using (StreamGeometryContext ctx = geometry.Open())
            {

                double step = 2 * Math.PI / Math.Max(numSides, 3);
                Point cur = c;

                double a = Math.PI * offsetDegree / 180.0;
                for (int i = 0; i < numSides; i++, a += step)
                {
                    cur.X = c.X + r * Math.Cos(a);
                    cur.Y = c.Y + r * Math.Sin(a);
                    if (i == 0)
                    {
                        ctx.BeginFigure(cur, true /* is filled */, true /* is closed */);
                    }
                    else
                    {
                        ctx.LineTo(cur, true /* is stroked */, false /* is smooth join */);
                    }
                }
            }

### Page URL

https://learn.microsoft.com/en-us/dotnet/desktop/wpf/graphics-multimedia/how-to-create-a-shape-using-a-streamgeometry?view=netframeworkdesktop-4.8

### Content source URL

https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/graphics-multimedia/how-to-create-a-shape-using-a-streamgeometry.md

### Document Version Independent Id

2836c340-b97b-5e9c-7d95-b12984dd281b

### Article author

@adegeo

**Comment by adegeo** [comment]
Thank you for opening this issue. I'll add it to the backlog. If you would like to contribute, you can submit a fix by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!
