### ISSUE TITLE
Create Direct3D9 Content doesn't compile.

### ISSUE THREAD

**Issue by Ianuarius** [dotnet/docs-desktop#1361]
I was getting a bunch of errors like "initialization of "'vertices'" is skipped by 'goto Cleanup'".

Seems like either the code is just wrong or I needed to know something that wasn't specified in the doc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ef22dd6-1f3d-0d61-b3eb-ea613def646b
* Version Independent ID: 32ba1989-bc1e-622a-da48-81a891c2f288
* Content: [Create Direct3D9 Content for Hosting - WPF .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/walkthrough-creating-direct3d9-content-for-hosting-in-wpf?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/advanced/walkthrough-creating-direct3d9-content-for-hosting-in-wpf.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/advanced/walkthrough-creating-direct3d9-content-for-hosting-in-wpf.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello. This content is pretty old and currently unmaintained. I don't know how much help I can be. You'll need to provide more information like what version of visual studio you're using, which libraries you're referencing, what version of .net you're targetting etc..

**Comment by adegeo** [comment]
Closing do to lack of response.
