### ISSUE TITLE
5.Should be Grid.Background

### ISSUE THREAD

**Issue by ScottChiu** [dotnet/docs-desktop#137]
[Enter feedback here]
5.Set the Panel.Background property to the watermark.png image file, by adding the following XAML anywhere between the <Grid> and </Grid> tags:
=>Should be Grid.Background instead of Panel.Background
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3d7ba9b-4bc3-105a-bed6-fed320821bb5
* Version Independent ID: cc43c332-3eb2-9473-b88a-128c6390cfec
* Content: [Create your first WPF app in Visual Studio 2019 - .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/getting-started/walkthrough-my-first-wpf-desktop-application?view=netframeworkdesktop-4.8#create-the-layout)
* Content Source: [dotnet-desktop-guide/framework/wpf/getting-started/walkthrough-my-first-wpf-desktop-application.md](https://github.com/dotnet/docs-desktop/blob/master/dotnet-desktop-guide/framework/wpf/getting-started/walkthrough-my-first-wpf-desktop-application.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello. The property is actually provided by the Panel object, which is why the link is resolving that way. However, we could change the link text to make it clear it's still the grid that we're working with.

**Comment by DuddyRosenberg** [comment]
I'm following all the steps and keep blowing up at this
![image](https://user-images.githubusercontent.com/63026090/104141150-4649e080-5383-11eb-96bc-7149b8510162.png)

**Comment by DuddyRosenberg** [comment]
> I'm following all the steps and keep blowing up at this
> ![image](https://user-images.githubusercontent.com/63026090/104141150-4649e080-5383-11eb-96bc-7149b8510162.png)

I believe it has something to do with the background image...
That's line 25
<ImageBrush ImageSource="/watermark.png" />

**Comment by adegeo** [comment]
Please open a [new issue with this link](https://github.com/dotnet/docs-desktop/issues/new?title=&body=%0A%0A%5BEnter%20feedback%20here%5D%0A%0A%0A---%0A%23%23%23%23%20Document%20Details%0A%0A%E2%9A%A0%20*Do%20not%20edit%20this%20section.%20It%20is%20required%20for%20docs.microsoft.com%20%E2%9E%9F%20GitHub%20issue%20linking.*%0A%0A*%20ID%3A%20d3d7ba9b-4bc3-105a-bed6-fed320821bb5%0A*%20Version%20Independent%20ID%3A%20cc43c332-3eb2-9473-b88a-128c6390cfec%0A*%20Content%3A%20%5BCreate%20your%20first%20WPF%20app%20in%20Visual%20Studio%202019%20-%20.NET%20Framework%5D(https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fdotnet%2Fdesktop%2Fwpf%2Fgetting-started%2Fwalkthrough-my-first-wpf-desktop-application%3Fview%3Dnetframeworkdesktop-4.8%23create-the-layout)%0A*%20Content%20Source%3A%20%5Bdotnet-desktop-guide%2Fframework%2Fwpf%2Fgetting-started%2Fwalkthrough-my-first-wpf-desktop-application.md%5D(https%3A%2F%2Fgithub.com%2Fdotnet%2Fdocs-desktop%2Fblob%2Fmaster%2Fdotnet-desktop-guide%2Fframework%2Fwpf%2Fgetting-started%2Fwalkthrough-my-first-wpf-desktop-application.md)%0A*%20Product%3A%20**dotnet-framework**%0A*%20Technology%3A%20**dotnet-wpf**%0A*%20GitHub%20Login%3A%20%40adegeo%0A*%20Microsoft%20Alias%3A%20**adegeo**) and add more information such as your XAML being used. Thanks!
