### ISSUE TITLE
background, not foreground

### ISSUE THREAD

**Issue by hayimadler** [dotnet/docs-desktop#1376]
In the paragraph titled "Use a VisualState", this sentence appears: 

"In the previous section, a <PropertyTrigger> was used to change the **foreground** of the button to AliceBlue".

This should say "background"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a7c3600-979e-8255-c6a6-d0db5424d154
* Version Independent ID: a3754a51-bf4f-3fb5-3d9c-98076160dd87
* Content: [How to create a template - WPF .NET](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/controls/how-to-create-apply-template?view=netdesktop-6.0&redirectedfrom=MSDN&viewFallbackFrom=netdesktop-5.0)
* Content Source: [dotnet-desktop-guide/net/wpf/controls/how-to-create-apply-template.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/net/wpf/controls/how-to-create-apply-template.md)
* Product: **dotnet-desktop**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for opening this issue. I'll add it to the backlog. If you would like to contribute, you can submit a fix by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!
