### ISSUE TITLE
XAML is not enough for Glyph example

### ISSUE THREAD

**Issue by maxima120** [dotnet/docs-desktop#1385]
In older MSDN doc, there was detailed info with examples for use of Glyphs to draw text in WPF .

Now it just bland XAML example with constant strings. Hardly usable.

A C# code sample is really necessary.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a42284f-53df-2f8c-3e8a-356d64dd2db7
* Version Independent ID: 34d8bc29-2ac2-467a-387d-7bc11661f8de
* Content: [Draw Text Using Glyphs - WPF .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/draw-text-using-glyphs?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/advanced/draw-text-using-glyphs.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/advanced/draw-text-using-glyphs.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello, do you know where this old doc is?

**Comment by adegeo** [comment]
Closing do to lack of response.
