### ISSUE TITLE
Xasan

### ISSUE THREAD

**Issue by Green71dev** [dotnet/docs-desktop#1389]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04e26c31-83eb-7195-f020-5efa86c5266a
* Version Independent ID: 8a23c1c2-3671-b7d9-f648-c29f16724e2c
* Content: [Data Binding Overview - Windows Forms .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/data-binding-and-windows-forms?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/winforms/data-binding-and-windows-forms.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/winforms/data-binding-and-windows-forms.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello! It seems you opened this issue in error. I'll close it.
