### ISSUE TITLE
Please add a screenshot in the section "Set a ToolTip in the designer"

### ISSUE THREAD

**Issue by ArmorBearer** [dotnet/docs-desktop#1390]
Would really help if there was a screenshot to show how to do this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c4a50d0-78db-d25d-735b-efc940ff167d
* Version Independent ID: 3aee9297-c8ea-7c58-93a0-0458f0d0aebb
* Content: [How to: Set ToolTips for Controls on a Windows Form at Design Time - Windows Forms .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/controls/how-to-set-tooltips-for-controls-on-a-windows-form-at-design-time?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/winforms/controls/how-to-set-tooltips-for-controls-on-a-windows-form-at-design-time.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/winforms/controls/how-to-set-tooltips-for-controls-on-a-windows-form-at-design-time.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello. Unless it's a much longer article, we don't typically add screenshots. There are too many to update when a new version comes out and something is tweaked.

That said, is there something about the text that is confusing, which we could change to make it better?

**Comment by adegeo** [comment]
Closing do to lack of response.
