### ISSUE TITLE
String mismatch between example markup and image

### ISSUE THREAD

**Issue by Plantelo** [dotnet/docs-desktop#1399]
### Type of issue

Typo

### Description

The XAML code for the example window has a Title tag with the word "Button" (from "Window with Button") capitalised, whereas the related example image shows a window with a title that has the word "button" fully in lowercase.
![discrepancy](https://user-images.githubusercontent.com/63164279/172574845-da3d3a8e-512a-461b-8827-dad8d59c8cad.png)

### Page URL

https://learn.microsoft.com/en-us/dotnet/desktop/wpf/overview/?view=netdesktop-6.0#feedback

### Content source URL

https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/net/wpf/overview/index.md

### Document Version Independent Id

1a4d3c35-a9ac-97e7-a726-b5b4c42a45f5

### Article author

@adegeo

**Comment by adegeo** [comment]
Thank you for opening this issue. I'll add it to the backlog. If you would like to contribute, you can submit a fix by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!
