### ISSUE TITLE
missing reference?

### ISSUE THREAD

**Issue by tsmos** [dotnet/docs-desktop#1408]
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0ad1362-3064-9816-47e7-7c29cd990173
* Version Independent ID: 08bd499b-178c-fb04-8980-41db01163b66
* Content: [How to: Implement Property Change Notification - WPF .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/data/how-to-implement-property-change-notification?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/data/how-to-implement-property-change-notification.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/data/how-to-implement-property-change-notification.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello. There doesn't seem to be many details in your issue. What reference is missing?
