### ISSUE TITLE
Request for adding more GIFs and Images in the documentation

### ISSUE THREAD

**Issue by sourashis59** [dotnet/docs-desktop#1411]
[Enter feedback here]

This is a documentation for UI, and there is not enough GIF or images of the UI changes done by changing the codes according to the documentations. This is extremely hard to understand what the codes are doing without any visual example. So it would be very helpful if visualization can be added for each codes in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a80625f-714f-fa9a-eb50-223b1ef4646c
* Version Independent ID: 1a4d3c35-a9ac-97e7-a726-b5b4c42a45f5
* Content: [What is Windows Presentation Foundation - WPF .NET](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/overview/?view=netdesktop-6.0)
* Content Source: [dotnet-desktop-guide/net/wpf/overview/index.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/net/wpf/overview/index.md)
* Product: **dotnet-desktop**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by RokasMarcinkevicius** [comment]
+1

**Comment by adegeo** [comment]
Are you talking about _all_ pages of documentation adding more screenshots? Or this article specifically, which has a lot of screenshots.

**Comment by sourashis59** [comment]
> Are you talking about _all_ pages of documentation adding more screenshots? Or this article specifically, which has a lot of screenshots.

All documentation pages actually.
