### ISSUE TITLE
page tells you to dispose of *any* objects that consume memory 

### ISSUE THREAD

**Issue by ArjanWiegelBrunelco** [dotnet/docs-desktop#1425]
"You should always call [Dispose](https://docs.microsoft.com/en-us/dotnet/api/system.idisposable.dispose) on any objects that consume system resources, such as [Pen](https://docs.microsoft.com/en-us/dotnet/api/system.drawing.pen) and [Graphics](https://docs.microsoft.com/en-us/dotnet/api/system.drawing.graphics) objects." 
Unaware users could take this advice literally. Please update the text to something in the line of: 
"You should always call [Dispose](https://docs.microsoft.com/en-us/dotnet/api/system.idisposable.dispose) on any objects that you created and consume system resources, such as [Pen](https://docs.microsoft.com/en-us/dotnet/api/system.drawing.pen) and [Graphics](https://docs.microsoft.com/en-us/dotnet/api/system.drawing.graphics) objects. Do not dispose of objects that you borrow from parent objects"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18e44864-2e5c-0d60-f14a-3bd8b3992a45
* Version Independent ID: afcf1d60-d1bf-6a10-7938-0435627eca49
* Content: [How to: Draw an Outlined Shape - Windows Forms .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/advanced/how-to-draw-an-outlined-shape?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/winforms/advanced/how-to-draw-an-outlined-shape.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/winforms/advanced/how-to-draw-an-outlined-shape.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Great point!

**Comment by ArjanWiegelBrunelco** [comment]
Thanks Adegeo. If I recall correctly, there were more examples with literally the same remark.
