### ISSUE TITLE
Error in the wording of the points in the documentation

### ISSUE THREAD

**Issue by justinasfour04** [dotnet/docs-desktop#146]
I have an issue with the comment in the documentation that is highlighted in the following issue that I posted on the ReactiveUI documentation https://github.com/reactiveui/website/issues/493

This documentation states
`The partial class must derive from the type that backs the root element.`
which as I mention in my issue raised with ReactiveUI, isn't strictly true. explaining how a partial class only needs it to be defined in once place but that MUST be on the xaml, so having it on the code behind is redundant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2e55a3e-08f2-ceaa-2e39-f907493b4b31
* Version Independent ID: f53e3de6-01a6-e43a-8cc5-fd338c168018
* Content: [Code-Behind and XAML - WPF .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/code-behind-and-xaml-in-wpf?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/advanced/code-behind-and-xaml-in-wpf.md](https://github.com/dotnet/docs-desktop/blob/master/dotnet-desktop-guide/framework/wpf/advanced/code-behind-and-xaml-in-wpf.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello. If I understand what your saying and how it all works, this statement is indeed correct. The partial class is usually generated by a build step in Visual Studio. This takes care of it for you, but if you were to omit that build step for some reason, you would be creating the class by hand and thus you would need to make sure that the class inherits from the same class as the root element.

The next bullet point clarifies that a bit:

>- Note that under the default behavior of the markup compile build actions, **you can leave the derivation blank in the partial class definition on the code-behind side**. The compiled result will assume the page root's backing type to be the basis for the partial class, even if it not specified. However, **relying on this behavior is not a best practice**.
