### ISSUE TITLE
Security PDF document not downloading.

### ISSUE THREAD

**Issue by NishitRaghunath** [dotnet/docs-desktop#1492]
[Enter feedback here]

Sir,
I find that the link that says "Download PDF" has a bug. Instead of allowing to download the pertinent PDF, it results in a download of the section "Introduction to WPF". Please fix this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22eeece6-7f1f-e074-24a6-7c24785119c2
* Version Independent ID: 40d26324-94a8-0eed-a92c-d5d65c957ebb
* Content: [Security - WPF .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/security-wpf?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/security-wpf.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/security-wpf.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
I just tested this and it seems to download all of the TOC content, which includes the security article. I believe this is operating correctly.
