### ISSUE TITLE
[Tracking] Consider renaming "up-for-grabs" label to "help wanted" & "good-first-issue" to "good first issue"

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs-desktop#1497]
Using the default label name is especially recognized by GitHub and we're trying to get a consistent experience for newcomers. See context at https://github.com/dotnet/runtime/issues/71496

Your project is also part of https://up-for-grabs.net/
Update the entry at https://github.com/up-for-grabs/up-for-grabs.net/blob/gh-pages/_data/projects/dotnet-docs-desktop.yml as well

/cc @danmoseley

**Comment by adegeo** [comment]
- Updated the labels
- Opened PR in up-for-grabs repo https://github.com/up-for-grabs/up-for-grabs.net/pull/3363
