### ISSUE TITLE
[doc bug]: D3DCode.DLL is not included in the legacy direct X install

### ISSUE THREAD

**Issue by maross3** [dotnet/docs-desktop#1498]
### Article URL

https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/advanced/walkthrough-hosting-direct3d9-content-in-wpf.md

### Technology

WPF (Windows Presentation Foundation)

### Version

- [X] .NET 5 or later (also .NET Core)
- [X] .NET Framework 4

### Description

`D3DCode.DLL` is not included in the legacy direct X SDK install, nor windows SDK 10 install. all of the documentation in regards to using direct X and WPF seems to be outdated. The documentation should be removed/archived if no longer supported, or updated if there is another work around for the interops of DX and WPF.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1eb4ec97-fc8a-2243-7049-d16fdce00107
* Version Independent ID: 54c533b5-1cdc-b113-a416-ab0f5d831b2f
* Content: [Host Direct3D9 content in WPF](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/advanced/walkthrough-hosting-direct3d9-content-in-wpf?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/advanced/walkthrough-hosting-direct3d9-content-in-wpf.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/advanced/walkthrough-hosting-direct3d9-content-in-wpf.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
I looked at this really quick and I discovered the prerequisites section for this article talks about creating your own DLL that contains those methods. It's documented in this article: https://learn.microsoft.com/en-us/dotnet/desktop/wpf/advanced/walkthrough-creating-direct3d9-content-for-hosting-in-wpf?view=netframeworkdesktop-4.8

However, as you pointed out, the content is very old. We're not really looking at updating this content right now. If we do in the future, for .NET 6+ we would probably first search for a library on [NuGet that interops WPF and DirectX](https://www.nuget.org/packages?q=directx+wpf) or at a minimum, just demonstrate using the [SharpDX library](http://sharpdx.org/)
