### ISSUE TITLE
Update Debugging WinForms Controls tutorial page to indicate this doesn't work for .NET controls.

### ISSUE THREAD

**Issue by merriemcgaw** [dotnet/docs-desktop#1499]
Users are attempting to use this page to create and debug WinForms .NET controls. This no longer works given that our designer now runs out of process. @KlausLoeffelmann is creating a doc to show how to do this. We're working on blogs and other docs to cover the WinForms .NET controls creation process currently and how to debug them. We will be creating an WinForms Designer SDK Extensibility samples repo shortly that will include samples and how to docs for everything. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cf24e8a-af35-53f6-093d-5392128ad3fb
* Version Independent ID: f493ff27-e2e1-ad7e-38d4-46ded0c45022
* Content: [Debug Custom Controls at Design Time - Windows Forms .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/controls/walkthrough-debugging-custom-windows-forms-controls-at-design-time?view=netframeworkdesktop-4.8&viewFallbackFrom=netdesktop-6.0)
* Content Source: [dotnet-desktop-guide/framework/winforms/controls/walkthrough-debugging-custom-windows-forms-controls-at-design-time.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/winforms/controls/walkthrough-debugging-custom-windows-forms-controls-at-design-time.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

---
[Associated WorkItem - 117823](https://dev.azure.com/msft-skilling/Content/_workitems/edit/117823)

**Comment by adegeo** [comment]
@merriemcgaw This still works for .NET Framework projects though, right?

**Comment by KlausLoeffelmann** [comment]
Yes, it does. Well, at least for .NET Framework projects in the classic WinForms Designer. There will be scenarios, where even .NET Framework projects need to be designed in the .NET Framework OOP Designer, namely when you need to design 32-Bit Components in a .NET Framework App in VS 2022 (which is 64-Bit). For that, you would also need to use the .NET Framework WinForms OOP Designer. That one is work in progress, though.

**Comment by merriemcgaw** [comment]
What @KlausLoeffelmann said 😄
