### ISSUE TITLE
Feedback to HowTo site [How to: Group, sort, and filter Data in the DataGrid control - WPF .NET Framework]

### ISSUE THREAD

**Issue by kkromkowski-GOD** [dotnet/docs-desktop#1502]
This site looks great and example is really deeply explained and ease to read and understand. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cdb1d027-90c8-941e-769a-27e85e7567ef
* Version Independent ID: f7560a46-71c3-e1c6-64b4-04d54b156809
* Content: [How to: Group, sort, and filter Data in the DataGrid control - WPF .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/controls/how-to-group-sort-and-filter-data-in-the-datagrid-control?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/controls/how-to-group-sort-and-filter-data-in-the-datagrid-control.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/controls/how-to-group-sort-and-filter-data-in-the-datagrid-control.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thanks!
