### ISSUE TITLE
this article is trash

### ISSUE THREAD

**Issue by stevensrf11** [dotnet/docs-desktop#1505]
Nothing fucking works as stated in the article when the code is ran.
 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23f605d0-6326-17d5-3087-4f6ef96ab9bb
* Version Independent ID: 10411c7d-3586-4904-6d4f-79e84f0c9b98
* Content: [Walkthrough: Enabling Drag and Drop on a User Control - WPF .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/walkthrough-enabling-drag-and-drop-on-a-user-control?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/advanced/walkthrough-enabling-drag-and-drop-on-a-user-control.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/advanced/walkthrough-enabling-drag-and-drop-on-a-user-control.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello. I would assist you if you could be more clear as to what doesn't work? I just created a new .net 4.7 project, ran through the full article, found 1 bug in the article at the end of the article. Everything prior to that worked fine. Here is the project I just created:

[code.zip](https://github.com/dotnet/docs-desktop/files/9550919/code.zip)

In the meantime, you should read the .NET Foundation [code of conduct](https://dotnetfoundation.org/about/code-of-conduct) and consider editing your title and question above.
