### ISSUE TITLE
example doesn't work .net 6.0

### ISSUE THREAD

**Issue by androvisuals** [dotnet/docs-desktop#1513]
[Enter feedback here]
![image](https://user-images.githubusercontent.com/19530188/191359741-3fb8ac44-294b-49f1-ba85-45a4e565a590.png)

All of these namespaces are missing in the windows form application yet there's no information about it on the example page. After googling it it seems that the .csproj file has to be modified. How exactly is unclear. This needs to be updated to.net 6.0 or include a solution when using .net 6.0

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5e19b710-bc33-02ea-b96a-3c13699ab9f4
* Version Independent ID: d4ceecb3-428c-5a3a-b7aa-4476304aae74
* Content: [How to: Animate a Rectangle - WPF .NET Framework](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/graphics-multimedia/how-to-animate-a-rectangle?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/graphics-multimedia/how-to-animate-a-rectangle.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/graphics-multimedia/how-to-animate-a-rectangle.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
It sounds like you're missing the `<UseWPF>true</UseWPF>` setting in your project. Can you confirm you have that set?
