### ISSUE TITLE
[doc bug]: Title shows .NET 5 when .NET 6 documentation is selected

### ISSUE THREAD

**Issue by ronnielutaro** [dotnet/docs-desktop#1515]
### Article URL

https://learn.microsoft.com/en-us/dotnet/desktop/wpf/?view=netdesktop-6.0

### Technology

WPF (Windows Presentation Foundation)

### Version

- .NET 6 

### Description

Main title shows .NET 5 when .NET 6 version of the documentation is selected. 
![docs issue](https://user-images.githubusercontent.com/29591720/192395854-d6ce3939-96f6-488a-9a71-500e00691348.png)

---
[Associated WorkItem - 86419](https://dev.azure.com/msft-skilling/Content/_workitems/edit/86419)

**Comment by RonnieLutalo** [comment]
In case this is something that needs a fix, I offer to work on this.

**Comment by adegeo** [comment]
Thank you for opening this. I'm going to have to add .NET 7 to the system soon and I'll go through and look at all the places where it says .NET 5/6 and adjust them. Thanks again.
