### ISSUE TITLE
Example does not work.

### ISSUE THREAD

**Issue by movsar** [dotnet/docs-desktop#1524]
When I try to go through walkthrough, on "**To process the dropped data**" section, if I drag and drop text from the TextBox, nothing happens as `e.Data.GetDataPresent(DataFormats.StringFormat)` returns `null`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 23f605d0-6326-17d5-3087-4f6ef96ab9bb
* Version Independent ID: 10411c7d-3586-4904-6d4f-79e84f0c9b98
* Content: [Walkthrough: Enabling Drag and Drop on a User Control - WPF .NET Framework](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/advanced/walkthrough-enabling-drag-and-drop-on-a-user-control?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/advanced/walkthrough-enabling-drag-and-drop-on-a-user-control.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/advanced/walkthrough-enabling-drag-and-drop-on-a-user-control.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello, are you using .NET Framework or .NET?
