### ISSUE TITLE
ContentControl is specified as Singleton which is misleading

### ISSUE THREAD

**Issue by pradeepkumar-devaraj** [dotnet/docs-desktop#1531]
### Type of issue

Missing information

### Description

In the page "[Data binding overview in WPF](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/data/?view=netdesktop-6.0)", under the section "[Master-detail binding scenario](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/data/?view=netdesktop-6.0#master-detail-binding-scenario)", the below sentence is not clear, and it is misleading. It can be rephrased for more clarity. 

This binding works because when a **singleton object** (the [ContentControl](https://learn.microsoft.com/en-us/dotnet/api/system.windows.controls.contentcontrol) in this case) is bound to a collection view, it automatically binds to the [CurrentItem](https://learn.microsoft.com/en-us/dotnet/api/system.windows.data.collectionview.currentitem) of the view. 

The word "**Singleton**" is predominantly used to specify a Design pattern. 

### Page URL

https://learn.microsoft.com/en-us/dotnet/desktop/wpf/data/?view=netdesktop-6.0

### Content source URL

https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/net/wpf/data/index.md

### Document Version Independent Id

c7bc226d-cd15-3740-a840-b12f7180fd04

### Article author

@adegeo

**Comment by adegeo** [comment]
Thank you for opening this issue. I'll add it to the backlog. If you would like to contribute, you can submit a fix by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!
