### ISSUE TITLE
Why is there no example to use the layout?

### ISSUE THREAD

**Issue by moerwald** [dotnet/docs-desktop#1532]
### Type of issue

Missing information

### Description

Some code how to use the layout-control would be great ...

### Page URL

https://learn.microsoft.com/en-us/dotnet/desktop/winforms/controls/flowlayoutpanel-control-overview?view=netframeworkdesktop-4.8

### Content source URL

https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/winforms/controls/flowlayoutpanel-control-overview.md

### Document Version Independent Id

9d46a62b-e74f-edbf-7bf0-1ebd05c121e2

### Article author

@adegeo

**Comment by adegeo** [comment]
Thank you for opening this issue. I'll add it to the backlog.

Thanks again!

**Comment by adegeo** [comment]
After looking at this, I think adding full code-first examples is out of scope for the .NET Framework articles. Closing the issue, sorry!
