### ISSUE TITLE
Quality for EncoderParameter has no affect

### ISSUE THREAD

**Issue by jdang67** [dotnet/docs-desktop#1533]
Try to set the Quality value to 0 and the image size not event reduced by a bit.  What is the purpose of this value when it does nothing?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b34c0362-b66b-d065-5d15-87c5dfa810be
* Version Independent ID: b0ca8d84-edb4-0adf-f289-54945dd6ef62
* Content: [How to: Set JPEG Compression Level - Windows Forms .NET Framework](https://learn.microsoft.com/en-us/dotnet/desktop/winforms/advanced/how-to-set-jpeg-compression-level?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/winforms/advanced/how-to-set-jpeg-compression-level.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/winforms/advanced/how-to-set-jpeg-compression-level.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello.

I don't spot any problem with the documentation. If it's wrong, I can't really tell as I don't have a repro project to test with. If you would like, please upload your project so I can compare.

Also, it helps to specify what version of .NET you're using and at least supply the code you're using.
