### ISSUE TITLE
only one control per cell

### ISSUE THREAD

**Issue by johnbo691** [dotnet/docs-desktop#1534]
### Type of issue

Missing information

### Description

How can an overview of the TableLayoutPanel control fail to mention that each cell can only contain one child control, and then not tell the reader how to work around that limitation?  Why would that not be an obvious bit of information to include in an introduction to a control?  You only mentioned this fact once, and that was near the end of the last article for TableLayoutPanel.

> The [TableLayoutPanel](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.tablelayoutpanel) control can contain only one child control per cell.

### Page URL

https://learn.microsoft.com/en-us/dotnet/desktop/winforms/controls/tablelayoutpanel-control-overview?view=netframeworkdesktop-4.8

### Content source URL

https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/winforms/controls/tablelayoutpanel-control-overview.md

### Document Version Independent Id

3a9becfb-2213-8fd4-8003-2d7c1b14e49c

### Article author

@adegeo

**Comment by adegeo** [comment]
Great point! Thank you for opening this issue. I'll add it to the backlog. If you would like to contribute, you can submit a fix by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.
