### ISSUE TITLE
in winforms I'm setting a checkbox property to true, yet it stays false

### ISSUE THREAD

**Issue by rblk2022** [dotnet/docs-desktop#1535]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1f8aa9eb-42a1-c4ec-5ab7-bde4dc76af62
* Version Independent ID: 6157ac57-f5eb-7658-8e6a-846b05f0afdd
* Content: [How to: Make Your Control Invisible at Run Time - Windows Forms .NET Framework](https://learn.microsoft.com/en-us/dotnet/desktop/winforms/controls/how-to-make-your-control-invisible-at-run-time?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/winforms/controls/how-to-make-your-control-invisible-at-run-time.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/winforms/controls/how-to-make-your-control-invisible-at-run-time.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello!

I can try and help if you provide more information, but I think you will have a better chance of getting your question answered if you post it on a forum such as StackOverflow.
