### ISSUE TITLE
Create a Composite Control

### ISSUE THREAD

**Issue by ErickTreetops** [dotnet/docs-desktop#1538]
This list of articles starts at the end with "How to add a control to the toolbox".
How about create it first then last add it to your toolbox to use.
Suggested list
What is a composite control
What Frameworks / platforms allow you to create a composite control. I suspect .net core doesn't allow them, but nowhere does it tell me when I can and can't use a composite control.

Creating a simple composite control.  Nice and simple maybe button and text box)
Properties, events, Design interface.  How to wire it up and use it visually on a form, as in "Visual" studio.
Testing
Adding it to your VS toolbox

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7614753f-afb5-c605-0998-59083ee38baf
* Version Independent ID: 6a567f8b-06e4-ac91-f352-636431540047
* Content: [Develop a Composite Control - Windows Forms .NET Framework](https://learn.microsoft.com/en-us/dotnet/desktop/winforms/controls/developing-a-composite-windows-forms-control?source=recommendations&view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/winforms/controls/developing-a-composite-windows-forms-control.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/winforms/controls/developing-a-composite-windows-forms-control.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Yeah, that's a badly ordered list. The article itself is pretty old and no one has looked at it in quite some time. Right now we're not spending too much time in this area, and this is a simple fix. I'm going to add it to the list good community fixable issues.

If you would like to contribute, you can submit a fix by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

**Comment by adegeo** [comment]
We've started working on this content for .NET 6, https://learn.microsoft.com/en-us/dotnet/desktop/winforms/controls-design/usercontrol-overview?view=netdesktop-7.0
