### ISSUE TITLE
ShouldSerialize methods not called unless declared public

### ISSUE THREAD

**Issue by Facsimiler** [dotnet/docs-desktop#1540]
[Enter feedback here]
The article states that `ShouldSerialize` methods should be declared with the `private` modifier. However, the XML serializer does not appear call these methods, to determine whether the associated property needs to be serialized, unless they are declared `public`. Is this a bug, or is the documentation incorrect? (I'm using the .NET Framework v2.7.2.)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e32682fb-671a-8f6e-045c-e92a96ca029e
* Version Independent ID: 42210b30-f3ee-9975-b3f2-8752f9aca815
* Content: [Defining Default Values with the ShouldSerialize and Reset Methods - Windows Forms .NET Framework](https://learn.microsoft.com/en-us/dotnet/desktop/winforms/controls/defining-default-values-with-the-shouldserialize-and-reset-methods?view=netframeworkdesktop-4.8&redirectedfrom=MSDN)
* Content Source: [dotnet-desktop-guide/framework/winforms/controls/defining-default-values-with-the-shouldserialize-and-reset-methods.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/winforms/controls/defining-default-values-with-the-shouldserialize-and-reset-methods.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

---
[Associated WorkItem - 86074](https://dev.azure.com/msft-skilling/Content/_workitems/edit/86074)

**Comment by adegeo** [comment]
Hi @Facsimiler I'm unsure what you mean exactly. This article is for the windows forms designer on how the properties for the user control should be handled by the designer when placing the control on the form.

You shouldn't have a standalone `ShouldSerialize` method, but a method named after the property. So if you have a property named `Amount` the method name should be `ShouldSerializeAmount`.

**Comment by Facsimiler** [comment]
Hi @adegeo,

Consider the following class that can be serialized (using your `Amount` property as an example) into an XML file:

```C#
using System;
using System.Xml.Serialization;

namespace SomeNamespace {

    [
        Serialization,
        XmlType(TypeName = "SomeNamespace.SomeClass"),    
        XmlInclude(typeof(SomeClass)),
    ]
    public class SomeClass {

        // Etc.

        /** <summary>Amount of this element.</summary>
         *
         *  <remarks>This value is serialized as part of the class's XML definition-but only if the
         *  ShouldSerializeAmount method returns true.</remarks> 
         */
        public int Amount {
            get => //etc.
            set => // etc.
        }
    
        /** <summary>Determine whether the Amount property is serialized.</summary>
         *
         *  <returns>True, if the Amount property should be serialized, or false otherwise.</returns>
         */
        public bool ShouldSerializeAmount() => // Etc.
    }
}
```

The referenced documentation pages states that the `ShouldSerializeAmount` method can be declared `private`, but, in practice, it is not called during serialization unless the method is `public`. Therefore, it's only possible to control whether the `Amount` property is serialized if the `ShouldSerializeAmount` method is `public`, polluting the API.

I'm using the .NET Framework v4.7.2.

**Comment by adegeo** [comment]
Looks like the bot was broken and didn't remove the label when you responded. I'll put this issue on my calendar for next month to take a look at.

**Comment by adegeo** [comment]
OK back to looking at this. Sorry for the delay, but this area isn't my main focus at the moment and this was a lower priority question, sorry.

So I think my original answer still stands. This is talking about the Windows Forms control serializer, not a generic XML serializer.  Looking around various forums and examples on the web, I think this is an undocumented feature (from the `XmlSerializer`'s standpoint that is only there to support the Windows Forms designer.

If you want to have conditional serialization, you need to get a little more into the serialization, possibly even controlling the entire serialization of the object. Also, other serializers may have more features that can support this, such as Json.NET for Json serialization.

I would open a request on stackoverflow with as much information as possible about what type of data you're using, how you want it to appear, and the capabilities such as conditional serialized properties. You'll get a large set of eyes looking at your programming question and hopefully get a better answer.

Sorry 😦
