### ISSUE TITLE
The Inheritance Picker does not show up.

### ISSUE THREAD

**Issue by makelyblakley** [dotnet/docs-desktop#1541]
The Inheritance Picker does not show up when I select a windows form and choose add. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fd246dd8-c0c4-a9d6-81a0-79e41a3dfa01
* Version Independent ID: 34af6cdd-7d21-5729-a41e-2b235d20c4ab
* Content: [How to: Inherit Forms Using the Inheritance Picker Dialog Box - Windows Forms .NET Framework](https://learn.microsoft.com/en-us/dotnet/desktop/winforms/advanced/how-to-inherit-forms-using-the-inheritance-picker-dialog-box?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/winforms/advanced/how-to-inherit-forms-using-the-inheritance-picker-dialog-box.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/winforms/advanced/how-to-inherit-forms-using-the-inheritance-picker-dialog-box.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
The Inheritance Picker is only available in a .NET Framework project, and you're probably using a .NET 6 or 7 project. I just created projects for both types and noticed it's only in .NET Framework. I think this will answer your question.
