### ISSUE TITLE
Outdated text in XAML overview

### ISSUE THREAD

**Issue by jacksonriley** [dotnet/docs-desktop#1542]
[Enter feedback here]
The section [Events and XAML code-behind](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/xaml/?view=netdesktop-6.0#events-and-xaml-code-behind) refers to an old version of a snippet in the text - i.e. the snippet is

```xaml
<Window x:Class="index.Window2"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        Title="Window2" Height="450" Width="800">
    <StackPanel>
        <Button Click="Button_Click">Click me</Button>
    </StackPanel>
</Window>
```
but the text refers to `ExampleNamespace` and `ExamplePage` instead of `index.Window2`:
> Notice that the code-behind file uses the CLR namespace `ExampleNamespace` and declares `ExamplePage` as a partial class within that namespace. This parallels the `x:Class` attribute value of `ExampleNamespace.ExamplePage` that was provided in the markup root.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 41391f13-7c61-97ac-e16e-ca1f280d79f6
* Version Independent ID: 12ab183d-74fa-e353-9761-fb5edc553e40
* Content: [XAML overview - WPF .NET](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/xaml/?view=netdesktop-6.0)
* Content Source: [dotnet-desktop-guide/net/wpf/xaml/index.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/net/wpf/xaml/index.md)
* Product: **dotnet-desktop**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

---
[Associated WorkItem - 52209](https://dev.azure.com/msft-skilling/Content/_workitems/edit/52209)

**Comment by adegeo** [comment]
Thanks for pointing this out. I'll add this to the backlog to get fixed.
