### ISSUE TITLE
Printing Windows Form in C#

### ISSUE THREAD

**Issue by gjohnsonjr** [dotnet/docs-desktop#1543]
I have followed the instructions but when the app enters the:

private void PrintDocument1_PrintPage(System.Object sender,
           System.Drawing.Printing.PrintPageEventArgs e) =>
            e.Graphics.DrawImage(memoryImage, 0, 0);

section, the memoryImage is always **null**, even after it is **not** null during the CaptureScreen() function.

NOTE: I found my error. Sorry to have bothered you. Thanks.
Glen

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 897fff16-d70f-5e07-0d49-a718e35df446
* Version Independent ID: 08014790-627a-e56f-9eea-309f4d70c016
* Content: [How to: Print a Windows Form - Windows Forms .NET Framework](https://learn.microsoft.com/en-us/dotnet/desktop/winforms/advanced/how-to-print-a-windows-form?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/winforms/advanced/how-to-print-a-windows-form.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/winforms/advanced/how-to-print-a-windows-form.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
No problem, glad you got it working 😁
