### ISSUE TITLE
looks like a minor editing error

### ISSUE THREAD

**Issue by kwbBaker** [dotnet/docs-desktop#1544]
Notice the sentence ending a paragraph, "Add the Microsoft.Windows.Compatibility package."  I think that was probably intended to be a sub-section title.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 98778ad1-6c20-6310-e4bc-9d9851a2270a
* Version Independent ID: d1ef1f43-00e2-b46f-4f38-6274a34f07f6
* Content: [Migrate a Windows Forms app to .NET 5 - Windows Forms .NET](https://learn.microsoft.com/en-us/dotnet/desktop/winforms/migration/?view=netdesktop-6.0)
* Content Source: [dotnet-desktop-guide/net/winforms/migration/index.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/net/winforms/migration/index.md)
* Product: **dotnet-desktop**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

---
[Associated WorkItem - 48582](https://dev.azure.com/msft-skilling/Content/_workitems/edit/48582)

**Comment by adegeo** [comment]
Thank you for pointing that out. It looks like it should have been a numbered section.
