### ISSUE TITLE
declaration event PropertyChangedEventHandler needs change

### ISSUE THREAD

**Issue by soba-noodle** [dotnet/docs-desktop#1548]
public event PropertyChangedEventHandler PropertyChanged; 

should be changed to a nullable declaration:

public event PropertyChangedEventHandler? PropertyChanged

to eliminate warning CS8612
Severity	Code	Description	Project	File	Line	Suppression State
Warning	CS8612	Nullability of reference types in type of 'event PropertyChangedEventHandler MainViewModel.PropertyChanged' doesn't match implicitly implemented member 'event PropertyChangedEventHandler? INotifyPropertyChanged.PropertyChanged'.	

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d0ad1362-3064-9816-47e7-7c29cd990173
* Version Independent ID: 08bd499b-178c-fb04-8980-41db01163b66
* Content: [How to: Implement Property Change Notification - WPF .NET Framework](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/data/how-to-implement-property-change-notification?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/data/how-to-implement-property-change-notification.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/data/how-to-implement-property-change-notification.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hi @soba-noodle Thanks for reporting this. This warning has to do with how your project is created. Starting with .NET 6, projects are configured for **nullable context**. This article, for .NET Framework, isn't aware of that context. Considering this change happened a year ago when .NET 6 was released, the .NET (non-framework) articles with code also suffer with this problem. This is something we'll have to address as a whole and not on an individual article.

Thank you though for reporting this.
