### ISSUE TITLE
How to list fonts on Linux

### ISSUE THREAD

**Issue by genifycom** [dotnet/docs-desktop#1550]
This page is completely useless in regards to .NET 6 and Linux.

Many of the previous approaches no longer work due to deprecation of libraries for Windows only.

Please provide a DotNet 6 and 7 approach that actually works!
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f3ba70d5-1325-5411-c21b-c6eee5963384
* Version Independent ID: 427155f8-6eed-acde-075b-6d894ba6f25f
* Content: [How to: Enumerate Installed Fonts - Windows Forms .NET Framework](https://learn.microsoft.com/en-us/dotnet/desktop/winforms/advanced/how-to-enumerate-installed-fonts?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/winforms/advanced/how-to-enumerate-installed-fonts.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/winforms/advanced/how-to-enumerate-installed-fonts.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Sorry, all of the content in this doc-space is tied to a Windows-only desktop technology, such as WinForms and WPF. Those are the technologies that contain the APIs to do thing with fonts.

You probably need to:

1. Find a library someone else has written that does this for you, such as on NuGet. (maybe an image manipulation library, or a drawing library, has an API to do it?)
2. Find a github repo with some code that's doing this.
3. Look through the Linux distro documentation to figure out what API calls you would have to make and then [code native PInvoke interfaces to those APIs](https://learn.microsoft.com/en-us/dotnet/standard/native-interop/)
