### ISSUE TITLE
Don't recommend BinaryFormatter

### ISSUE THREAD

**Issue by gewarren** [dotnet/docs-desktop#1551]
### Type of issue

Outdated article

### Description

BinaryFormatter is unsafe to use. This article shouldn't recommend using it and should add a caution block similar to https://learn.microsoft.com/en-us/dotnet/standard/serialization/binary-serialization.

Related to dotnet/docs#32568.

### Page URL

https://learn.microsoft.com/en-us/dotnet/desktop/wpf/advanced/application-startup-time?view=netframeworkdesktop-4.8

### Content source URL

https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/advanced/application-startup-time.md

### Document Version Independent Id

c7e42d2e-6ad7-4d68-d778-879698cac362

### Article author

@adegeo

---
[Associated WorkItem - 330109](https://dev.azure.com/msft-skilling/Content/_workitems/edit/330109)

**Comment by eriawan** [comment]
@gewarren 

I'm quite curious about this issue. Now that BinaryFormatter is deleted in .NET 9.0, should we also remove the description section about BinaryFormatter in the Application Startup time documentation in the original issue?

**Comment by gewarren** [comment]
@jeffhandley Not sure if you were aware of [this section](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/advanced/application-startup-time?view=netframeworkdesktop-4.8#use-the-binaryformatter-class-for-serialization), but we should either revise it or remove it with high priority, I would think.
