### ISSUE TITLE
Please include information on how to include and reference ViewBox elements in a WPF app

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/docs-desktop#1554]
Hi,

Please updated the attached page so that includes recommendation on how to include and reference ViewBox element XAML files in a WPF app.
For example, in [this](https://learn.microsoft.com/en-us/visualstudio/extensibility/ux-guidelines/images-and-icons-for-visual-studio?view=vs-2022) page, the VS Image Gallery is explained. The gallery includes VS icons in XAML format.

However, there's no guidance and recommendations on how to include those images in a WPF app, please update the docs to demonstrate that.

Here are some relevant questions on SO and MSDN:
- [How to include raw xaml file which is not a resource?](https://stackoverflow.com/a/69026704/75500)
- [How to use a ViewBox as a Resource](https://social.msdn.microsoft.com/Forums/vstudio/en-US/57cc8e51-d358-4c06-b182-a203f1beee6a/how-to-use-a-viewbox-as-a-ressource?forum=wpf)
- [Embed XAML file with ViewBox as a Resource](https://stackoverflow.com/a/58031553/75500)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a67c2159-b497-7f30-59d2-e9f4261f7bc7
* Version Independent ID: f7b9dc91-11d5-9431-8e54-0e8af8a826c7
* Content: [Pack URIs - WPF .NET Framework](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/app-development/pack-uris-in-wpf?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/app-development/pack-uris-in-wpf.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/app-development/pack-uris-in-wpf.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello @weitzhandler I'm sorry but I can't seem to figure out the link between what you're talking about and the PackURI article. This article isn't describing how to design resources, it's describing how to reference them, so it doesn't sound like an appropriate place for this suggestion.

But I may be misunderstanding your suggestion. Can you please clarify what's the exact problem you encounter, if you found a solution to fix it, and where specifically you would like it documented?
