### ISSUE TITLE
"UIElementCollection object element" reference is erroneous

### ISSUE THREAD

**Issue by BruceHaley** [dotnet/docs-desktop#1556]
The following words appear to be outdated/inapplicable:

"and that is why the [UIElementCollection](https://learn.microsoft.com/en-us/dotnet/api/system.windows.controls.uielementcollection) object element is shown commented out"

There is no UIElementCollection object element shown commented out.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 41391f13-7c61-97ac-e16e-ca1f280d79f6
* Version Independent ID: 12ab183d-74fa-e353-9761-fb5edc553e40
* Content: [XAML overview - WPF .NET](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/xaml/?view=netdesktop-6.0)
* Content Source: [dotnet-desktop-guide/net/wpf/xaml/index.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/net/wpf/xaml/index.md)
* Product: **dotnet-desktop**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

---
[Associated WorkItem - 70437](https://dev.azure.com/msft-skilling/Content/_workitems/edit/70437)

**Comment by adegeo** [comment]
Hi. Looks like in porting the code over I didn't realize what the commented out XAML was in the original source, so I probably removed it. I'll add it back in.

```xml
    <!--<UIElementCollection>-->
    <Button>First Button</Button>
    <Button>Second Button</Button>
    <!--</UIElementCollection>-->
```
