### ISSUE TITLE
Is the code snippet in the section "Opting out of individual high DPI features" up to date?

### ISSUE THREAD

**Issue by jmoralesv** [dotnet/docs-desktop#1559]
[Enter feedback here]
Hello Microsoft team,
I wanted to ask you if the section "Opting out of individual high DPI features" is correct and up to date. I'm currently working on updating a .NET Framework Windows Forms app to support high DPI monitors, and found something that is contradictory in that section.

I was checking the link at the bottom of that section, "For a list of individual keys and their values, see [Windows Forms Add Configuration Element](https://learn.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/winforms/windows-forms-add-configuration-element)". When comparing the contents of the attributes available list there with the code snippet in this section, I noticed that the `<System.Windows.Forms.ApplicationConfigurationSection>` is something that goes inside of the `<configuration>` element in an app.config file.

However, the code snippet you have here in this section shows `<compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">` as the parent element, which is available in a manifest file (app.manifest), not in an app.config file.

This also goes against what a previous code snippet shows in the bullet "Enable per-monitor DPI awareness in the app.config file" in the section "Configuring your Windows Forms app for high DPI support", where the `<System.Windows.Forms.ApplicationConfigurationSection>` element is displayed correctly inside of a `<configuration>` element.

If this is wrong, and I think it is, could you please update the code snippet for that section? So it doesn't lead to confusion to other readers and developers.

Thanks!
Jorge

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 67438c9c-fecf-d5df-d381-93b519929711
* Version Independent ID: f1980646-43a3-6ecb-88cd-7dd2fab5c2ce
* Content: [High DPI support - Windows Forms .NET Framework](https://learn.microsoft.com/en-us/dotnet/desktop/winforms/high-dpi-support-in-windows-forms?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/winforms/high-dpi-support-in-windows-forms.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/winforms/high-dpi-support-in-windows-forms.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

---
[Associated WorkItem - 63087](https://dev.azure.com/msft-skilling/Content/_workitems/edit/63087)

**Comment by adegeo** [comment]
Hi @jmoralesv I'm not sure. I'll have to investigate. I'm currently working on updating things to .NET 7 so I think I can check this out this week.

**Comment by jmoralesv** [comment]
Hi @adegeo thank you very much!
