### ISSUE TITLE
Template references undefined "MenuScrollButton" style

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/docs-desktop#1560]
There are two `RepeatButton` objects in this document with `{StaticResource MenuScrollButton}`, yet nothing in this document defines what `MenuScrollButton` actually is which means these styles/templates won't run correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0a19972d-68c2-fdcb-9ee2-34b9be6577be
* Version Independent ID: 39ab460f-20e6-9997-2f83-1fed12e4347d
* Content: [Menu Styles and Templates - WPF .NET Framework](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/controls/menu-styles-and-templates?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/controls/menu-styles-and-templates.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/controls/menu-styles-and-templates.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

---
[Associated WorkItem - 70441](https://dev.azure.com/msft-skilling/Content/_workitems/edit/70441)

**Comment by drewnoakes** [comment]
Actually it looks like the content is here, but is not included correctly in the document:

https://github.com/dotnet/docs-desktop/blob/215857b51cbaf5ab8cc11d2f0207c8a4c7e5a6aa/dotnet-desktop-guide/samples/snippets/csharp/VS_Snippets_Wpf/ControlTemplateExamples/CS/resources/menu.xaml#LL94-L157C11

**Comment by drewnoakes** [comment]
Actually `MenuPopupBrush` is also referenced in a few places, but isn't defined anywhere as far as I can tell.

**Comment by adegeo** [comment]
Thanks. I'll investigate how to update this page. I'm not sure where these templates came from originally. I'll see what I can do to update them to the latest. I'm unsure why you wouldn't just use the XAML editor function of generate a template which (I think???) generates a copy of the existing template used by WPF?
