### ISSUE TITLE
getting there

### ISSUE THREAD

**Issue by edthehorse** [dotnet/docs-desktop#1570]
At last an effort at least to teach by simple example

Lots of trees for the bits of wood tho

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5bbf3b44-d30c-f80e-de53-830a309343b9
* Version Independent ID: 7a6ca3f1-31e9-9cfd-0469-c477e8888233
* Content: [Storyboards Overview - WPF .NET Framework](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/graphics-multimedia/storyboards-overview?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/graphics-multimedia/storyboards-overview.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/graphics-multimedia/storyboards-overview.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello. I'm trying to guess your intent of this message, which is to really request more guided tutorials to teach the fundamentals of WPF? 😺

**Comment by edthehorse** [comment]
Sure Andy

Ill try to find time to take a closer look (Im abroad atm) and be a bit 
more constructive :-)

Regards

Ed

On 07/02/2023 16:09, Andy (Steve) De George wrote:

> Hello. I'm trying to guess your intent of this message, which is to 
> really request more guided tutorials to teach the fundamentals of WPF? 
> 😺
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/dotnet/docs-desktop/issues/1570#issuecomment-1421028368
[2]

**Comment by adegeo** [comment]
Closing due to lack of response. Please feel free to add more info.
