### ISSUE TITLE
Provided style and template doesn't work well with ScrollViewer (Default template works fine and as intended)

### ISSUE THREAD

**Issue by eulerleibniz** [dotnet/docs-desktop#1571]
I need to show a ScrollViewer inside the Expander and I can do it using the default Expander control with no problem. This template, however, sets the size of the Expander as the Content which is ScrollViewer and that makes ScrollViewer useless. Note that I can not hardcode the size of the ScrollViewer by hand as it defeats the purpose of letting the layout manager decide its size ( the default Expander Control does this perfectly). 

    <Grid>
        <Expander Margin="10"
                  ExpandDirection="Right"
                  HorizontalAlignment="Left">

            <ScrollViewer ScrollViewer.CanContentScroll="True">
                <StackPanel Orientation="Vertical">
                    
                    <Image Source="Image 1.jpg" />
                    <Image Source="Image 1.jpg" />
                    <Image Source="Image 1.jpg" />
                    <Image Source="Image 1.jpg" />
                    <Image Source="Image 1.jpg" />
                    <Image Source="Image 1.jpg" />
                    <Image Source="Image 1.jpg" />
                    <Image Source="Image 1.jpg" />
                </StackPanel>
            </ScrollViewer>
        </Expander>

    </Grid>

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bdb9feb2-67b1-f850-9acb-38f05f9ce5f1
* Version Independent ID: 1ad823ca-dbdf-a145-0265-0cf29056ec98
* Content: [Expander Styles and Templates - WPF .NET Framework](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/controls/expander-styles-and-templates?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/controls/expander-styles-and-templates.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/controls/expander-styles-and-templates.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

---
[Associated WorkItem - 70434](https://dev.azure.com/msft-skilling/Content/_workitems/edit/70434)

**Comment by adegeo** [comment]
Generally these issue come from the template being really out of date. I'm unsure where these templates came from originally. I'll do my best to find an updated version and update the article.
