### ISSUE TITLE
A picture or video would be nice considering this example code wont work without a bunch of modifications...

### ISSUE THREAD

**Issue by StingyJack** [dotnet/docs-desktop#1586]
... so we can at least see if the thing we hack together based on this code looks like you expect it to look.

Please make the XAML (Page) to be consistent with the c# (Window)

Its also not clear that the two blocks of code should be used as one or the other, not both.  Where does the c# code go in a blank WPF app?

The c# code as it is produces 25 compiler errors.  And thats not counting the runtime errors because the smiley png does not exist anywhere.
![image](https://user-images.githubusercontent.com/15381181/221334097-f8d71879-a112-41f4-affa-ee2337810baa.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2d210673-78b4-3eb7-d949-3fdc492c0caa
* Version Independent ID: 55957ba3-8779-5965-804c-17849e3513df
* Content: [How to: Choose Between StackPanel and DockPanel - WPF .NET Framework](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/controls/how-to-choose-between-stackpanel-and-dockpanel?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/controls/how-to-choose-between-stackpanel-and-dockpanel.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/controls/how-to-choose-between-stackpanel-and-dockpanel.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

---
[Associated WorkItem - 69674](https://dev.azure.com/msft-skilling/Content/_workitems/edit/69674)

**Comment by adegeo** [comment]
Yuck... The C# code should just be removed
