### ISSUE TITLE
Possibly garbled wording in Section "Command Library"

### ISSUE THREAD

**Issue by holmerr** [dotnet/docs-desktop#1592]
The last line of the Section "Command Library" reads:

When you reference commands in the various command libraries using WPF WPF XAML processor references at load time).

It's difficult to parse this sentence.  The unmatched closing parenthesis suggests that an editing mistake occurred.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cf18098f-ff52-349a-4894-1b8ae3bdefd7
* Version Independent ID: e7732035-e185-777d-3396-e44b0d507322
* Content: [Commanding Overview - WPF .NET Framework](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/advanced/commanding-overview?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/advanced/commanding-overview.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/advanced/commanding-overview.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

---
[Associated WorkItem - 70319](https://dev.azure.com/msft-skilling/Content/_workitems/edit/70319)

**Comment by adegeo** [comment]
Thank you for opening this issue. I'll get this fixed up.

**Comment by holmerr** [comment]
Many thanks for the fine article (and for the fix).

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Andy (Steve) De George ***@***.***>
Sent: Wednesday, March 15, 2023 8:15:11 PM
To: dotnet/docs-desktop ***@***.***>
Cc: Randall Holmes ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [dotnet/docs-desktop] Possibly garbled wording in Section "Command Library" (Issue #1592)

CAUTION: Email Originated Outside of Auburn.

Closed #1592<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fdocs-desktop%2Fissues%2F1592&data=05%7C01%7Cholmerr%40auburn.edu%7Ca8ef7e2eb5b24eeea20c08db25bbe53d%7Cccb6deedbd294b388979d72780f62d3b%7C1%7C0%7C638145261178052798%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=BcHNgjA4Q8A5Ve1ooAo7k0drmG9YnojXbfymw5PT%2BEg%3D&reserved=0> as completed via #1596<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fdocs-desktop%2Fpull%2F1596&data=05%7C01%7Cholmerr%40auburn.edu%7Ca8ef7e2eb5b24eeea20c08db25bbe53d%7Cccb6deedbd294b388979d72780f62d3b%7C1%7C0%7C638145261178052798%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=GJdX6dH%2BU35knFnKtKElIEZieQxhREC%2FjV%2BBOvYcYfs%3D&reserved=0>.
