### ISSUE TITLE
Bug in code?

### ISSUE THREAD

**Issue by einarstokke** [dotnet/docs-desktop#160]
Possible bug:
When the OnDrop event is triggered, the statement `e.Data.GetDataPresent(DataFormats.StringFormat)` evaluates to false, so the remaining code is never executed, and the circle never turns green.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23f605d0-6326-17d5-3087-4f6ef96ab9bb
* Version Independent ID: 10411c7d-3586-4904-6d4f-79e84f0c9b98
* Content: [Walkthrough: Enabling Drag and Drop on a User Control - WPF .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/walkthrough-enabling-drag-and-drop-on-a-user-control?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/advanced/walkthrough-enabling-drag-and-drop-on-a-user-control.md](https://github.com/dotnet/docs-desktop/blob/master/dotnet-desktop-guide/framework/wpf/advanced/walkthrough-enabling-drag-and-drop-on-a-user-control.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for reporting this. It seems it needs to check for the `Text` format and not `StringFormat`

**Comment by adegeo** [comment]
Hmmm I just did some more testing and this works correctly on .NET Framework. It's not working on .NET 5 though. I'm going to close this issue and ping the wpf folks in their repo about this regression.
