### ISSUE TITLE
Suggesting to mention UWP in this documentation highlighting limitations due to airspace issue

### ISSUE THREAD

**Issue by geocine** [dotnet/docs-desktop#1601]
### Type of issue

Missing information

### Description

May you also include and mention UWP in this documentation. Highlight limitations due to airspace issue similar to https://learn.microsoft.com/en-us/windows/apps/desktop/modernize/visual-layer-in-desktop-apps

### Page URL

https://learn.microsoft.com/en-us/dotnet/desktop/wpf/advanced/technology-regions-overview?view=netframeworkdesktop-4.8

### Content source URL

https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/advanced/technology-regions-overview.md

### Document Version Independent Id

b0463b1e-ee77-ca73-fccb-1bca3336d4d9

### Article author

@adegeo

**Comment by adegeo** [comment]
Hello, thank you for this suggestion. Right now this is out of the scope for the article. If this article gets updated for .NET 6/7/8 we can look at adding this. Otherwise, I'll leave this issue up to the community to handle if they feel like it's a good addition.
