### ISSUE TITLE
The description provided for Orientation property of "StackPanel2" in the example is wrong.  

### ISSUE THREAD

**Issue by pradeepkumar-devaraj** [dotnet/docs-desktop#1606]
The "StackPanel2" defined in the code has Orientation property assigned to "Vertical". But the TextBlock used to describe the StatckPanel orientation mentions "StackPanel.Orientation="Horizontal" which is wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a01663b5-c69f-20d0-5d02-e216bd54565f
* Version Independent ID: a13e9d64-18ca-dc0e-0afe-211d921a98f6
* Content: [Alignment, Margins, and Padding Overview - WPF .NET Framework](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/advanced/alignment-margins-and-padding-overview?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/advanced/alignment-margins-and-padding-overview.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/advanced/alignment-margins-and-padding-overview.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for opening this issue. I'll add it to the backlog. If you would like to contribute, you can submit a fix by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!

**Comment by kgrems** [comment]
This is my first ever "Help Wanted" issue and my first contribution to open source in general!  I submitted a pull request.
