### ISSUE TITLE
Excellent. Did help me a lot.

### ISSUE THREAD

**Issue by Avrohom** [dotnet/docs-desktop#1610]
Excellent. Did help me a lot.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 09a6c25d-0ac9-a764-1df5-eea8ede79421
* Version Independent ID: b7506d5e-be24-81aa-80b8-9efffb5b3e8b
* Content: [How to create a custom routed event - WPF .NET](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/events/how-to-create-a-custom-routed-event?view=netdesktop-7.0)
* Content Source: [dotnet-desktop-guide/net/wpf/events/how-to-create-a-custom-routed-event.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/net/wpf/events/how-to-create-a-custom-routed-event.md)
* Product: **dotnet-desktop**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
I'm glad it helped!
