### ISSUE TITLE
Watermark instructions "work" until text is cleared.

### ISSUE THREAD

**Issue by digitalsleuth** [dotnet/docs-desktop#1616]
While following the steps on this particular process, I found the "resource" link, and added the image as a resource (though it's not present on this page). I placed the files in the correct location (relative URI to my Images\ folder in the XAML), and launched the debug process. Everything looks good, I can see the background it disappears when I start typing.

However, when I clear the box (backspace until I get to the beginning) I get an IO.FileNotFoundException error: 
```
System.IO.FileNotFoundException: 'Could not find file 'O:\Projects\<project_path>\bin\x64\Debug\net6.0-windows10.0.17763.0\bg.gif'.'
```
I can attest that the file does **NOT** exist in the "bin\x64\Debug" folder because, well simply put, that's not my project folder. It's in the "Images\" folder of the project, and the debug launches properly, with the background image showing.

When building a self-contained executable, I've tested this and it crashes after clearing the box.

The only differences between my project and this example is that I'm using a `Window` and not a `Page`, and I'm not using a `StackPanel` in my XAML.

Perhaps something is missing in this documentation, or this is an actual issue.

I found the solution was to include 'pack://application:' in the Uri and modify the UriKind to Absolute, as identified in [this StackOverflow post](https://stackoverflow.com/questions/19174172/wpf-directory-not-found-exception-and-presentationcore-pdb-not-loaded).

This will work for the debug process, and confirmed working on a Self-Contained executable (executable moved to a Virtual Machine without ANY of the build assets and it worked as desired).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 595479dc-fe01-620f-aa97-28c6fdf1f42f
* Version Independent ID: a9bd8e58-c020-454f-a39b-4f19c6224627
* Content: [How to: Add a Watermark to a TextBox - WPF .NET Framework](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/controls/how-to-add-a-watermark-to-a-textbox?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/controls/how-to-add-a-watermark-to-a-textbox.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/controls/how-to-add-a-watermark-to-a-textbox.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
As you attested, the article doesn't seem to cover actually adding the image to your project and configuring it in such a way that the loader can resolve the path to the image. I wonder, though, if it would be easier to just configure the textbox with the image in the XAML as is being done, but then have the event locate the image and hide it or show it based on the text in the textbox. This avoids the loading code all together.

**Comment by adegeo** [comment]
In general, this way of setting a watermark just isn't good. If you use any other color on the background of the parent control, it will bleed through. The image is set to a specific color which could then clash with any theme you end up using too. However, a much easier way is to simply add the watermark image a resource and reference it. This simplifies the XAML and the code. I'll follow up with an update to the article.
