### ISSUE TITLE
Code example and article do not match

### ISSUE THREAD

**Issue by Onman99** [dotnet/docs-desktop#1617]
The code provided and the text explaining the code do not match. Specifically the first block of XAML code.
In the code is the item 
`<MeshGeometry3D 
              Positions="-1 -1 0  1 -1 0  -1 1 0  1 1 0"
              Normals="0 0 1  0 0 1  0 0 1  0 0 1"
              TextureCoordinates="0 1  1 1  0 0  1 0   "
              TriangleIndices="0 1 2  1 3 2" />`

And in the text immediately below it describes how 8 vertices are defined to define a cube-shaped mesh. It also says "the first three vertices specified by the Positions list are (1,1,0), (0,1,0), and (0,0,0)."
Please review this text in relation to the code block as it is highly confusing for an absolute beginner (like me) in the 3D world.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4aa7e5c8-ed8e-5b1c-288f-f13edb728bee
* Version Independent ID: d329915f-a054-b423-adf5-e161902a02dd
* Content: [3D Graphics Overview - WPF .NET Framework](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/graphics-multimedia/3-d-graphics-overview?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/graphics-multimedia/3-d-graphics-overview.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/graphics-multimedia/3-d-graphics-overview.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

---
[Associated WorkItem - 85577](https://dev.azure.com/msft-skilling/Content/_workitems/edit/85577)

**Comment by adegeo** [comment]
You are correct, the description doesn't match the code. Without running the example and just looking at it, it looks like it's describing a cube face, not a whole cube. I'll add this to the next sprint.
