### ISSUE TITLE
example don't validate in Visual studio

### ISSUE THREAD

**Issue by jackfruh** [dotnet/docs-desktop#1619]
[Enter feedback here]
Please fix these examples
memoryImage is not defined anywhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 586c8a82-ecb3-f8f9-dea9-b0b6a344210e
* Version Independent ID: ce7d22a1-32d6-e117-6cc6-3dc94edadf16
* Content: [How to print a Windows Form - Windows Forms .NET](https://learn.microsoft.com/en-us/dotnet/desktop/winforms/printing/how-to-print-windows-form?view=netdesktop-7.0)
* Content Source: [dotnet-desktop-guide/net/winforms/printing/how-to-print-windows-form.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/net/winforms/printing/how-to-print-windows-form.md)
* Product: **dotnet-desktop**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello. Looking at the code `memoryImage` is declared:

![image](https://user-images.githubusercontent.com/67293991/232605752-b350ec68-7695-4654-a4af-ac8006b90b51.png)

Can you explain more about your problem? Perhaps share your code?
