### ISSUE TITLE
Object requirements

### ISSUE THREAD

**Issue by Rose-Kenner-Biamp** [dotnet/docs-desktop#1625]
[Enter feedback here]

This does not work at all. I suspect that 'Object' has requirements, such as implementing INotifyProperty; but none of the help sites mention this. I have a simple Object, basically a structure with 5 Properties, and the bound form components are not notified when the data changes and no BindingSource events fire.

Can you expand on what the Object is required to implement?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e890ee3b-412f-e524-f93a-28e7dad1faa0
* Version Independent ID: ee48495d-3a11-1de2-0ed1-71e959630adc
* Content: [Bind Control to a Type Using the Designer - Windows Forms .NET Framework](https://learn.microsoft.com/en-us/dotnet/desktop/winforms/controls/how-to-bind-a-windows-forms-control-to-a-type-using-the-designer?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/winforms/controls/how-to-bind-a-windows-forms-control-to-a-type-using-the-designer.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/winforms/controls/how-to-bind-a-windows-forms-control-to-a-type-using-the-designer.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hi @Rose-Kenner-Biamp I'm assuming you're using Windows Forms for .NET 6 or 7? This was written for .NET Framework, and the data binding docs haven't been written for .NET yet. AFAIK there aren't any non-working parts of databinding in .NET winforms. There is a [blog post](https://devblogs.microsoft.com/dotnet/databinding-with-the-oop-windows-forms-designer/) that discusses some of the new .NET 6 features, but .NET 7 goes even further if you enable previewfeatures, which [adds WPF-style command binding and base classes too](https://devblogs.microsoft.com/dotnet/winforms-cross-platform-dotnet-maui-command-binding/).

Personally, I've never been able to get databinding working well in Windows Forms. Perhaps @KlausLoeffelmann can help?

**Comment by Rose-Kenner-Biamp** [comment]
I can do it by hand.

Following any common help like https://learn.microsoft.com/en-us/dotnet/desktop/winforms/how-to-implement-the-inotifypropertychanged-interface?view=netframeworkdesktop-4.8

The object must 
* derive from INotifyPropertyChanged
* add an event public event PropertyChangedEventHandler PropertyChanged;
* implement NotifyPropertyChanged like this
        private void NotifyPropertyChanged([CallerMemberName]  String propertyName = "")
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
* add using System.ComponentModel (for [CallerMemberName] recognition)
* each property must now add a private backing variable e.g. for public Details there must be a member field details.
* each property {get;set;} must be converted to 
	public { get => details; 
	            set { if (value != this.details) 
	                   { this.details = value;
        	             NotifyPropertyChanged();
                           }
                         }
* the form must subscribe to BindingSource_ListChanged which must have this code
	if (e.ListChangedType == ListChangedType.ItemChanged)
	{ 
            if (e.PropertyDescriptor.Name == "Details")
	    { 
               text1.Text = (myBindingSource.DataSource as myBindingType)?.Details;
            }
         }

Ok, now it is bound.

But this is a lot of boilerplate code to write by hand - I thought there was a more convenient way to do databinding from an object.

**Comment by adegeo** [comment]
I'm going to close this because I don't think there is anything to do on the old doc

**Comment by Rose-Kenner-Biamp** [comment]
I suppose "Implement NotifyPropery" covers what must be done.
