### ISSUE TITLE
OS Version number doesn't seem right

### ISSUE THREAD

**Issue by scott-smith-immersedvr** [dotnet/docs-desktop#1626]
Based upon some checking I did in the C# Interactive window of Visual Studio, the following example code from this page won't work as expected:

> // Create a reference to the OS version of Windows 10 Creators Update.
> Version OsMinVersion = new Version(10, 0, 15063, 0);
> . . .
> // Compare the current version to the minimum required version.
> Console.WriteLine(Environment.OSVersion.Version.CompareTo(OsMinVersion));

On **both** my Windows 10 and 11 machines, `Environment.OSVersion.Version` yields the same result:
```
> Environment.OSVersion.Version
[6.2.9200.0]
```
I don't know why they're the same.

Meanwhile, looking at the **System Information** app, I see the following on the two different machines:

_Windows 10:_
- OS Name: **Microsoft Windows 10 Enterprise**
- Version: **10.0.19044 Build 19044**

_Windows 11:_
- OS Name: **Microsoft Windows 11 Home**
- Version: **10.0.22000 Build 22000**

I'm not sure where System Information is getting it's display values, but it seems clear that .NET's `Environment.OSVersion` deals with a different (internal) OS number. Thus it appears that the comparison of versions shown in the example code won't work as expected.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 67438c9c-fecf-d5df-d381-93b519929711
* Version Independent ID: f1980646-43a3-6ecb-88cd-7dd2fab5c2ce
* Content: [High DPI support - Windows Forms .NET Framework](https://learn.microsoft.com/en-us/dotnet/desktop/winforms/high-dpi-support-in-windows-forms?view=netframeworkdesktop-4.8&source=docs)
* Content Source: [dotnet-desktop-guide/framework/winforms/high-dpi-support-in-windows-forms.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/winforms/high-dpi-support-in-windows-forms.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello @scott-smith-immersedvr If you're running on .NET Framework, the OSVersion operated differently for a time. You need to enable "Windows 10" support for the app. This is detailed in the [Configuring your Windows Forms app for high DPI support](https://learn.microsoft.com/en-us/dotnet/desktop/winforms/high-dpi-support-in-windows-forms?view=netframeworkdesktop-4.8&source=docs#configuring-your-windows-forms-app-for-high-dpi-support) section. Add the app manifest section and it will report the correct version.

If you're running on .NET (not Framework) then OSVersion reports correctly and you also don't need to enable compatibility.

I'll close this issue as I think it should solve your problem. Please let me know either way.
