### ISSUE TITLE
Resources code sample incorrect

### ISSUE THREAD

**Issue by jg67** [dotnet/docs-desktop#163]
In the Resource and settings section the text says:
       Notice that the Include was changed to Update on both the <Compile> and <EmbeddedResource> elements

But the code sample following still has the EmbeddedResource as "Incluide=" instead of "Update="
        <EmbeddedResource Include="Properties\Resources.resx">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98778ad1-6c20-6310-e4bc-9d9851a2270a
* Version Independent ID: d1ef1f43-00e2-b46f-4f38-6274a34f07f6
* Content: [Migrate a Windows Forms app to .NET 5 - Windows Forms .NET](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/migration/?view=netdesktop-5.0)
* Content Source: [dotnet-desktop-guide/net/winforms/migration/index.md](https://github.com/dotnet/docs-desktop/blob/master/dotnet-desktop-guide/net/winforms/migration/index.md)
* Product: **dotnet-desktop**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for reporting this. I'll edit the article. I was making changes in here regarding those specific settings and I must have missed something.
