### ISSUE TITLE
Minor typo on wpf hosting walkthrough page

### ISSUE THREAD

**Issue by wyckster** [dotnet/docs-desktop#1633]
`itto` is a typo.  It should probably say `it to`

> The `Form1_Load` event handler creates an instance of `UserControl1` and adds **itto** the [ElementHost](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.integration.elementhost) control's ...

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 04fff519-3d2a-4756-1fc7-41ba0cc98621
* Version Independent ID: e26e8075-7880-39b9-9c87-8f0b871c03dc
* Content: [Host 3D WPF Composite Control in Windows Forms](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/advanced/walkthrough-hosting-a-3-d-wpf-composite-control-in-windows-forms?view=netframeworkdesktop-4.8&viewFallbackFrom=netdesktop-7.0)
* Content Source: [dotnet-desktop-guide/framework/wpf/advanced/walkthrough-hosting-a-3-d-wpf-composite-control-in-windows-forms.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/advanced/walkthrough-hosting-a-3-d-wpf-composite-control-in-windows-forms.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for reporting. I've made the fix.
