### ISSUE TITLE
Funny how the listview doc page doesn't actually show you what a listview is

### ISSUE THREAD

**Issue by TimLovellSmith** [dotnet/docs-desktop#1635]
[Enter feedback here]
Just thinking out loud here but... wouldn't the simplest way to explain to everyone what the listview control class is, to be to show some kind of sketch or screenshot of what makes a listview, a listview?

Obviously specific screenshots go out of date, and control are customizable to look and behave different, but when it comes to explaining the default behavior I think a picture is worth a thousand words.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3f8d2d3b-69d3-dbc7-2a66-6d1df6910aa5
* Version Independent ID: e287f575-c2d8-5661-af8a-908893298679
* Content: [ListView Control - Windows Forms .NET Framework](https://learn.microsoft.com/en-us/dotnet/desktop/winforms/controls/listview-control-windows-forms?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/winforms/controls/listview-control-windows-forms.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/winforms/controls/listview-control-windows-forms.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hi @TimLovellSmith thank you for this suggestion. This is something we've noted in other issues, and we'll work on this as we port the docs to the .NET area and out of .NET Framework.
