### ISSUE TITLE
Page is lopsided

### ISSUE THREAD

**Issue by ChitownRonnie** [dotnet/docs-desktop#1636]
[Enter feedback here]  The page provides C# code but VB code solution is very differemt

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 097f0935-4e55-891d-5a27-fb898d63d8f3
* Version Independent ID: cce4458e-b162-09f3-48ea-b4481aa4c183
* Content: [Create a new app with Visual Studio tutorial - WPF .NET](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/get-started/create-app-visual-studio?view=netdesktop-7.0)
* Content Source: [dotnet-desktop-guide/net/wpf/get-started/create-app-visual-studio.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/net/wpf/get-started/create-app-visual-studio.md)
* Product: **dotnet-desktop**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hi @ChitownRonnie can you elaborate on what differences you're seeing? If it's related to how the XAML class is declared, there isn't much I can do about that except add a note at the first occurrence of XAML that points this out.
