### ISSUE TITLE
Missing screenshots

### ISSUE THREAD

**Issue by DiskJunky** [dotnet/docs-desktop#1639]
Without supporting screenshots to show/demonstrate the functionality, the bar for understanding the page content is quite high. Someone essentially has to create a test project and copy/paste the code to see which functionality they're looking for.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 09e57514-4a5b-a11a-e6fb-cd6efc96d004
* Version Independent ID: f853a44e-3ea2-0379-e60b-c16aa3f47d51
* Content: [How to: Horizontally or Vertically Align Content in a StackPanel - WPF .NET Framework](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/controls/how-to-horizontally-or-vertically-align-content-in-a-stackpanel?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/controls/how-to-horizontally-or-vertically-align-content-in-a-stackpanel.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/controls/how-to-horizontally-or-vertically-align-content-in-a-stackpanel.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
@DiskJunky Thank you for the suggestion. We're going to be adding screenshots, where appropriate, as we port articles to the .NET docs area. We're not updating the old articles unless it's a critical bug. Sorry about that.
