### ISSUE TITLE
Common problem with all your documentation

### ISSUE THREAD

**Issue by micklord49** [dotnet/docs-desktop#164]
THis is true for all your code samples... WHY DO YOU LEAVE OUT THE USING? More often than not this leaves me searching for which Library I have to use... 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: baed064b-f762-0197-aea8-5597efea9eba
* Version Independent ID: a15d1fb8-485f-bd7a-7771-7cf8767fe735
* Content: [How to: Draw an Existing Bitmap to the Screen - Windows Forms .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/advanced/how-to-draw-an-existing-bitmap-to-the-screen?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/winforms/advanced/how-to-draw-an-existing-bitmap-to-the-screen.md](https://github.com/dotnet/docs-desktop/blob/master/dotnet-desktop-guide/framework/winforms/advanced/how-to-draw-an-existing-bitmap-to-the-screen.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello. Sorry for the inconvenience. This is a design decision we made because of the following reasons:

01. Usings/Imports adds extra code lines that require extra introduction and explanation.
01. The links in the article to the types (such as [Bitmap](https://docs.microsoft.com/en-us/dotnet/api/system.drawing.bitmap)) go to the API reference which instantly tells you which namespace and library:

    ![image](https://user-images.githubusercontent.com/67293991/103573730-94db1480-4e83-11eb-8f6c-b86c39cee448.png)

01. Modern versions of Visual Studio and other IDEs include tip bubbles that search for and import the correct namespaces.

    ![image](https://user-images.githubusercontent.com/67293991/103574169-52fe9e00-4e84-11eb-8dd3-6e09deb2add3.png)

However, newer tutorial content will generally always include the namespaces. And if the article is complex, the author may add the namespace, but at their discretion.

**Comment by micklord49** [comment]
The particular page I flagged, vs did not have a suggestion because it required a nuget package which was beyond vs to suggest...

The lack of a suggestion on the page as to what I needed to do led to quite a bit of extra searching which I feel could have been avoided if you have a policy of including just a little extra information on your part.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by adegeo** [comment]
@micklord49 Interesting, it shouldn't require any NuGet package. What package did you add?

**Comment by micklord49** [comment]
I was adding the imaging package for .net core which is standard in .net

**Comment by adegeo** [comment]
Did you first create a new Windows Forms app for .NET Core/5? That should add everything you need automatically, you shouldn't need to add any NuGet references.

**Comment by micklord49** [comment]
Nope, I was using it in an ASP project

**Comment by micklord49** [comment]
(I was using it to extract Exif information from an uploaded image - which had it's own problems because BitConverter.ToInt32 insisted on being Littlendian even though the asp.net application was running on a linux docker container and the image loader stored everything as Bigendian.

**Comment by adegeo** [comment]
Ahh, I see. The documentation is written for Windows Forms, which is why it doesn't need to really give you much setup.
