### ISSUE TITLE
No mention of PrintDocument control

### ISSUE THREAD

**Issue by KennyTK** [dotnet/docs-desktop#1642]
This code example also uses the PrintDocument control but makes no mention of it. I'd happily submit a PR but I'm not sure of the WPF equivalent.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 586c8a82-ecb3-f8f9-dea9-b0b6a344210e
* Version Independent ID: ce7d22a1-32d6-e117-6cc6-3dc94edadf16
* Content: [How to print a Windows Form - Windows Forms .NET](https://learn.microsoft.com/en-us/dotnet/desktop/winforms/printing/how-to-print-windows-form?view=netdesktop-7.0)
* Content Source: [dotnet-desktop-guide/net/winforms/printing/how-to-print-windows-form.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/net/winforms/printing/how-to-print-windows-form.md)
* Product: **dotnet-desktop**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
You're right, that is totally missing! I fyou would like to contribute, we're totally open to it. The WPF and WinForms docsets are evolving at different speeds, so don't worry about WPF if you're working in th WinForms area.

And I'm remembering correctly, WPF uses an entirely different printing API.

**Comment by KennyTK** [comment]
Planning to improve and submit a PR in the next few days. 😄
