### ISSUE TITLE
 error CS0103: The name 'Properties' does not exist in the current context

### ISSUE THREAD

**Issue by paul1923** [dotnet/docs-desktop#1644]
I'm building a .Net 6 C# WPF application, when trying to access Properties, as described on this page, I get a CS0103

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8bf63644-510d-8160-566f-af4b6a34e8bd
* Version Independent ID: 397693f7-4bdf-69a9-d5dc-bc2c50c4517d
* Content: [How To: Read Settings at Run Time With C# - Windows Forms .NET Framework](https://learn.microsoft.com/en-us/dotnet/desktop/winforms/advanced/how-to-read-settings-at-run-time-with-csharp?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/winforms/advanced/how-to-read-settings-at-run-time-with-csharp.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/winforms/advanced/how-to-read-settings-at-run-time-with-csharp.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hi @paul1923

It seems that the latest templates for .NET 6/7/8 don't include the settings file, you'll need to add it yourself.

1. In the **Solution Explorer** window of Visual Studio, create a folder in your project named `Properties`
2. Right click on `Properties` >`Add` > `New Item`
3. In the search box on the top right, put in `settings`
4. Most likely the last item in the results will be `Settings File`, select this
5. Set the name of the file to `Settings.settings` and press the `Add` button.

Now you'll have the settings file. Open it and add your settings.

This should fix your problem; I'll close this issue. Let me know if you need more help.
