### ISSUE TITLE
Flaw in drag&drop walkthrough for VB

### ISSUE THREAD

**Issue by Erbfl** [dotnet/docs-desktop#1656]
[Enter feedback here]

---Walkthrough code example doesn't work as expected in the following section of the page
>>>To process the dropped data
   1.  Open Circle.xaml.cs or Circle.xaml.vb.
   2.  Add the following [OnDrop](https://learn.microsoft.com/en-us/dotnet<<<

In particular, "If e.Data.GetDataPresent(DataFormats.StringFormat)" never returns true.
After changing this to "If e.Data.GetDataPresent(DataFormats.Text)" the Walkthrough works as expected, i.e. changes the colour of the Circle control to green.

/api/system.windows.uielement.ondrop) override to provide class handling for the [Drop](https://learn.microsoft.com/en-us/dotnet/api/system.windows.uielement.drop) event.
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 23f605d0-6326-17d5-3087-4f6ef96ab9bb
* Version Independent ID: 10411c7d-3586-4904-6d4f-79e84f0c9b98
* Content: [Walkthrough: Enabling Drag and Drop on a User Control - WPF .NET Framework](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/advanced/walkthrough-enabling-drag-and-drop-on-a-user-control?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/advanced/walkthrough-enabling-drag-and-drop-on-a-user-control.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/advanced/walkthrough-enabling-drag-and-drop-on-a-user-control.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello. Are you using .NET Framework or .NET 6/7?
