### ISSUE TITLE
window form background design

### ISSUE THREAD

**Issue by kaungkaung333333333** [dotnet/docs-desktop#1662]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e1780214-3e1b-d3db-0621-feee922687c2
* Version Independent ID: 19ae0cbc-a540-6c3b-9999-e59ffe32eeb7
* Content: [Set the Background of a Panel Using the Designer - Windows Forms .NET Framework](https://learn.microsoft.com/en-us/dotnet/desktop/winforms/controls/how-to-set-the-background-of-a-windows-forms-panel-using-the-designer?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/winforms/controls/how-to-set-the-background-of-a-windows-forms-panel-using-the-designer.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/winforms/controls/how-to-set-the-background-of-a-windows-forms-panel-using-the-designer.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hi @kaungkaung333333333 I'm not sure what issue you're trying to report. Can you please provide more information? Thanks!
