### ISSUE TITLE
typo?

### ISSUE THREAD

**Issue by zhiwang20** [dotnet/docs-desktop#1665]
x:Class="Names.MainWindow" instead of x:Class="Names.LayoutStep2"?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 097f0935-4e55-891d-5a27-fb898d63d8f3
* Version Independent ID: cce4458e-b162-09f3-48ea-b4481aa4c183
* Content: [Create a new app with Visual Studio tutorial - WPF .NET](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/get-started/create-app-visual-studio?view=netdesktop-7.0)
* Content Source: [dotnet-desktop-guide/net/wpf/get-started/create-app-visual-studio.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/net/wpf/get-started/create-app-visual-studio.md)
* Product: **dotnet-desktop**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for taking the time to report this.

The `LayoutStep2` is a side effect of the code snippet system that imports code during publish. I can't reuse the same class name to show the progression of before/after. I can hide that portion of code though, just showing the grid itself.
