### ISSUE TITLE
Remove Step 9

### ISSUE THREAD

**Issue by UTFDev** [dotnet/docs-desktop#1673]
Step 9 is both confusing and misleading.
The sentence is confusing because it doesn't make sense - you can't add code to a control!
It's also misleading because step 9 is not required to achieve an MDI window list menu item. Anyone coming to this page will be baffled by step 9, and please don't insult my intelligence again by tellng me how to create an event handler. I've been a developer for over 35 years and have been using VS since 2005.
I've created the project as described in the page (before you corrected the &New ommission) but without step 9 and it works fine.
Regards,

Mick.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b6f059cf-5b48-9964-7878-987b0e7af457
* Version Independent ID: 44d5fc14-e7fc-cd31-451c-b53aa4dd1e87
* Content: [How to: Create an MDI Window List with MenuStrip - Windows Forms .NET Framework](https://learn.microsoft.com/en-us/dotnet/desktop/winforms/controls/how-to-create-an-mdi-window-list-with-menustrip-windows-forms?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/winforms/controls/how-to-create-an-mdi-window-list-with-menustrip-windows-forms.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/winforms/controls/how-to-create-an-mdi-window-list-with-menustrip-windows-forms.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello again, I'll get this fixed up.

**Comment by UTFDev** [comment]
Hi Andy,

That page now reads a lot better. Thanks for taking the time to update it.

Regards,

Mick.
