### ISSUE TITLE
Code improvement in example of "WeatherComponent2"

### ISSUE THREAD

**Issue by HugoRoss** [dotnet/docs-desktop#1678]
I suggest to change the code in example of "WeatherComponent2" as follows:

old:

```
private void RaiseEvent(GetWeatherCompletedEventArgs e)
    {
        if (GetWeatherCompleted != null)
            GetWeatherCompleted(this, e);
    }

```

new:
```
private void RaiseEvent(GetWeatherCompletedEventArgs e)
    {
        GetWeatherCompleted?.Invoke(this, e);
    }
```

Reason: Safer (between the two accesses to `GetWeatherCompleted ` someone could unsubscribe and cause a `NullReferenceException`) and more compact syntax.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b0bc9d86-b893-7c9f-d832-3c3026f5278e
* Version Independent ID: 5d75b64a-62d1-b0f9-b8fd-c84f60318808
* Content: [Threading Model - WPF .NET Framework](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/advanced/threading-model?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/advanced/threading-model.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/advanced/threading-model.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

---
[Associated WorkItem - 153648](https://dev.azure.com/msft-skilling/Content/_workitems/edit/153648)

**Comment by adegeo** [comment]
Hello, thank you for the suggestion. You are correct, this is the preferred way to do it. However, at this moment, this is a low priority.

**Comment by adegeo** [comment]
Related to #1691
