### ISSUE TITLE
Accessing resouces in a separate assembly doesn't work as described

### ISSUE THREAD

**Issue by SetTrend** [dotnet/docs-desktop#168]
Following the instructions from below mentioned MS Docs page, I'm not able to access remote resources from an external assembly using [`ComponentResourceKey`](https://docs.microsoft.com/dotnet/api/system.windows.componentresourcekey).

The following line in `MainWindow.xaml` doesn't work: no background color is getting displayed:

```xml
<StackPanel Grid.Row="0" Background="{DynamicResource {ComponentResourceKey TypeInTargetAssembly={x:Type res:DummyForSharingResources}, ResourceId=TestBg}}"></StackPanel>
```

I [published a corresponding repository here](/SetTrend/Wpf-ResourceTest), containing my Visual Studio 2019 solution. It contains all the details.

What I did so far

- "Themes/generic.xaml" file created in supplemental assembly (`StylesAndResources`), filled with resources.
- `ThemeInfoAttribute` updated in application assembly to reference `ResourceDictionaryLocation.ExternalAssembly`.
- Dummy class created in `StylesAndResources` in order to be able to have a [`ComponentResourceKey`](https://docs.microsoft.com/dotnet/desktop/wpf/advanced/componentresourcekey-markup-extension) be generated.

So, I followed the docs completely, and still it doesn't work.

**What's wrong?**

I propose the `ComponentResourceKey`/theming documentation to be amended to provide a concise, working description - or to remove this information completely from the docs if `ComponentResourceKey` and theming is not supported by WPF anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 025a6256-5ca6-5e96-915d-1134d9e9dd43
* Version Independent ID: 0786699a-4732-2214-67e6-ca8b7dcd5864
* Content: [Control Authoring Overview - WPF .NET Framework](https://docs.microsoft.com/dotnet/desktop/wpf/controls/control-authoring-overview#defining-and-referencing-keys-for-theme-resources)
* Content Source: [dotnet-desktop-guide/framework/wpf/controls/control-authoring-overview.md](https://github.com/dotnet/docs-desktop/blob/master/dotnet-desktop-guide/framework/wpf/controls/control-authoring-overview.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello, I'll see if I can figure it out. Thank you for creating the repository with the code, that helps a bunch.

**Comment by SetTrend** [comment]
Hello, @adego, I just wanted to ask for a short follow-up. Did you by accident manage to have a look at this?

**Comment by adegeo** [comment]
Sorry for the delay. I couldn't get it working either.

@rladuca is there a known limitation with WPF .NET 5 in theming and referenced assemblies?

**Comment by adegeo** [comment]
I FIGURED IT OUT!

Your **StylesAndResources** project also needs the `ThemeInfo` attribute set, but it needs it set to `SourceAssembly`

```csharp
[assembly: ThemeInfo(
		ResourceDictionaryLocation.SourceAssembly,
		ResourceDictionaryLocation.SourceAssembly
)]
```

This makes it work. Even though it was working, I was able to (1) delete the _assemblyinfo.cs_ file from the main project, and (2) change the reference in _MainWindow.xaml_ from `DynamicResource` to `StaticResource` and everything still worked.

**Comment by adegeo** [comment]
I believe this should solve the problem. I'll close this issue in anticipation :D just let me know how it goes!

**Comment by SetTrend** [comment]
Thank you so much, @adegeo 👍 

I'm currently investigating on the distinguished differences between external resources via "pack" URI, ComponentResourceKey and `generic.xaml`. It would be a great help if you would spare the time if I'd have another question or two.

At this time, I believe the resouces documentation needs slight improvement. I'm striving for a clear, concise, exhaustive documentation, distinguishing between the four different resource reference approaches.

Just by chance: currently, there isn't a visual tracing tool available, listing a class library's externally available resources and how they affect an app's controls?
