### ISSUE TITLE
GetMetadata returns UIPropertyMetadata, is this then OneWay binding?

### ISSUE THREAD

**Issue by trivalik** [dotnet/docs-desktop#1690]
Just to make sure to determine whether a `DependencyProperty` is TwoWay binding. In case the `GetMetadata` returns "UIPropertyMetadata" let the documentation the reader alone. It just tell how to interpret if type is `FrameworkPropertyMetadata`.

I am also not sure about the correct answer. I would believe it is then `OneWay`.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0087496b-4b5d-33c1-5666-57fccd986ef4
* Version Independent ID: c7bc226d-cd15-3740-a840-b12f7180fd04
* Content: [Data binding overview - WPF .NET](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/data/?view=netdesktop-7.0)
* Content Source: [dotnet-desktop-guide/net/wpf/data/index.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/net/wpf/data/index.md)
* Product: **dotnet-desktop**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

---
[Associated WorkItem - 153647](https://dev.azure.com/msft-skilling/Content/_workitems/edit/153647)

**Comment by adegeo** [comment]
Hello. If I understand your issue correctly, you're pointing out the fact that `DP.GetMetadata` doesn't return `FrameworkPropertyMetadata` as a type. So the paragraph talking about `GetMetadata` should point this out and show that you need to cast it to see if the property (1) supports databinding and (2) see if the property supports the binding mode.

You can read more about it, including an example, in the API doc: https://learn.microsoft.com/dotnet/api/system.windows.frameworkpropertymetadata?view=windowsdesktop-7.0#examples

**Comment by trivalik** [comment]
Thanks for the link, but it does not clarify the how to interpret if another datatype comes back. Maybe it is obvious for experienced developer that if another datatype comes back it is always `OneWay` (at least for `PropertyMetadata` and `UIPropertyMetadata`), but I can imagine if another type is returned (like a custom one) that the answer is not that easy.

**Comment by trivalik** [comment]
Sure, but what is the answer for the else branch? At least for is it `TwoWay` binding?

**Comment by adegeo** [comment]
There is no `else` if you're trying to determine `TwoWay`. As far as I can tell, this is the derived class that would implement `OneWay` or `TwoWay`. The other base classes don't carry this information. If your property metadata isn't of this type, then I think it means the property doesn't support binding.

**Comment by trivalik** [comment]
What I can say is that other types also allow binding.

**Comment by adegeo** [comment]
@trivalik Sorry, I missed your reply! The other types of metadata are supported in binding, but they don't carry the default values for twoway and updatesourcetrigger. Those two values are in the [FrameworkPropertyMetadata type](https://learn.microsoft.com/en-us/dotnet/api/system.windows.frameworkpropertymetadata.defaultupdatesourcetrigger?view=windowsdesktop-7.0).

If you're trying to look up what the current binding is on the property, I think you can do that with `BindingOperations.GetBinding` and then check the `.Mode` and `.UpdateSourceTrigger` properties of the result.

```csharp
// textBox3 is an instance of a TextBox
// the TextProperty is the data-bound dependency property
Binding myBinding = BindingOperations.GetBinding(textBox3, TextBox.TextProperty);
