### ISSUE TITLE
LocBaml tool is incompatible with .NET 6 Core

### ISSUE THREAD

**Issue by ipizhenko** [dotnet/docs-desktop#1695]
The **LocBaml** tool doesn't compile for .NET Core 6. Compiled as is for .NET Framework 4.7.2 it can't work with applications compiled for .NET Core 6. Please update the tool. Please also describe how to achieve the same result WITHOUT using this tool.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7dc952bd-fed7-6cff-e3ae-7ab73eebde02
* Version Independent ID: 9bca4403-30cd-4442-9e1e-765d4a1c4df9
* Content: [Globalization and localization overview - WPF .NET Framework](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/advanced/wpf-globalization-and-localization-overview?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/advanced/wpf-globalization-and-localization-overview.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/advanced/wpf-globalization-and-localization-overview.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

---
[Associated WorkItem - 157252](https://dev.azure.com/msft-skilling/Content/_workitems/edit/157252)

**Comment by adegeo** [comment]
Correct. I saw that you posted in the dotnet/wpf repo, which is where the owner of that tool would be, I assume. I'll add this to the Oct sprint. Personally I don't really know anything about it so there's going to be some learning on my end. If you figure anything out, please keep me informed in this issue.

**Comment by adegeo** [comment]
@dotnet/wpf-developers Is there guidance on how to localize content for WPF with LocBaml being dead?

**Comment by adegeo** [comment]
Pinged some internal folks. Waiting for an answer...

**Comment by adegeo** [comment]
It doesn't seem like this is going to be fixed soon. 😢 https://github.com/dotnet/wpf/issues/7245 I'll at least add a note to the article page.
