### ISSUE TITLE
Great Index for the controls

### ISSUE THREAD

**Issue by Ed2353** [dotnet/docs-desktop#1696]
This page makes it easier to group the controls and makes them easier to understand and find

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 49e8b900-2d5f-a7ab-e25e-f8a4604cc807
* Version Independent ID: 91dfa289-d554-6fc0-48bc-47bee06a1646
* Content: [Controls by Category - WPF .NET Framework](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/controls/controls-by-category?view=netframeworkdesktop-4.8#layout)
* Content Source: [dotnet-desktop-guide/framework/wpf/controls/controls-by-category.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/controls/controls-by-category.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for this feedback!
