### ISSUE TITLE
Example code not clear and not working

### ISSUE THREAD

**Issue by biasosoft** [dotnet/docs-desktop#1697]
The code for data template binding it is not clear and it is not working
The list view shows ItemsSource="{Binding Source={StaticResource ExpenseDataSource}"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d3d7ba9b-4bc3-105a-bed6-fed320821bb5
* Version Independent ID: cc43c332-3eb2-9473-b88a-128c6390cfec
* Content: [Create your first WPF app in Visual Studio 2019 - .NET Framework](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/getting-started/walkthrough-my-first-wpf-desktop-application?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/getting-started/walkthrough-my-first-wpf-desktop-application.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/getting-started/walkthrough-my-first-wpf-desktop-application.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hi @biasosoft Sorry for the delay. What exactly is unclear and not working? When I searched for `ExpenseDataSource` I found the resource declaration in the grid resources, and inside that grid, I see the listbox reference, which seems different from what you put in your issue comment:

```xml
<ListBox Name="peopleListBox" Grid.Column="1" Grid.Row="2" 
         ItemsSource="{Binding Source={StaticResource ExpenseDataSource}, XPath=Person}"
         ItemTemplate="{StaticResource nameItemTemplate}">
</ListBox>
```
