### ISSUE TITLE
Example code block mistakenly (?) spans 2 code blocks

### ISSUE THREAD

**Issue by Decimation** [dotnet/docs-desktop#1699]
Example code spans 2 code blocks, with the last block containing a single brace:

![firefox_2023-09-13_(20h36m44s)_i648vkzABF](https://github.com/dotnet/docs-desktop/assets/4624891/0723db6f-e539-4044-9f5e-968bb4b270d7)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 713fc9ca-506f-f1af-b79b-85833d892454
* Version Independent ID: 34871a66-3028-4913-755e-ab90eb9e2b89
* Content: [How to: Set Up Notification of Binding Updates - WPF .NET Framework](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/data/how-to-set-up-notification-of-binding-updates?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/data/how-to-set-up-notification-of-binding-updates.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/data/how-to-set-up-notification-of-binding-updates.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

---
[Associated WorkItem - 169362](https://dev.azure.com/msft-skilling/Content/_workitems/edit/169362)

**Comment by adegeo** [comment]
Thank you. This is a silly way someone tried to use the code+docs publishing system to yank just some lines out of an existing code sample. I'll get this fixed soon.
