### ISSUE TITLE
No Dice

### ISSUE THREAD

**Issue by TooLoose** [dotnet/docs-desktop#1700]
Smoking your socks I think.
Got to creating the WpfControlLibrary. UserControl1 is created and the editor does indeed open to UserControl1.xaml but thats where it ends. 

```xml
<UserControl x:Class="WpfControlLibrary1.UserControl1"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
             xmlns:local="clr-namespace:WpfControlLibrary1"
             mc:Ignorable="d" 
             d:DesignHeight="450" d:DesignWidth="800">
    <Grid>
            
    </Grid>
</UserControl>
```

No design window here? Stuck.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 67494678-fd83-5a07-331a-3e6565f564af
* Version Independent ID: 4287fc67-3f52-e7ea-bbe2-cd41b6d3fc07
* Content: [Create new WPF Content on Windows Forms](https://learn.microsoft.com/en-us/dotnet/desktop/winforms/advanced/walkthrough-creating-new-wpf-content-on-windows-forms-at-design-time?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/winforms/advanced/walkthrough-creating-new-wpf-content-on-windows-forms-at-design-time.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/winforms/advanced/walkthrough-creating-new-wpf-content-on-windows-forms-at-design-time.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello. Sorry for the delay in response. It sounds like something is wrong with your visual studio installation.  Can you please let me know what version of Visual Studio you're using? If you've not fixed this by now, you should probably reinstall Visual Studio. You can also try closing down your project/solution and opening JUST the WPF control project. The final thing I can suggest is using Visual Studio's menu at the top to report a problem with them directly: **Help** > **Send feedback** > **Report a problem**
