### ISSUE TITLE
The example is not very helpful

### ISSUE THREAD

**Issue by Manthazar** [dotnet/docs-desktop#1701]
In the missing of understanding HOW databinding with DataGridView actually works, you would expect a bunch of code related to data bindings as in preconditions/ limitations or attention points. This example spends 99% of reading time in setting up the form and link a sql result to the grid. Not sure how useful this actually is.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b64c24e5-b492-3147-cc76-383e9a05947a
* Version Independent ID: e2a75064-1d78-3f14-c956-ae4cee8c31e7
* Content: [Bind data to DataGridView Control - Windows Forms .NET Framework](https://learn.microsoft.com/en-us/dotnet/desktop/winforms/controls/how-to-bind-data-to-the-windows-forms-datagridview-control?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/winforms/controls/how-to-bind-data-to-the-windows-forms-datagridview-control.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/winforms/controls/how-to-bind-data-to-the-windows-forms-datagridview-control.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Yeah, I agree with you. A lot of these older articles need a big refresh. What exactly where you hoping to learn from this article? How did you arrive at this article? Knowing this will help me in updating this and other articles for the .NET 7+ docs.
