### ISSUE TITLE
Incorrect code sample in Custom RoutedEvent

### ISSUE THREAD

**Issue by totszwai** [dotnet/docs-desktop#1705]
Is the code wrong? `new(routedEvent: ConditionalClickEvent);` Is missing `RoutedEventArgs` right...?

Could the code example also be updated to showcase how to do a REAL "custom" RoutedEvent? The example right now is still using `RoutedEvent` and `RoutedEventHandler`, is it possible to just route any other event?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 09a6c25d-0ac9-a764-1df5-eea8ede79421
* Version Independent ID: b7506d5e-be24-81aa-80b8-9efffb5b3e8b
* Content: [How to create a custom routed event - WPF .NET](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/events/how-to-create-a-custom-routed-event?view=netdesktop-7.0)
* Content Source: [dotnet-desktop-guide/net/wpf/events/how-to-create-a-custom-routed-event.md](https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/net/wpf/events/how-to-create-a-custom-routed-event.md)
* Product: **dotnet-desktop**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello!

C# syntax (I can't remember when it was introduced) allows you to use `new(parameters)` when declaring the type can be inferred on the left side. So `MyClass obj = new(parameters...)` is valid. If you use `var` you must specify the type with `new`: `var obj = new MyClass(parameters...)`

I'm not sure what you mean by a "real 'custom'" routed event?

**Comment by totszwai** [comment]
Ah ok, I need to switch over to using higher version of C# but I can't since I'm stuck with Framework 4.8
![image](https://github.com/dotnet/docs-desktop/assets/4440365/0272c1df-91c7-4796-9908-531bbea255d0)

> I'm not sure what you mean by a "real 'custom'" routed event?

What I mean is that, in the example, it is still bound to use `RoutedEvent`, example:

```
    public static readonly RoutedEvent ConditionalClickEvent = EventManager.RegisterRoutedEvent(
        name: "ConditionalClick",
        routingStrategy: RoutingStrategy.Bubble,
        handlerType: typeof(RoutedEventHandler), // <=== HERE
        ownerType: typeof(CustomButton));

    // Provide CLR accessors for assigning an event handler.
    public event RoutedEventHandler ConditionalClick  // <=== HERE
    {
        add { AddHandler(ConditionalClickEvent, value); }
        remove { RemoveHandler(ConditionalClickEvent, value); }
    }
```

I tried to make my own custom events such as:
```
public delegate void HelloWorldHandler();
```

If I do that, it would complain that my handler is not of type `RoutedEvent`... since `RegisterRoutedEvent` seems to be only accepting `RoutedEvent` only...

**Comment by adegeo** [comment]
Hello, sorry for the delay, I was out of town. The docs for .NET 6/7 use those code features 😁 So you'll have to down convert to .NET Framework's version of C# if that's what you're using, and I see that's what you did.

The routed event system is looking for a specific pattern of delegate, being `void (object, RoutedEventArgs)` so your custom delegate needs to conform to that. If you have extra data you want to send with the event, create a new class that inherits from `RoutedEventArgs` and use a delegate with your new class: (this code is mostly all written from memory so hopefully it compiles correctly 😁 )
```csharp
public class MyEventArgs: RoutedEventArgs
{
    public string FirstName;

    public MyEventArgs(RoutedEvent routedEvent, object source) : base(routedEvent, source)
    {
    }
}
```
Then create a delegate for that which matches the pattern:
```csharp
public delegate void HelloWorldHandler(object sender, MyEventArgs args);
```
When you go to invoke the routed event, you just pass in your `MyEventArgs` instead of `RoutedEventArgs`:
```csharp
this.RaiseEvent(new MyEventArgs(ConditionalClickEvent, this) { FirstName = "Josh" });
```

Does this help?

**Comment by totszwai** [comment]
Thank you for spending time with the code sample!
