### ISSUE TITLE
Incorrect example reference in Using Resources in XAML.

### ISSUE THREAD

**Issue by DaveGWork** [dotnet/docs-desktop#1714]
### Type of issue

Typo

### Description

Last sentence of section [Use resources in XAML](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/systems/xaml-resources-overview?view=netdesktop-7.0#use-resources-in-xaml) states:

> In the previous example, the sameMyBrush resource sets two different properties: [Button.Background](https://learn.microsoft.com/en-us/dotnet/api/system.windows.controls.control.background) and [Rectangle.Fill](https://learn.microsoft.com/en-us/dotnet/api/system.windows.shapes.shape.fill).

However, the previous example refers to an **ellipse**, not a **rectangle** (there are no references to rectangles in the example):
```xml
<Button Background="{StaticResource MyBrush}"/>
<Ellipse Fill="{StaticResource MyBrush}"/>`
```

Or:
```xml
<Ellipse HorizontalAlignment="Center" Width="100" Height="100" Fill="{StaticResource MyBrush}" Margin="10" />
```

### Page URL

https://learn.microsoft.com/en-us/dotnet/desktop/wpf/systems/xaml-resources-overview?view=netdesktop-7.0

### Content source URL

https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/net/wpf/systems/xaml-resources-overview.md

### Document Version Independent Id

dcb51036-d8b6-ee9d-9d9e-c34a8398e70e

### Article author

adegeo

---
[Associated WorkItem - 171216](https://dev.azure.com/msft-skilling/Content/_workitems/edit/171216)

**Comment by adegeo** [comment]
Thank you for reporting this. I'll get it fixed!
