### ISSUE TITLE
Handle leak

### ISSUE THREAD

**Issue by mdblack98** [dotnet/docs-desktop#172]
[Enter feedback here]
It seems this method creates a thread handle leak

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60c9b9f3-dbfa-0282-6fb1-4ec25b14f2fa
* Version Independent ID: dd4704e0-8053-77a7-835f-1418455156c1
* Content: [Make thread-safe calls to controls - Windows Forms .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/controls/how-to-make-thread-safe-calls-to-windows-forms-controls?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/winforms/controls/how-to-make-thread-safe-calls-to-windows-forms-controls.md](https://github.com/dotnet/docs-desktop/blob/master/dotnet-desktop-guide/framework/winforms/controls/how-to-make-thread-safe-calls-to-windows-forms-controls.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for opening this issue. Can you be a more specific as to where the problem is in the article/code?

Thanks again!

**Comment by mdblack98** [comment]
Check out this thread...I'm currently using the method shown on the link I reported earlier...which they complain about in the link.  I see a handle leak going on too.
https://stackoverflow.com/questions/3048430/ui-thread-invoke-causing-handle-leak

Mike 

    On Monday, January 18, 2021, 01:01:05 PM CST, Andy De George <notifications@github.com> wrote:  
 
 


Thank you for opening this issue. Can you be a more specific as to where the problem is in the article/code?

Thanks again!

**Comment by adegeo** [comment]
I can't seem to replicate this. Using the code from the stackoverflow question, but having it run until told to stop, I see the memory footprint increase until the GC collects the memory and keeps the footprint low. If the GC is collecting the memory, where is the leak?

If I run the code in a slow interval, I can see the memory increasing slowly. However, it never infinitely increases. If I at some point use the GC to force collection, the memory footprint doesn't change. It's keep the memory reserved. As the timer continues to `Invoke` the memory doesn't increase and is reused for some time until it becomes too much and memory increases yet again. However, it always hits the limits the GC has set and collects.

@JeremyKuhne perhaps you can comment? I don't know the history/internals of how this is should or does work.

Here is a sample app and some of the code before I cleaned it up for the app: [WindowsFormsApp1.zip](https://github.com/dotnet/docs-desktop/files/5868806/WindowsFormsApp1.zip)

```csharp
using System;
using System.Threading;
using System.Windows.Forms;

namespace WindowsFormsApp1
{
    public partial class Form1 : Form
    {
        Thread thread;
        private delegate void UpdateGUI();
        bool UpdateTheGui = false;

        public Form1()
        {
            InitializeComponent();

            thread = new Thread(new ThreadStart(MyThreadLoop));
            thread.Start();
        }

        private void MyThreadLoop()
        {
            while (true)
            {
                if (UpdateTheGui)
                    UpdateTheGuiNow();
                else
                    Thread.Sleep(500);
            }
        }

        private void UpdateTheGuiNow()
        {
            if (label1.InvokeRequired)
            {
                var callback = new UpdateGUI(UpdateTheGuiNow);
                label1.Invoke(callback);
                return;
            }

            label1.Text = DateTime.Now.ToString("MM-dd-yyyy HH:mm:ss");
            label2.Text = DateTime.Now.ToString("MM-dd-yyyy HH:mm:ss");
            label3.Text = DateTime.Now.ToString("MM-dd-yyyy HH:mm:ss");
        }

        private void button1_Click(object sender, EventArgs e) =>
            UpdateTheGui = !UpdateTheGui;

        private void Form1_FormClosing(object sender, FormClosingEventArgs e) =>
            thread.Abort();

        private void button2_Click(object sender, EventArgs e)
        {
            GC.Collect();
            GC.WaitForPendingFinalizers();
        }
    }
}
```

**Comment by JeremyKuhne** [comment]
There are no known leaks here. Yes, there are objects that are created that are dependent on the GC running finalizers, but that isn't a leak.  If someone finds WinForms created objects that aren't finalizing properly when the GC runs then a repro and explanation of what exactly is leaking on the dotnet/winforms repository would be the right follow up (if reproducible on .NET Core) . .NET Framework issues are filed as described here: https://github.com/dotnet/winforms#please-note  Note that .NET Framework issues have to meet a very high bar to get changes/fixes made (security issues for example).

cc: @KlausLoeffelmann

**Comment by adegeo** [comment]
Thank you for clarifying. I'm going to close this issue.
