### ISSUE TITLE
Document WFAC* Analyzer Diagnostics

### ISSUE THREAD

**Issue by lonitra** [dotnet/docs-desktop#1721]
**Help us make content visible**
-WFAC001
-WFAC002
-WFAC010

**Describe the new article**

WCAF* analyzer diagnostics are currently undocumented on microsoft.learn. They are documented in the WinForms repo at https://github.com/dotnet/winforms/blob/a8f51bd3d2690890a6ea2ae0d8d084aab0a1b926/docs/list-of-diagnostics.md#analyzer-warnings , but should also be documented https://learn.microsoft.com/en-us/dotnet/desktop/winforms/wfdev-diagnostics/obsoletions-overview?view=netdesktop-7.0 in the reference table or similar

---
[Associated WorkItem - 174295](https://dev.azure.com/msft-skilling/Content/_workitems/edit/174295)

**Comment by adegeo** [comment]
@lonitra I need some more information here. There isn't enough details in the docs you linked. I need a detailed summary of each warning with

- Why does it trigger
- What do you do to fix it
- How is it different from previous versions

**Comment by lonitra** [comment]
Apologies on that! These are new analyzer diagnostics that were added in .NET 6. More information on why it triggers/how to fix them can be found here:
[WFAC001 and WFAC002](https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms.Analyzers.CSharp/ApplicationConfigurationGenerator.Help.md)

[WFAC010](https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms.Analyzers/AppManifestAnalyzer.Help.md#wfac010-unsupported-high-dpi-configuration)

**Comment by adegeo** [comment]
I can't determine how WFAC002 triggers. I understand 001 though.

**Comment by RussKie** [comment]
It's when the supplied value is invalid and can't be parsed:
* https://github.com/dotnet/winforms/blob/d20f9c71a189693c6c3475253397665bce0a1354/src/System.Windows.Forms.Analyzers.CSharp/src/System/Windows/Forms/Generators/ProjectFileReader.cs#L46-L54 --> https://github.com/dotnet/winforms/blob/d20f9c71a189693c6c3475253397665bce0a1354/src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/ProjectFileReaderTests.cs#L160-L181
* https://github.com/dotnet/winforms/blob/d20f9c71a189693c6c3475253397665bce0a1354/src/System.Windows.Forms.Analyzers.CSharp/src/System/Windows/Forms/Generators/ProjectFileReader.cs#L71-L88 --> https://github.com/dotnet/winforms/blob/d20f9c71a189693c6c3475253397665bce0a1354/src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/ProjectFileReaderTests.cs#L86-L122

**Comment by adegeo** [comment]
@RussKie So you mean the project file's value was invalid?

**Comment by RussKie** [comment]
Correct.
E.g., `<ApplicationVisualStyles>yes</ApplicationVisualStyles>` or `<ApplicationDefaultFont>Microsoft Sans Serif, 8.25pt Style=Bold</ApplicationDefaultFont>` would result in `WFAC002`.

**Comment by adegeo** [comment]
@RussKie @lonitra I added a PR with the new error articles, please review.
