### ISSUE TITLE
Case error

### ISSUE THREAD

**Issue by m-brooks** [dotnet/docs-desktop#1726]
### Type of issue

Typo

### Description

[Enter feedback here]
There are references to the button_click method in the text discussing code-behind. This should be button_Click (note the case - it's case-sensitive).

### Page URL

https://learn.microsoft.com/en-us/dotnet/desktop/wpf/overview/?view=netdesktop-7.0&source=docs

### Content source URL

https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/net/wpf/overview/index.md

### Document Version Independent Id

1a4d3c35-a9ac-97e7-a726-b5b4c42a45f5

### Article author

adegeo

**Comment by adegeo** [comment]
@m-brooks Thank you for reporting this, I'll get it fixed!
