### ISSUE TITLE
How to: Set JPEG Compression Level

### ISSUE THREAD

**Issue by EdwardLarrabee** [dotnet/docs-desktop#1732]
### Type of issue

Other (describe below)

### Description

After a painful and fruitless search of the web and Microsoft documentation to discover how to set JPEG compression:

- This is an excellent description of how do it!
- None of the partially relevant pages that describe parts of the solution link to this page. This a major omission.

Having written documentation for programmers, I understand how little software engineers list to writers, but:

- The default compression setting for JPEG saves produces the smallest files but images that are nearly worthless.
- There is little explanation of the meaning of the parameters and what they produce.

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/desktop/winforms/advanced/how-to-set-jpeg-compression-level?view=netframeworkdesktop-4.8

### Content source URL

https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/winforms/advanced/how-to-set-jpeg-compression-level.md

### Document Version Independent Id

b0ca8d84-edb4-0adf-f289-54945dd6ef62

### Article author

adegeo

**Comment by adegeo** [comment]
Hello. I'm glad you finally found the information you needed. However, I'm not sure that I understand what you're requesting. Can you provide more details as to what you would like me to do to improve the documentation.
