### ISSUE TITLE
Shock

### ISSUE THREAD

**Issue by ShockAdam** [dotnet/docs-desktop#1733]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/desktop/winforms/windows-forms-data-binding?view=netframeworkdesktop-4.8

### Content source URL

https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/winforms/windows-forms-data-binding.md

### Document Version Independent Id

19cd298e-2016-edc8-0f7c-430ddccdff78

### Article author

adegeo

**Comment by adegeo** [comment]
Hello, you opened this issue but didn't add any information. Is there something I can help you with regarding that article?
