### ISSUE TITLE
Me

### ISSUE THREAD

**Issue by jchernand0** [dotnet/docs-desktop#1738]
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/desktop/winforms/advanced/how-to-create-application-settings?view=netframeworkdesktop-4.8#to-create-new-application-settings-programmatically

### Content source URL

https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/winforms/advanced/how-to-create-application-settings.md

### Document Version Independent Id

8094f938-37c8-54cb-e3e7-2ea31bda74d4

### Article author

adegeo

**Comment by adegeo** [comment]
Hello, you opened this issue but didn't add any information. Is there something I can help you with regarding that article?
