### ISSUE TITLE
Window.Close documentation missing return value for CloseDialog

### ISSUE THREAD

**Issue by RedX2501** [dotnet/docs-desktop#1744]
### Type of issue

Missing information

### Description

https://learn.microsoft.com/en-us/dotnet/desktop/wpf/windows/how-to-close-window-dialog-box?view=netdesktop-8.0#cancel-close-and-hide

This page states that `Close` will return false when the window is shown using `ShowDialog`. This information is missing from this page.

### Page URL

https://learn.microsoft.com/en-us/dotnet/desktop/wpf/windows/how-to-close-window-dialog-box?view=netdesktop-8.0

### Content source URL

https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/net/wpf/windows/how-to-close-window-dialog-box.md

### Document Version Independent Id

84dce3df-b013-726d-b5ec-cffd901051ae

### Article author

@adegeo

---
[Associated WorkItem - 230265](https://dev.azure.com/msft-skilling/Content/_workitems/edit/230265)

**Comment by adegeo** [comment]
Hi @RedX2501 thank you for opening this issue. However, I don't see what you're referencing. Can you add some more information about what is missing and where specifically it's missing?

**Comment by RedX2501** [comment]
I see, i thought the linked pointed to the close API.
So i mean that this page https://learn.microsoft.com/en-us/dotnet/api/system.windows.window.close?view=windowsdesktop-8.0 about the close method on the window class 
Is missing the information that ShowDialog will return false (and not null) when a dialog is closed via Close.

**Comment by adegeo** [comment]
OK thank you for that clarification! I see what you're talking about. I'll look at getting an update in there. Thanks again!
