### ISSUE TITLE
A critical step seems to be missing from this article

### ISSUE THREAD

**Issue by Fish-watching-the-sea** [dotnet/docs-desktop#1746]
### Type of issue

Missing information

### Description

I installed the steps in the article to create a new custom control class, which inherits from Control by default. I directly changed Control to Button and followed the steps in the article. However, an error occurred when using the controls in the toolbox.

### Page URL

https://learn.microsoft.com/zh-cn/dotnet/desktop/winforms/controls-design/extend-existing?view=netdesktop-8.0

### Content source URL

https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/net/winforms/controls-design/extend-existing.md

### Document Version Independent Id

0e50042f-8923-2392-0adb-752f313c42c6

### Article author

@adegeo

**Comment by adegeo** [comment]
Hello @Fish-watching-the-sea can you provide the error? Can you also add in your code?
