### ISSUE TITLE
Italian page "Estensione del markup TemplateBinding" typo

### ISSUE THREAD

**Issue by AndreaGordanelli** [dotnet/docs-desktop#1762]
### Type of issue

Localization

### Description

Section "Osservazioni"
Un TemplateBinding oggetto è una forma ottimizzata di binding[MISSING SPACE]per gli scenari di modello

### Page URL

https://learn.microsoft.com/it-it/dotnet/desktop/wpf/advanced/templatebinding-markup-extension?view=netframeworkdesktop-4.8

### Content source URL

https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/advanced/templatebinding-markup-extension.md

### Document Version Independent Id

6b07aa4c-9201-9928-8c9e-77fbe7ad5396

### Article author

@adegeo

---
[Associated WorkItem - 226793](https://dev.azure.com/msft-skilling/Content/_workitems/edit/226793)

**Comment by adegeo** [comment]
Thank you for reporting this. I'll file a bug with our localization system.

**Comment by adegeo** [comment]
Internal bug [940390](https://dev.azure.com/ceapex/CEINTL/_workitems/edit/940390)

**Comment by adegeo** [comment]
In the next sprint, I'm going to try and force a fix to prevent that word from translating incorrectly.
