### ISSUE TITLE
Add ToolStripItem.SelectedChanged event

### ISSUE THREAD

**Issue by Epica3055** [dotnet/docs-desktop#1801]
**Related links**
[Issue_8548](https://github.com/dotnet/winforms/issues/8548), [PR_10321](https://github.com/dotnet/winforms/pull/10321)

**Issue description**

.NET Core 3.1 introduced a [breaking change](https://learn.microsoft.com/en-us/dotnet/core/compatibility/winforms#removed-controls) in using Menus. MainMenu and MenuItem controls were removed and ToolStripMenuItem is recommended as a replacement.

However, the new ToolStripMenuItem class is missing the equivalent to MenuItem's [Select](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.menuitem.select?view=netframework-4.8) event, that is raised when menu item is highlighted by mouse or keyboard.

This event is most commonly used to display hints/descriptions/feedback to user when they navigate through menu items.

Some workarounds are the following ToolStripMenuItem's events: `MouseEnter`, `MouseLeave`, `MouseHover`, etc. But this does not cover the selection of a ToolStripMenuItem via keyboard (e.g. arrow keys).

Adding a new `SelectedChanged` event to the ToolStripItem class could be a solution to the problem. The event is raised every time the [Selected](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.toolstripitem.selected?view=windowsdesktop-7.0) property value changes, similar to [AvailableChanged](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.toolstripitem.availablechanged?view=windowsdesktop-7.0) or [EnabledChanged](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.toolstripitem.enabledchanged?view=windowsdesktop-7.0) events.

**Target framework**

-  .NET Core

**Version**
9.0.100-alpha.1.23511.2

**Simple usage after adding this new event**

<details open>
  <summary>Code sample</summary>

``` c#

using System.Diagnostics;

namespace Sample;

internal static class Program
{
    [STAThread]
    static void Main()
    {
        Application.EnableVisualStyles();
        Application.SetHighDpiMode(HighDpiMode.PerMonitorV2);
        Application.Run(new TestForm());
    }
}

class TestForm: Form
{
    private System.ComponentModel.IContainer components = null;

    public TestForm()
    {
        InitializeComponent();
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing && (components != null))
        {
            components.Dispose();
        }

        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container();
        menuStrip1 = new MenuStrip();
        toolStripMenuItem1 = new ToolStripMenuItem();
        toolStripMenuItem2 = new ToolStripMenuItem();

        toolStripMenuItem2.SelectedChanged += (e, s) =>
        {
            Trace.WriteLine("\n toolStripMenuItem2.SelectedChanged " + DateTime.Now.ToString());
        };

        toolStripMenuItem3 = new ToolStripMenuItem();

        menuStrip1.Items.AddRange(new ToolStripItem[] { toolStripMenuItem1, toolStripMenuItem2, toolStripMenuItem3 });
        menuStrip1.Location = new Point(0, 0);
        menuStrip1.Name = "menuStrip1";
        menuStrip1.Size = new Size(300, 24);
        menuStrip1.TabIndex = 2;
        menuStrip1.Text = "menuStrip1";

        toolStripMenuItem1.Name = "toolStripMenuItem1";
        toolStripMenuItem1.Size = new Size(37, 20);
        toolStripMenuItem1.Text = "MenuItem1";

        toolStripMenuItem2.Name = "toolStripMenuItem2";
        toolStripMenuItem2.Size = new Size(43, 20);
        toolStripMenuItem2.Text = "MenuItem2";

        toolStripMenuItem3.Name = "toolStripMenuItem3";
        toolStripMenuItem3.Size = new Size(49, 20);
        toolStripMenuItem3.Text = "MenuItem3";

        AutoScaleDimensions = new SizeF(7F, 15F);
        AutoScaleMode = AutoScaleMode.Font;
        ClientSize = new Size(300, 200);
        Controls.Add(menuStrip1);
    }

    private MenuStrip menuStrip1;
    private ToolStripMenuItem toolStripMenuItem1;
    private ToolStripMenuItem toolStripMenuItem2;
    private ToolStripMenuItem toolStripMenuItem3;
}

```
</details>

https://github.com/dotnet/docs/assets/135201996/4e1e1edc-4860-40d7-bec5-e832eead92df

**Comment by lonitra** [comment]
> > Since this is a new API, this will need to be documented.
> 
> @lonitra Can you clarify what sort of documentation you're looking for in [dotnet/winforms#10321 (review)](https://github.com/dotnet/winforms/pull/10321#pullrequestreview-1775722435)? It is updated API docs, or a conceptual doc?

More of an updated API doc. There are a list of events that users can hook into for `ToolStripItem` which are documented [here](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.toolstripitem.availablechanged?view=windowsdesktop-7.0). The linked PR added a new event called `SelectedChanged` along with `OnSelectedChange` method so we'd like to get this documented in the same fashion as the other events and `OnX` methods.

**Comment by gewarren** [comment]
@lonitra If you select .NET 9, you can see the SelectedChanged event: https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.toolstripitem.selectedchanged?view=windowsdesktop-9.0. If you need guidance on porting over the actual documentation comments, let me know.

**Comment by lonitra** [comment]
Yes could you give me some guidance on that? Apologies, I had thought an issue needed to be opened to get this done for new APIs.

**Comment by gewarren** [comment]
You can either edit the ToolStripItem.xml file directly in the dotnet/dotnet-api-docs repo, or you can use this tool to port all /// comments from the source code for a given assembly or type: https://github.com/dotnet/api-docs-sync/blob/main/docs/PortToDocs.md.

**Comment by lonitra** [comment]
Got it, thank you so much! I will get to updating the docs using the guidance you provided.

**Comment by adegeo** [comment]
@lonitra should I close this issue? I don't think there's anything to do here in this repo.

**Comment by lonitra** [comment]
I hadn't gotten to making a PR for this yet, but please feel free to close as this is more of an action item for winforms.
