### ISSUE TITLE
error in the doc

### ISSUE THREAD

**Issue by rromerik** [dotnet/docs-desktop#1805]
### Type of issue

Missing information

### Description

Line Command is able to take multiple point, but the doc only says it take a single endpoint...
this is a valid path...
M16,16L0,16 0,0 16,0z
the line command (L0,16 0,0 16,0)

### Page URL

https://learn.microsoft.com/en-us/dotnet/desktop/wpf/graphics-multimedia/path-markup-syntax?view=netframeworkdesktop-4.8

### Content source URL

https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/graphics-multimedia/path-markup-syntax.md

### Document Version Independent Id

d68f63c2-ad1b-2650-f005-3d10d14eaf39

### Article author

@adegeo

---
[Associated WorkItem - 242440](https://dev.azure.com/msft-skilling/Content/_workitems/edit/242440)

**Comment by adegeo** [comment]
Thanks, I'll mention that.
