### ISSUE TITLE
Typo - Practical vs Concrete

### ISSUE THREAD

**Issue by adegeo** [dotnet/docs-desktop#1815]
### Type of issue

Typo

### Description

Article uses the term "practical" instead of "concrete" when talking about non-abstract classes.

### Page URL

https://learn.microsoft.com/en-us/dotnet/desktop/wpf/advanced/xaml-and-custom-classes-for-wpf?view=netframeworkdesktop-4.8

### Content source URL

https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/advanced/xaml-and-custom-classes-for-wpf.md

### Document Version Independent Id

87c6e97d-b3c0-a960-69b1-0a48f2f12134

### Article author

@adegeo

---
[Associated WorkItem - 250205](https://dev.azure.com/msft-skilling/Content/_workitems/edit/250205)

**Comment by bigboybamo** [comment]
Hi @adegeo, I saw this marked as help wanted so I opened a pull request for this fix #1820
Thanks
