### ISSUE TITLE
visual studio 2019 cannot add wpf control to elementhost

### ISSUE THREAD

**Issue by FriesLander** [dotnet/docs-desktop#182]
In visual studio 2019, I cannot add the wpf control to the winforms form because it does not appear in the winforms form toolbox. Adding the elementhost control works but there are no WPF controls that can be associated with this. This feature worked in VS2017, is it still supported in VS2019?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67494678-fd83-5a07-331a-3e6565f564af
* Version Independent ID: 4287fc67-3f52-e7ea-bbe2-cd41b6d3fc07
* Content: [Create new WPF Content on Windows Forms](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/advanced/walkthrough-creating-new-wpf-content-on-windows-forms-at-design-time?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/winforms/advanced/walkthrough-creating-new-wpf-content-on-windows-forms-at-design-time.md](https://github.com/dotnet/docs-desktop/blob/master/dotnet-desktop-guide/framework/winforms/advanced/walkthrough-creating-new-wpf-content-on-windows-forms-at-design-time.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**

**Comment by adegeo** [comment]
Are you using WPF for .NET 5 or .NET Framework?

**Comment by FriesLander** [comment]
Thank you for your response. I am currently targeting 4.8  for the winforms project and I have tried .Net Core 3.1 and .Net 5 for the Wpf control but with neither the controls appear in teh winforms toolbox

**Comment by adegeo** [comment]
I don't know that it would work mixing frameworks like that. You should keep it all in .NET Framework or all in .NET 5/Core. Visual Studio is definitely tooled to work with each differently. Let me know if using the same solves your problem.

**Comment by FriesLander** [comment]
That did the trick. I changed the target for the WPF control library from .Net 5/Core to  .Net Framework 4.8 to match the WinForms project and it worked. Many thanks Andy,
