### ISSUE TITLE
ToolBar need link tool

### ISSUE THREAD

**Issue by Paris-Granville** [dotnet/docs-desktop#1827]
### Type of issue

Missing information

### Description

Help
This page describes Toolbar [https://learn.microsoft.com/fr-fr/dotnet/desktop/wpf/controls/toolbar?view=netframeworkdesktop-4.8](url)
But, I cannot find any info about internet link tool (to insert an internet link in the text).
Does anyone can help ?
Tks

### Page URL

https://learn.microsoft.com/fr-fr/dotnet/desktop/wpf/controls/toolbar?view=netframeworkdesktop-4.8

### Content source URL

https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/controls/toolbar.md

### Document Version Independent Id

b7b30375-c6f7-f051-b076-33e0cf7e71c8

### Article author

@adegeo

**Comment by adegeo** [comment]
Sorry, I don't understand what you're referencing. I've never heard of a internet link tool?

**Comment by Paris-Granville** [comment]
In toolbars, you have tools (copy, cut, paste, etc).
Among tools, there is one used to insert an active link (you can call it url).
I whish to know how to set such tool in a toolbar.

**Comment by adegeo** [comment]
I think I understand you. What you're saying is that you've seen toolbars in apps that have a link you can click on, as an item in the toolbar.

You can put any control inside of the toolbar. To create clickable links, use a `<TextBlock><Hyperlink>` control combintation:

```xaml
<ToolBar VerticalAlignment="Top">
    <Button>Test Button</Button>
    <Separator />
    <TextBlock VerticalAlignment="Center">
        <Hyperlink NavigateUri="https://www.microsoft.com" Click="Hyperlink_Click">More Information</Hyperlink>
    </TextBlock>
</ToolBar>
```

![image](https://github.com/dotnet/docs-desktop/assets/67293991/0d959682-0370-49c6-978b-9c949c781ea9)

You then need to handle the `Click` handler and open a browser window or whatever you want. You could just open other windows or do something else in the app. There is no direct web browser launch, so you'll need to look up how to do that with the Windows Shell:

```csharp
private void Hyperlink_Click(object sender, RoutedEventArgs e)
{
    var url = ((Hyperlink)sender).NavigateUri.ToString();
    var procInfo = new System.Diagnostics.ProcessStartInfo(url)
    {
        UseShellExecute = true,
    };
    System.Diagnostics.Process.Start(procInfo);
}
```

I believe this answers your question.
