### ISSUE TITLE
Incomplete documentation

### ISSUE THREAD

**Issue by Bohdan-dotcom** [dotnet/docs-desktop#1828]
### Type of issue

Code doesn't work

### Description

The documentation on the Learn Microsoft website is not fully developed and there is only confusion, no simplicity, no ease in understanding everything, which costs a lot of nerves on this website, please do something about it so that everything changes for the better. :-(

### Page URL

https://learn.microsoft.com/pl-pl/dotnet/desktop/wpf/get-started/create-app-visual-studio?view=netdesktop-8.0

### Content source URL

https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/net/wpf/get-started/create-app-visual-studio.md

### Document Version Independent Id

cce4458e-b162-09f3-48ea-b4481aa4c183

### Article author

@adegeo

**Comment by adegeo** [comment]
I hear you. The content for .NET Framework WPF is still available and is 90% compatible with .NET WPF. Is there something you want to see specifically for .NET WPF?
