### ISSUE TITLE
ISSUE

### ISSUE THREAD

**Issue by TehreemRiaz32** [dotnet/docs-desktop#1835]
### Type of issue

Other (describe below)

### Description

THE APPLICATION IS NOT USER FRIENDLY

### Page URL

https://learn.microsoft.com/en-us/dotnet/desktop/winforms/windows-forms-data-binding?view=netframeworkdesktop-4.8

### Content source URL

https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/winforms/windows-forms-data-binding.md

### Document Version Independent Id

19cd298e-2016-edc8-0f7c-430ddccdff78

### Article author

@adegeo

**Comment by adegeo** [comment]
Hello @TehreemRiaz32 I'm not sure what you mean. Can you please clarify?
