### ISSUE TITLE
Image missing or incorrect in section 'Drawing Content in Visual Objects'

### ISSUE THREAD

**Issue by DanStevens** [dotnet/docs-desktop#1837]
### Type of issue

Missing information

### Description

There appears to be images missing in section _Drawing Content in Visual Objects_ of the article WPF Graphics Rendering Overview.

![image](https://github.com/dotnet/docs-desktop/assets/1074238/49f27dbd-1ec1-4d17-baa8-c953295c5198)

The above screenshot of the relevant section is the text `DrawingGroup order of operations` followed by `Order of DrawingGroup operations`. The former run of text is an image element with the tag `alt="DrawingGroup order of operations"`, so it appears my browser is displaying the `alt` text as the image source is missing or incorrect.

Here is the complete HTML `img` tag:

`<img src="media/graphcismm-drawinggroup-order.png?view=netframeworkdesktop-4.8" alt="DrawingGroup order of operations" title="graphcismm_drawinggroup_order" data-linktype="relative-path">`

### Page URL

https://learn.microsoft.com/en-us/dotnet/desktop/wpf/graphics-multimedia/wpf-graphics-rendering-overview?view=netframeworkdesktop-4.8

### Content source URL

https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/framework/wpf/graphics-multimedia/wpf-graphics-rendering-overview.md

### Document Version Independent Id

b474b103-625b-e0af-d370-dd850a6748e3

### Article author

@adegeo

---
[Associated WorkItem - 263797](https://dev.azure.com/msft-skilling/Content/_workitems/edit/263797)

**Comment by YAYA-INK** [comment]
I encountered the same problem.
