### ISSUE TITLE
Invalid property in WPF Names tutorial

### ISSUE THREAD

**Issue by madzdog** [dotnet/docs-desktop#1891]
### Type of issue

Typo

### Description

1stNames is not a valid value for the property x:Name. It must start with a character.

### Page URL

https://learn.microsoft.com/en-us/dotnet/desktop/wpf/get-started/create-app-visual-studio?view=netdesktop-7.0

### Content source URL

https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/net/wpf/get-started/create-app-visual-studio.md

### Document Version Independent Id

cce4458e-b162-09f3-48ea-b4481aa4c183

### Article author

@adegeo

**Comment by madzdog** [comment]
1stNames is not a valid value for the property x:Name.  It must start with a character.

**Comment by adegeo** [comment]
@hi

**Comment by adegeo** [comment]
Looking at this, the name is actually **LSTNAMES** not **1STNAMES** that's an L not a 1. I do admit, the font on my machine does make it look like a 1 lol. I'm going to close this issue. Thanks for reporting it!
