### ISSUE TITLE
Example code is VB.NET only

### ISSUE THREAD

**Issue by Hefaistos68** [dotnet/docs-desktop#192]
There is no C# example code available. When code type selection is on C# the example is still shown as VB

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04cd6654-e92a-b84c-f26b-b8a4f1aa4cf2
* Version Independent ID: 24efb60b-4356-f8f3-12e4-a9e11eac06c6
* Content: [How to: Custom Draw a ToolStrip Control - Windows Forms .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/controls/how-to-custom-draw-a-toolstrip-control?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/winforms/controls/how-to-custom-draw-a-toolstrip-control.md](https://github.com/dotnet/docs-desktop/blob/master/dotnet-desktop-guide/framework/winforms/controls/how-to-custom-draw-a-toolstrip-control.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Interesting! I wonder how that got lost during migration (if it was even ever there) Thank you for filing this issue. We'll get it fixed up.
