### ISSUE TITLE
The example of Styles section is uncompilable

### ISSUE THREAD

**Issue by trannamtrung1st** [dotnet/docs-desktop#196]
https://docs.microsoft.com/en-us/dotnet/desktop/wpf/introduction-to-wpf?view=netframeworkdesktop-4.8#styles
This example of Styles section is uncompilable. Detail error: The property 'Content' is set more than once.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fbc43bf-579e-bea3-9e01-b949d85bac3b
* Version Independent ID: 49790964-9329-7cf1-2472-4e4632bac7f8
* Content: [Introduction to WPF](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/introduction-to-wpf?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/introduction-to-wpf.md](https://github.com/dotnet/docs-desktop/blob/master/dotnet-desktop-guide/framework/wpf/introduction-to-wpf.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for catching this! We'll get this fixed up.
