### ISSUE TITLE
Fix grammatical error

### ISSUE THREAD

**Issue by muneeb-devp** [dotnet/docs-desktop#1965]
### Type of issue

Typo

### Description

**.NET SDK projects automatically import the correct Page and Compile items for you and you don't need to do declare these.**

Suggested changes:
- Replace *do declare* with *declare* — the "do" is unnecessary in this context
- Added a comma before "and" to separate the clauses.

### Page URL

https://learn.microsoft.com/en-us/dotnet/desktop/wpf/windows/?view=netdesktop-9.0

### Content source URL

https://github.com/dotnet/docs-desktop/blob/main/dotnet-desktop-guide/net/wpf/windows/index.md

### Document Version Independent Id

02653ec8-ce70-979e-c96c-5949fa5befd6

### Article author

@adegeo

### Metadata

* ID: c50c7729-f1ce-2f8e-cd77-186a94846c64 
* Service: **dotnet-desktop**
* Sub-service: **wpf**

[Related Issues](https://github.com/dotnet/docs-desktop/issues?q=is%3Aissue+is%3Aopen+02653ec8-ce70-979e-c96c-5949fa5befd6)

**Comment by muneeb-devp** [comment]
Hi, could this issue be assigned to me please? I would like to edit the document and create a PR

**Comment by adegeo** [comment]
@muneeb-devp Absolutely! Sorry for the delay!
