### ISSUE TITLE
Aligning controls

### ISSUE THREAD

**Issue by swurding** [dotnet/docs-desktop#202]
Your page says to go to the format menu to align my controls.  Visual Studio 2019 has no format menu, unless it is hidden amongst dozens of others somewhere.  Not helpful at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7ab477d-b8ee-fe6b-81d2-a8628ff495f6
* Version Independent ID: f9f6774c-2dcc-5380-1103-1f7655a5558a
* Content: [Align Multiple Controls - Windows Forms .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/controls/how-to-align-multiple-controls-on-windows-forms?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/winforms/controls/how-to-align-multiple-controls-on-windows-forms.md](https://github.com/dotnet/docs-desktop/blob/master/dotnet-desktop-guide/framework/winforms/controls/how-to-align-multiple-controls-on-windows-forms.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
When you have the designer open, the Format menu should be visible:

![image](https://user-images.githubusercontent.com/67293991/106969709-3c0bcf80-6700-11eb-98a4-1513552578e1.png)
