### ISSUE TITLE
Link missing in Threading Model page

### ISSUE THREAD

**Issue by Cyl18** [dotnet/docs-desktop#204]
![image](https://user-images.githubusercontent.com/14993992/107140567-d1f06600-695d-11eb-8a3c-f9cec5f68482.png)

Here `Task Parallelism` is capitalized, so it should be a link?

https://github.com/dotnet/docs-desktop/blob/99e90fa1624d46f03ba9e0f43aeba6612e616b7c/dotnet-desktop-guide/framework/wpf/advanced/threading-model.md#L30
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0bc9d86-b893-7c9f-d832-3c3026f5278e
* Version Independent ID: 5d75b64a-62d1-b0f9-b8fd-c84f60318808
* Content: [Threading Model - WPF .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/threading-model?redirectedfrom=MSDN&view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/advanced/threading-model.md](https://github.com/dotnet/docs-desktop/blob/master/dotnet-desktop-guide/framework/wpf/advanced/threading-model.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for opening this issue. I'll look for the appropriate link. Great catch!
