### ISSUE TITLE
Incorrect Properties\Resources Update

### ISSUE THREAD

**Issue by atniomn** [dotnet/docs-desktop#205]
```
<ItemGroup>
  <EmbeddedResource Include="Properties\Resources.resx">
    <Generator>ResXFileCodeGenerator</Generator>
    <LastGenOutput>Resources.Designer.cs</LastGenOutput>
  </EmbeddedResource>
  <Compile Update="Properties\Resources.Designer.cs">
    <AutoGen>True</AutoGen>
    <DependentUpon>Resources.resx</DependentUpon>
    <DesignTime>True</DesignTime>
  </Compile>
</ItemGroup>
```

The EmbeddedResources item should be an Update, not an Inlcude. An Include will cause the dotnet SDK to complain about duplicate items, without globbing on *.resx files disabled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98778ad1-6c20-6310-e4bc-9d9851a2270a
* Version Independent ID: d1ef1f43-00e2-b46f-4f38-6274a34f07f6
* Content: [Migrate a Windows Forms app to .NET 5 - Windows Forms .NET](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/migration/?view=netdesktop-5.0)
* Content Source: [dotnet-desktop-guide/net/winforms/migration/index.md](https://github.com/dotnet/docs-desktop/blob/master/dotnet-desktop-guide/net/winforms/migration/index.md)
* Product: **dotnet-desktop**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Yes, I see how I messed that up in a different PR. I'll adjust this wording to clarify that.
