### ISSUE TITLE
Great Tutorial.

### ISSUE THREAD

**Issue by margeir** [dotnet/docs-desktop#214]
Thanks for this tutorial, I´m looking to rewrite my (old) WinForm application.
Needed to get the basics in WPF.

Thanks, Margeir

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3d7ba9b-4bc3-105a-bed6-fed320821bb5
* Version Independent ID: cc43c332-3eb2-9473-b88a-128c6390cfec
* Content: [Create your first WPF app in Visual Studio 2019 - .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/getting-started/walkthrough-my-first-wpf-desktop-application?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/getting-started/walkthrough-my-first-wpf-desktop-application.md](https://github.com/dotnet/docs-desktop/blob/master/dotnet-desktop-guide/framework/wpf/getting-started/walkthrough-my-first-wpf-desktop-application.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Glad it helped!
