### ISSUE TITLE
Better Standalone Example For Creating a Popup

### ISSUE THREAD

**Issue by CheetahChrome** [dotnet/docs-desktop#216]
Examples can be frustrating if they are not fully self contained.  The create pop-up examples are ones that one cannot be just copy and pasted into the editor and run.

So this example, unlike the first `Button` code example, does not need a code-behind `Click` event to show the popup.  Instead the below example uses a `ToggleButton` where the popup's `IsOpen` state is bound to the toggle's property `IsChecked`; hence making it selfcontained:

```
<ToggleButton   x:Name="OpenState"
                 Height="30" Width="60">
    <StackPanel>
        <TextBlock Text="{Binding IsChecked, ElementName=OpenState}"
                    FontSize="18"
                    VerticalAlignment="Center"
                    HorizontalAlignment="Center">
        </TextBlock>

        <Popup Name="myPopup"
                IsOpen="{Binding IsChecked, ElementName=OpenState}">
            <TextBlock Name="myPopupText"
                        Background="LightBlue"
                        Foreground="Blue">Popup Text</TextBlock>
        </Popup>

    </StackPanel>
</ToggleButton>
```
Hence a fully contained example. :-)

---
Its frustrating to a new learner when they can't just run an example. As mentioned, the first example shown (https://docs.microsoft.com/en-us/dotnet/desktop/wpf/controls/popup-overview?view=netframeworkdesktop-4.8#creating-a-popup) does not work. My example above does work without code behind.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e046afa9-e4b1-1f27-88c3-be8540d6f64e
* Version Independent ID: 58b0db73-1b13-e2a5-cff3-fb89493422d1
* Content: [Popup Overview - WPF .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/controls/popup-overview?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/controls/popup-overview.md](https://github.com/dotnet/docs-desktop/blob/master/dotnet-desktop-guide/framework/wpf/controls/popup-overview.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Yuck, what a terrible example the docs are providing here! Thank you for pointing this out. I'll get this fixed up.
