### ISSUE TITLE
Need Updated Document for .NET5 for DataSource and Databinding

### ISSUE THREAD

**Issue by babj57** [dotnet/docs-desktop#219]
I am trying to create a database using Visual Studio 2019 in C#. I select Add a data source but I get the following message:
The window is not supported for the selected project. For steps to enable data binding please visit:
https://aka.ms/WinForms/DataBinding. I would like to see a .NET5 data source and data binding document.  I am using Windows Forms Application to develop. I can use Frameworks 4.8 with no problem but I would like to learn how to do it with the .Net 5.
 Thanks,
Bernard A. Bailey, Jr.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48ae40c5-6c3a-adc3-c81b-0c9a1f017fb8
* Version Independent ID: 19cd298e-2016-edc8-0f7c-430ddccdff78
* Content: [Data Binding - Windows Forms .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/windows-forms-data-binding?view=netframeworkdesktop-4.8&viewFallbackFrom=netdesktop-5.0)
* Content Source: [dotnet-desktop-guide/framework/winforms/windows-forms-data-binding.md](https://github.com/dotnet/docs-desktop/blob/master/dotnet-desktop-guide/framework/winforms/windows-forms-data-binding.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello! I'm not sure why it tells you to go here. Looking around the winforms repository, there are quite a few issues opened related to data binding. I think the designers are still catching up unfortunately. You may want to ask there. Here is another issue opened a few months ago related to data binding. dotnet/winforms#4362 However, you may want to create a specific issue about "How do I create a data binding source for .NET 5 WinForms through Visual Studio" as really I think that's the problem. It's probably pointing you to docs to essentially learn how to do it by hand and not through the designer. An article like [this](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/data-binding-and-windows-forms?view=netframeworkdesktop-4.8)would get you started in some way. But it's far from a solution that will get you going..


You are correct though, the documentation for data binding in .NET 5 world doesn't yet exist. I'm using issue #72 to track the overall progress of WinForms content.

**Comment by adegeo** [comment]
As I think this just isn't fully ready yet from Visual Studio's side, I'm going to close this issue. Talking to the winforms folks in the repository I linked to in my previous comment will probably get you some clearer answers as to when this will be supported. It may be supported in the next release of Visual Studio for example.
