### ISSUE TITLE
Refer to DesignerSerializationVisibility attribute

### ISSUE THREAD

**Issue by chm-tm** [dotnet/docs-desktop#27]
When it comes to generate efficient code, the [`DesignerSerializationVisibility` attribute](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.designerserializationvisibilityattribute) would be worth to be mentioned. Depending on the scenario, the attribute fits better.

An example:

My scenario was a custom inherited `ToolStripButton`. It introduces a new property which controls some of the properties of the base classes. Those properties should no longer be serialized.

I first tried the methodology described in this page before finding out that the `DesignerSerializationVisibility` attribute works best for me, using the following pattern:

```C#
[Browsable(false)]
[DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
public new bool CheckOnClick { get => base.CheckOnClick; set => base.CheckOnClick = value; }
```

By the way, there are two swapped words "a have" in the first sentence.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e32682fb-671a-8f6e-045c-e92a96ca029e
* Version Independent ID: 42210b30-f3ee-9975-b3f2-8752f9aca815
* Content: [Defining Default Values with the ShouldSerialize and Reset Methods - Windows Forms .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/controls/defining-default-values-with-the-shouldserialize-and-reset-methods?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/winforms/controls/defining-default-values-with-the-shouldserialize-and-reset-methods.md](https://github.com/dotnet/docs-desktop/blob/master/dotnet-desktop-guide/framework/winforms/controls/defining-default-values-with-the-shouldserialize-and-reset-methods.md)
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for opening this issue. I'll add it to the backlog. If you would like to contribute, you can submit a fix by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!
