### ISSUE TITLE
Walkthrough: Implementing a Form That Uses a Background Operation

### ISSUE THREAD

**Issue by jm000r** [dotnet/docs-desktop#35]
For the progress bar I am unable to find :  
backgroundWorker1_ProgressChanged()

There is something about cursor position.

Thanks,
John
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abc0abf3-d937-0712-190b-4b88df2ea032
* Version Independent ID: 36808bbd-11ce-2131-9b03-64e4d5f48c57
* Content: [Walkthrough: Implementing a Form That Uses a Background Operation - Windows Forms .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/controls/walkthrough-implementing-a-form-that-uses-a-background-operation?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/winforms/controls/walkthrough-implementing-a-form-that-uses-a-background-operation.md](https://github.com/dotnet/docs-desktop/blob/live/dotnet-desktop-guide/framework/winforms/controls/walkthrough-implementing-a-form-that-uses-a-background-operation.md)
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
@jm000r Hello. I'm unsure what you mean by you're unable to find that method. Where are you looking? What part in the tutorial are you where you ran into this problem?

**Comment by jm000r** [comment]
Thanks, Andy:

 

    Believe I didn’t study it enough to know where to find it.   Let me study some more without wasting your time.

 

 

John

**Comment by adegeo** [comment]
The first area where that method is referenced, the steps right before that, say to add the event handler for ProgressChanged. This is what generates the method for you.

Please let me know if that solves your problem. Thanks!

**Comment by adegeo** [comment]
Glad I could help!
