### ISSUE TITLE
not working with identity colum in a table

### ISSUE THREAD

**Issue by mverdia** [dotnet/docs-desktop#39]
[Immetti qui i commenti]

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: b64c24e5-b492-3147-cc76-383e9a05947a
* Version Independent ID: e2a75064-1d78-3f14-c956-ae4cee8c31e7
* Content: [Bind data to DataGridView Control - Windows Forms .NET Framework](https://docs.microsoft.com/it-it/dotnet/desktop/winforms/controls/how-to-bind-data-to-the-windows-forms-datagridview-control?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/winforms/controls/how-to-bind-data-to-the-windows-forms-datagridview-control.md](https://github.com/dotnet/docs-desktop/blob/live/dotnet-desktop-guide/framework/winforms/controls/how-to-bind-data-to-the-windows-forms-datagridview-control.md)
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello!

I can't really provide support for your specific question. I don't believe the Northwind sample database for cusotmers is using an identity column.

I think you will have a better chance of getting your question answered if you post it on a forum such as StackOverflow. 

https://stackoverflow.com/questions/19071144/how-to-handle-identity-column-in-datagridview
https://stackoverflow.com/questions/17215029/c-sharp-datagridview-with-identity-column

I'm going to close the issue. 

Thanks.
