### ISSUE TITLE
The XAML example I find lacking

### ISSUE THREAD

**Issue by Rod-in-NM** [dotnet/docs-desktop#40]
The XAML example given on the Docs page, I find in adequate. Before the example it says:

> The text content of the TextBox in the following example is bound to the Age property (of type int) of a binding source object named ods. The binding is set up to use a validation rule named AgeRangeRule so that if the user enters non-numeric characters or a value that is smaller than 21 or greater than 130, a red exclamation mark appears next to the text box and a tool tip with the error message appears when the user moves the mouse over the text box.

I'm not understanding what **ods** might be. A field in a table? Another property in the viewmodel? I could use additional explanation, please.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44547693-9c95-8bd0-8911-2837b3550ba1
* Version Independent ID: 60ce7c58-08ae-5608-8c07-8a81d5031aeb
* Content: [How to: Implement Binding Validation - WPF .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/data/how-to-implement-binding-validation?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/data/how-to-implement-binding-validation.md](https://github.com/dotnet/docs-desktop/blob/live/dotnet-desktop-guide/framework/wpf/data/how-to-implement-binding-validation.md)
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
ods is the name of a static resource defined in the resources section of the xaml file, which maps to a class of some sort. The end of the article links to a binding example. Specifically the mainwindow.xaml file here: https://github.com/microsoft/WPF-Samples/blob/master/Data%20Binding/BindValidation/MainWindow.xaml defines the `ods` object.

To learn more about the basics of binding, check out [How to create as simple binding](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/data/how-to-create-a-simple-binding?view=netframeworkdesktop-4.8) and [Databinding Overview](https://docs.microsoft.com/en-us/dotnet/desktop-wpf/data/data-binding-overview?toc=%2Fdotnet%2Fframework%2Fwpf%2Fdata%2Ftoc.json&bc=%2Fdotnet%2Fframework%2Fwpf%2Fdata%2Fbreadcrumb%2Ftoc.json&view=netframeworkdesktop-4.8#basic-data-binding-concepts)

Hope this helps.
