### ISSUE TITLE
WPF Is Misspelled

### ISSUE THREAD

**Issue by Dextarius** [dotnet/docs-desktop#42]
In the section for 'Attached Events', I assume WPF is misspelled in the sentence "In the WOF implementation... "

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9024fd6b-79b6-4b3e-17f7-b7257fe39139
* Version Independent ID: dbdfb5d0-7d61-b4e1-3e91-42f785445c64
* Content: [XAML Syntax In Detail - WPF .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/xaml-syntax-in-detail?view=netframeworkdesktop-4.8&source=docs)
* Content Source: [dotnet-desktop-guide/framework/wpf/advanced/xaml-syntax-in-detail.md](https://github.com/dotnet/docs-desktop/blob/live/dotnet-desktop-guide/framework/wpf/advanced/xaml-syntax-in-detail.md)
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for opening this issue. I'll add it to the backlog. If you would like to contribute, you can submit a fix by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!
