### ISSUE TITLE
windowsForm

### ISSUE THREAD

**Issue by Elmerleonel1999** [dotnet/docs-desktop#46]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5088aa3f-addb-a600-bc90-9c1e6a4c8dfd
* Version Independent ID: 053d6ccf-6dff-ebb9-6a18-3adc0ea9f5f8
* Content: [Windows Forms - .NET](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/?view=netdesktop-5.0)
* Content Source: [dotnet-desktop-guide/net/winforms/index.md](https://github.com/dotnet/docs-desktop/blob/live/dotnet-desktop-guide/net/winforms/index.md)
* Product: **dotnet-desktop**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Hello @Elmerleonel1999 you, didn't leave a message with your question. Can you please add that? Thanks
