### ISSUE TITLE
Remove [xaml] plaintext from WPF articles.

### ISSUE THREAD

**Issue by adegeo** [dotnet/docs-desktop#56]
Some of the WPF articles have text `[xaml]` in them. I think it was there to mark a section as xaml code, but it's not needed. Find and remove these.

- [ ] dotnet-desktop-guide\framework\wpf\graphics-multimedia\how-to-create-a-cubic-bezier-curve.md
- [ ] dotnet-desktop-guide\framework\wpf\graphics-multimedia\how-to-create-a-linesegment-in-a-pathgeometry.md
- [ ] dotnet-desktop-guide\framework\wpf\graphics-multimedia\how-to-create-an-elliptical-arc.md
- [ ] dotnet-desktop-guide\framework\wpf\graphics-multimedia\how-to-create-a-quadratic-bezier-curve.md

**Comment by ccoyle** [comment]
Hi! I can take care of these.
