### ISSUE TITLE
Attached Properties Overview page is missing

### ISSUE THREAD

**Issue by JansthcirlU** [dotnet/docs-desktop#57]
**Issue description**

The documentation for [Attached Properties Overview](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/attached-properties-overview) is missing. It is still linked in related docs such as the [Dependency Properties Overview](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/dependency-properties-overview?view=netframeworkdesktop-4.8) page but gets redirected to a 404 when clicked.

**.NET or .NET Framework**

- [ ] .NET (5 or Core)
- [x] .NET Framework (4.x)

**Technology**

- [x] WPF
- [ ] Windows Forms

**.NET information**

If using the .NET SDK or .NET Core SDK, include `dotnet --info` output. If using .NET Framework without the .NET Core SDK, include info from Visual Studio's **Help** > **About Microsoft Visual Studio** dialog.

**Comment by adegeo** [comment]
Thanks! I noticed this about the same time too. I filed a fix but it sat over the weekend. It's merged now and should be live later tonight. Thanks again!

**Comment by JansthcirlU** [comment]
Page is still broken 12 hours after closing.
