### ISSUE TITLE
Code example comment lists Border instead of ScrollViewer

### ISSUE THREAD

**Issue by petroselo** [dotnet/docs-desktop#62]
In the first code example on this page, the last comment reads
"// Add the Border as the Content of the Parent Window Object"
I think it should not be "Border" but "ScrollViewer" like this.
// Add the ScrollViewer as the Content of the Parent Window Object

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 712dcc2a-20de-b5be-a9cf-2b548f76768e
* Version Independent ID: c4e96199-5cbd-f9ef-ba03-261614d02ffd
* Content: [ScrollViewer Overview - WPF .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/controls/scrollviewer-overview?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/controls/scrollviewer-overview.md](https://github.com/dotnet/docs-desktop/blob/master/dotnet-desktop-guide/framework/wpf/controls/scrollviewer-overview.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for opening this issue. I'll add it to the backlog.

Thanks again!
