### ISSUE TITLE
404 on first link in article for Dependency properties

### ISSUE THREAD

**Issue by ignispotentia** [dotnet/docs-desktop#66]
The first link the the first sentence of the article points to a 404 link.

Sentence in question:
Windows Presentation Foundation (WPF) provides a set of services that can be used to extend the functionality of a type's **property**. 

**property** points to https://docs.microsoft.com/en-us/dotnet/standard/base-types/common-type-syste#properties instead of
https://docs.microsoft.com/en-us/dotnet/standard/base-types/common-type-syste**m**#properties

Regards,
Milos

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73a26290-f551-b7c3-3677-426ea3fb39d9
* Version Independent ID: 8e6e4275-ed51-8425-7d6b-ee4a4b1c3fba
* Content: [Dependency properties overview - WPF .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/dependency-properties-overview?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/advanced/dependency-properties-overview.md](https://github.com/dotnet/docs-desktop/blob/live/dotnet-desktop-guide/framework/wpf/advanced/dependency-properties-overview.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for opening this issue. I'll add it to the backlog. If you would like to contribute, you can submit a fix by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!

**Comment by ignispotentia** [comment]
Thanks! I’ll fix it tonight.

Milos
