### ISSUE TITLE
just add link to list of characters...

### ISSUE THREAD

**Issue by itrashpod** [dotnet/docs-desktop#67]
just add link to list of characters...
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8089bee4-feef-f0a5-1691-120bfa240784
* Version Independent ID: 595f2172-fa4a-0d3e-03b0-516ca73f41cc
* Content: [How to: Use Special Characters in XAML - WPF .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/how-to-use-special-characters-in-xaml?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/advanced/how-to-use-special-characters-in-xaml.md](https://github.com/dotnet/docs-desktop/blob/master/dotnet-desktop-guide/framework/wpf/advanced/how-to-use-special-characters-in-xaml.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
It is also probably useful to mention that the reason for special character encoding is that the character interferes with the parsing of the XAML file. For example, the `"` character is used on attributes and therefore can't be used inside of an attribute value such as `Text="They said "Hello""`
