### ISSUE TITLE
DesiredHeight property in Style doesn't exist on Border control

### ISSUE THREAD

**Issue by Jim-arch** [dotnet/docs-desktop#83]
[Enter feedback here]
                            <Border x:Name="**Content**" Grid.Row="1" BorderThickness="1,0,1,1" CornerRadius="0,0,2,2">
                                <Border.BorderBrush>
                                    <SolidColorBrush Color="{DynamicResource BorderMediumColor}" />
                                </Border.BorderBrush>
                                <Border.Background>
                                    <SolidColorBrush Color="{DynamicResource ContentAreaColorDark}" />
                                </Border.Background>
                                <ContentPresenter Margin="4" />
                            </Border>
                        </Grid>
                        <ControlTemplate.Triggers>
                            <Trigger Property="IsExpanded" Value="True">
                                <Setter TargetName="ContentRow" Property="Height" Value="{Binding **DesiredHeight**, ElementName=**Content**}" />
                            </Trigger>
                        </ControlTemplate.Triggers>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdb9feb2-67b1-f850-9acb-38f05f9ce5f1
* Version Independent ID: 1ad823ca-dbdf-a145-0265-0cf29056ec98
* Content: [Expander Styles and Templates - WPF .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/controls/expander-styles-and-templates?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/wpf/controls/expander-styles-and-templates.md](https://github.com/dotnet/docs-desktop/blob/master/dotnet-desktop-guide/framework/wpf/controls/expander-styles-and-templates.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for opening this issue. I'll add it to the backlog. If you would like to contribute, you can submit a fix by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

I did a quick test and found that the value `Height` works.

Thanks again!
