### ISSUE TITLE
DataValidation against EF6 data

### ISSUE THREAD

**Issue by KDGundermann** [dotnet/docs-desktop#86]
[Enter feedback here]
I am displaying data coming from my database using EntityFramework 6 in the grid.
The EF6 class has already data annotations e.g. <Required> <StringLength(50)>
I don't want to repeat this constraints in the WinForms frontend, so how can I check against the EF6 class ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e0fef96-b91e-52da-9cff-26d9bcda458e
* Version Independent ID: 964e241c-13b6-0e91-f8dd-6885e4e91319
* Content: [Walkthrough: Validate data in DataGridView control - Windows Forms .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/controls/walkthrough-validating-data-in-the-windows-forms-datagridview-control?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/winforms/controls/walkthrough-validating-data-in-the-windows-forms-datagridview-control.md](https://github.com/dotnet/docs-desktop/blob/master/dotnet-desktop-guide/framework/winforms/controls/walkthrough-validating-data-in-the-windows-forms-datagridview-control.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
@KDGundermann Hi. I don't know much about EF6, but it looks like the constraint is just an attribute. You can look up that attribute and get the value. This article helps you understand how to read the attributes on something: https://docs.microsoft.com/en-us/dotnet/standard/attributes/retrieving-information-stored-in-attributes

You'll want to use reflection to get the property member with the attribute defined on it, then use the `Attribute.GetCustomAttribute` method to retrieve the attribute instance.

I also did a quick search on stackoverflow related to attributes and reflection and found this neat extension method that may help: https://stackoverflow.com/questions/23329087/get-custom-attribute-from-specific-object-property-field

I'm going to close this issue. If you need further help I encourage you to ask on stackoverflow as you'll get more people looking at your issue and possibly links to other solutions.

Cheers!
