### ISSUE TITLE
Configuration.Settings doesn't exist?

### ISSUE THREAD

**Issue by MHDeveloper30** [dotnet/docs-desktop#92]
Using c# Winforms Desktop .net core 5.0 RC2, trying to understand  configuration options in .net core

I'm confused... the document says for C# app access the settings object as below:

" If you created your settings using the Visual Studio Application Settings dialog box in the Property Editor, you can retrieve the default settings object generated for your language through the following expression.

Configuration.Settings.Default"

But the Configuration Class in System.Configuration doesn't have a Settings property.

I can access Mynamespace.Properties.Settings.Default.

Can someone clarify please, or is the document incorrect?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93200945-5dfb-d551-d286-e3df2cc09f55
* Version Independent ID: 3978e874-5b5c-b470-66fb-fd6218b0f16f
* Content: [How to: Validate Application Settings - Windows Forms .NET Framework](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/advanced/how-to-validate-application-settings?view=netframeworkdesktop-4.8)
* Content Source: [dotnet-desktop-guide/framework/winforms/advanced/how-to-validate-application-settings.md](https://github.com/dotnet/docs-desktop/blob/master/dotnet-desktop-guide/framework/winforms/advanced/how-to-validate-application-settings.md)
* Product: **dotnet-framework**
* Technology: **dotnet-winforms**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment]
Thank you for opening this issue. I'll add it to the backlog. Seems like the docs are incorrect!! It should be `Properties.Settings.Default` as you found.

If you would like to contribute, you can submit a fix by editing the original article. Click on the **Content Source** link at the bottom of your original comment. To learn how to edit, see the [Editing files in a repository](https://help.github.com/articles/editing-files-in-your-repository) article from GitHub.

Thanks again!

**Comment by MHDeveloper30** [comment]
Done. Thanks for help with this – my first contribution!
